### ISSUE TITLE
Expose non top-level input and output connectors, particularly for FMI export

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#10599]
FMI export exposes parameters from all hierarchy levels. This is not the case for inputs and outputs though, requiring clumsy model extensions propagating them to the top level. Take `Modelica.Fluid.Examples.DrumBoiler` as example:

![Screenshot from 2023-04-23 21-19-17](https://user-images.githubusercontent.com/4224368/233860426-fb09948d-4ed9-41d9-b938-60e39b5f2ec1.png)

It would be great if inputs and outputs were also exposed from all hierarchy levels, like parameters, avoiding explicit `Y_Valve`, `qm_S` and the like.

Take the following screenshot of `ThermofluidStream.Examples.SimpleStream` as another example. Similarly to other Modelica libraries, the source and sensor components offer signal input and output connectors, respectively. Imagine how additional top level connectors that are currently required for FMI export would mess this up: 
![Screenshot from 2023-04-23 20-16-41](https://user-images.githubusercontent.com/4224368/233857684-d4a3759d-3c9e-4335-aaba-16ea1f27ec76.png)
It should be a non-issue to directly expose outputs. Inputs are a bit trickier as they influence the model. But why not give it a try?

Here is a test example that illustrates typical patterns in Modelica libraries:
- signal and physical connectors
- a Source offering a conditional signal input
- a Component additionally using an input intended for modification in a user dialog
- a Signaling block used on different hierarchy levels
- and finally a System model
```Modelica
package LocalIOs

connector RealInput = input Real;
connector RealOutput = output Real;

connector PhysicalConnector
  Real p;
  flow Real f;
end PhysicalConnector;

model Source
  parameter Real u_par = 2;
  parameter Boolean use_u_in = false;
  RealInput u_in(start = u_par) if use_u_in;
  RealOutput yp;
  RealOutput yf;
  PhysicalConnector c;
protected
  RealInput u_in_internal;
equation
  connect(u_in, u_in_internal);
  if not use_u_in then
    u_in_internal = u_par;
  end if;
  c.p = u_in_internal;
  connect(u_in_internal, yp);
  yf = c.f;
end Source;

model Component
  PhysicalConnector c;
  input Real modifiedInput annotation(Dialog(enable=true));
  RealOutput measurement;
protected
  Signaling signaling(u1 = 1);
equation
  signaling.u2 = 2;
  c.f = 0.5*c.p + modifiedInput + signaling.y;
  connect(signaling.y, measurement);
end Component;

block Signaling
  RealInput u1;
  RealInput u2;
  RealOutput y;
equation
  y = u1 + u2;
end Signaling;

model System
  Source source(use_u_in = true);
  Component component(modifiedInput = 1);
  Signaling signaling;
equation
  connect(source.c, component.c);
  connect(source.yf, signaling.u1);
end System;

end LocalIOs;
```
OpenModelica refuses to translate the System model.
```
[1] Symbolic Error
Too few equations, under-determined system. The model has 14 equation(s) and 16 variable(s).
```
The inputs `source.u_in` and `signaling.u2` are considered unassigned. Couldn't a compile option be introduced to expose them as model inputs instead?
Similarly, why not exposing `source.yp`, `component.measurement` and `signaling.y` as model outputs when exporting an FMU?

**Comment by rfranke** [comment]
Here is an example how --exposeLocalIOs might be useful beyond FMI export. The above `Source` model is quite clumsy to get a conditional signal input. This pattern appears in many Modelica libraries.
Exploiting --exposeLocalIOs, the additional `use_u_in` and `u_in_internal` including connect statement are not needed anymore. The parameter `u_par` becomes `u_default` whenever `u_in` remains unconnected.
```Modelica
model SourceExploitingLocalIOs
  parameter Real u_default = 2;
  RealInput u_in(start = u_default);
  RealOutput yp;
  RealOutput yf;
  PhysicalConnector c;
equation
  c.p = u_in;
  yf = c.f;
  connect(u_in, yp);
end SourceExploitingLocalIOs;
```

**Comment by rfranke** [comment]
There is a problem with Modelica.Media that intentionally uses local input connectors:
https://github.com/modelica/ModelicaStandardLibrary/blob/7d2e8d7a7e2738f9eaa0fe45ca21af54eb1e6ac9/Modelica/Media/package.mo#L4003-L4009
defined as:
https://github.com/modelica/ModelicaStandardLibrary/blob/7d2e8d7a7e2738f9eaa0fe45ca21af54eb1e6ac9/Modelica/Media/package.mo#L3976-L3983
Everything might work fine with
```Modelica
      input SI.AbsolutePressure p "Absolute pressure of medium";
      input SI.MassFraction[nXi] Xi(start=reference_X[1:nXi]) "Structurally independent mass fractions";
      input SI.SpecificEnthalpy h "Specific enthalpy of medium";
```
But for now the best solution appears to make the flag `--exposeLocalIOs` an integer, 0 meaning top-level, 1 to include input/output connectors of top level components -- like `source.p_in` (see above screenshots), 2 going one level deeper -- like the bad `source.medium.p`, and so on.

PR #10606 does this.

**Comment by casella** [comment]
@franke I don't see any problem exposing non-top level _outputs_ when generating FMUs. How a compilable model maps into an FMU is tool dependent, same way as how a top-level input, see Section 4.4.2.2 of the MLS.

I am a bit doubtful about exposing non-top level _inputs_ in terms of Modelica semantics, which I understand is what you are proposing [here](https://github.com/OpenModelica/OpenModelica/issues/10599#issuecomment-1519498977). This could be a good idea, but it seems to me that it should be changed in the Modelica Language specification first. This also impact the balanced model analysis, see [Section 4.7](https://specification.modelica.org/maint/3.6/class-predefined-types-and-declarations.html#prefix-rules).

**Comment by rfranke** [comment]
You are right. Trying in Dymola, I get a warning about input variables without binding equation when not using connectors in `BaseProperties`. Interestingly `ThermofluidStream` does not use a generic `medium` model, but just specific state records with generic access methods -- another way to get rid of those weird connectors without connection.

Regarding standardization, it's a bit of hen and egg problem. We need to explore such a feature before proposing an extension to the Modelica standard. The current test implementation looks promising for non top-level inputs too: the simple rule is to only expose inputs that are never inside in a connection set (generalizing top-level inputs). Additionally inputs without binding equation -- which should not happen according to the current standard -- but would work. The simulator can take the start value as default if left unconnected.

**Comment by casella** [comment]
> Regarding standardization, it's a bit of hen and egg problem. We need to explore such a feature before proposing an extension to the Modelica standard.

Absolutely. It just needs to be very clear that it is an experimental feature, so people should not expect to have it supported forever, nor to have it supported in other Modelica tools. As you understand well, this is sometimes tricky/subtle and can have profound political implications 😅 . See the recent discussion about Modelica standardization on the modelica-design mailing list.

**Comment by casella** [comment]
From that point of view, I would suggest to put this feature under the [--allowNonStandardModelica](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-allownonstandardmodelica) flag.

If the proposal makes way into the MLS draft, then we can just turn it on by default.

**Comment by perost** [comment]
> Does --allowNonStandardModelica support integer options, like
> 
> ```
>   --allowNonStandardModelica=protectedAccess,exposeLocalIOs=2
> ```
> 
> ?

No, it only takes a list of strings. The way you've implemented it is currently the only option if you want an integer flag.

**Comment by casella** [comment]
OK, that's not absolutely necessary, we can keep `--exposeLocalIOs `for the time being. But it would be nice to avoid polluting the namespace of compiler flags with non-standard stuff.

**Comment by rfranke** [comment]
Still open. After a discussion with @AnHeuermann at OpenModelica workshop in February (didn't find time since then), a better idea appears to be extending the model at hand with top-level IOs, i.e. automatically add things that a modeler could also add manually, without braking the Modelica standard.

**Comment by rfranke** [comment]
See #12303. Here is what it does for a simple example:
![Screenshot from 2024-04-24 07-18-27](https://github.com/OpenModelica/OpenModelica/assets/4224368/6539dfc4-b2d5-42e1-aa10-d8b2222e9e47)
```Modelica
model Example
  Modelica.Blocks.Continuous.Integrator integrator(use_reset = true, use_set = false);
  Modelica.Blocks.Math.Gain gain;
  Modelica.Blocks.Math.Feedback feedback(u1(start=1));
  Modelica.Blocks.Math.Sign sign1;
equation
  connect(integrator.y, feedback.u2);
  connect(feedback.y, gain.u);
  connect(gain.y, integrator.u);
  connect(integrator.y, sign1.u);
annotation(
    uses(Modelica(version = "4.0.0")));
end Example;
```
Call `omc --exposeLocalIOs=1 Example.mo` to get this instantiated model -- mind `sign1_y`, `feedback_u1` and `integrator_reet`:
```Modelica
class Example
  final parameter Boolean sign1.generateEvent = false "Choose whether events shall be generated";
  Real sign1.y "Connector of Real output signal";
  Real sign1.u "Connector of Real input signal";
  Real feedback.y;
  Real feedback.u2 "Feedback input";
  Real feedback.u1(start = 1.0) "Commanded input";
  Real gain.y "Output signal connector";
  Real gain.u "Input signal connector";
  parameter Real gain.k(unit = "1", start = 1.0) "Gain value multiplied with input signal";
  protected Real integrator.local_set;
  protected Boolean integrator.local_reset;
  Boolean integrator.reset "Optional connector of reset signal";
  Real integrator.y(start = integrator.y_start) "Connector of Real output signal";
  Real integrator.u "Connector of Real input signal";
  parameter Real integrator.y_start = 0.0 "Initial or guess value of output (= state)";
  final parameter enumeration(NoInit, SteadyState, InitialState, InitialOutput) integrator.initType = Modelica.Blocks.Types.Init.InitialState "Type of initialization (1: no init, 2: steady state, 3,4: initial output)";
  final parameter Boolean integrator.use_set = false "= true, if set port enabled and used as reinitialization value when reset";
  final parameter Boolean integrator.use_reset = true "= true, if reset port enabled";
  parameter Real integrator.k(unit = "1") = 1.0 "Integrator gain";
  output Real sign1_y "Connector of Real output signal";
  input Real feedback_u1(start = 1.0) "Commanded input";
  input Boolean integrator_reset "Optional connector of reset signal";
initial equation
  integrator.y = integrator.y_start;
equation
  sign1.y = if noEvent(sign1.u > 0.0) then 1.0 else if noEvent(sign1.u < 0.0) then -1.0 else 0.0;
  feedback.y = feedback.u1 - feedback.u2;
  gain.y = gain.k * gain.u;
  der(integrator.y) = integrator.k * integrator.u;
  when integrator.local_reset then
    reinit(integrator.y, integrator.local_set);
  end when;
  integrator.local_set = integrator.y_start;
  gain.y = integrator.u;
  feedback.y = gain.u;
  integrator.y = feedback.u2;
  integrator.y = sign1.u;
  integrator.reset = integrator.local_reset;
  sign1.y = sign1_y;
  feedback.u1 = feedback_u1;
  integrator.reset = integrator_reset;
end Example;
```
The variable browser of OMEdit shows -- do also mind the propagation of attributes like start value and description:
![Screenshot from 2024-04-24 07-29-27](https://github.com/OpenModelica/OpenModelica/assets/4224368/177b2575-6fc7-4ea1-bfe4-729c11e57f5d)

**Comment by casella** [comment]
@rfranke it's not clear to me how the names of the newly created top level inputs are determined

**Comment by perost** [comment]
> @rfranke it's not clear to me how the names of the newly created top level inputs are determined

It changes the `.` in the original name to `_`, while keeping the last subscripts (this might not be intentional, see my comment in the PR). So e.g. `a.b[2].c[3]` => `a_b_c[3]`. And if the name still isn't unique it adds `_` to the end of the name until it is.

**Comment by rfranke** [comment]
@casella sounds interesting. Quotes are typically tricky during processing, but elegant if it works out. Will investigate this.

**Comment by rfranke** [comment]
Here is the tricky part, independently of exposeLocalIOs:
```Modelica
model Quoted
  model Sub
    Real 'y' = 1;
  end Sub;
  Sub sub;
  Real 'sub.y' = 2;
end Quoted;
```
gives with the current master branch:
![Screenshot from 2024-04-25 08-33-18](https://github.com/OpenModelica/OpenModelica/assets/4224368/0531b22f-6430-4369-867c-7f4ef6ac50ab)

Version 1.22.3 gives:
![Screenshot from 2024-04-25 08-36-57](https://github.com/OpenModelica/OpenModelica/assets/4224368/f40ef086-5947-4208-ae7b-7cb6cffd6be0)

Neither quote of quotes with current master branch nor splitted tree view for `'sub.y'` look right. The latter might just be an OMEdit display issue, but why did you introduce those quote of quotes recently?

**Comment by rfranke** [comment]
Btw. the rule that `'y'` and `y` are two different identifiers also contributes to the trickiness in my mind. Would prefer a definition saying that they are the same.

**Comment by rfranke** [comment]
@AnHeuermann, @adeas31 you seem to be working on quoted identifiers.
Where does the \-quoting of '-quotes come from lately?
Shouldn't OMEdit keep `'sub.y'` as one entry?

**Comment by rfranke** [comment]
@casella I merged the PR (squashing corrections after the review by @perost).
Quoted identifiers appear to be a different story. Treated right, the change might even become invisible to users of the implementation in OpenModelica 1.22, as `component.u` would not become `component_u` but `'component.u'` then.
Just, please fix `\\'component.u\\'`.

**Comment by adeas31** [comment]
> Shouldn't OMEdit keep 'sub.y' as one entry?

Yes. I will fix it.

**Comment by adeas31** [comment]
![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/f075b451-1c59-4a1d-a6d0-c4fbcb6d9ca4)

**Comment by casella** [comment]
As a side note, when importing Base Modelica models obtained by flattening structured Modelica models, it may actually be useful to strip the quotes and still get a tree view of the variables, instead of a flat one. This should be optional, though. I'll open a separate ticket about that.

**Comment by rfranke** [comment]
This is what I get with the recent master branch -- \\-quotes are gone, thank you. Still splitting though and the variable values have been replaced with empty entry boxes?!

![Screenshot from 2024-04-26 16-30-54](https://github.com/OpenModelica/OpenModelica/assets/4224368/b6fb87fb-0a5e-49fc-82b6-09ce0739268a)

**Comment by rfranke** [comment]
Unfortunately \\-quotes are still present in FMI export, see e.g. modelDescription.xml of `OpenModelica/testsuite/openmodelica/cppruntime/fmu/modelExchange/2.0/exposeLocalIOs.mos` -- `\\\\'component.measurement\\\\'`.
This wasn't the case with version 1.22.3. Where do they come from?
```
Equation mismatch: diff says:
--- /tmp/omc-rtest-rfranke/openmodelica/cppruntime/fmu/modelExchange/2.0/equations-expected	2024-04-26 16:40:45.776019052 +0200
+++ /tmp/omc-rtest-rfranke/openmodelica/cppruntime/fmu/modelExchange/2.0/equations-got	2024-04-26 16:40:50.251993420 +0200
@@ -31,76 +31,76 @@
 </LogCategories>
 <DefaultExperiment startTime=\"0.0\" stopTime=\"1.0\" tolerance=\"1e-6\" stepSize=\"0.002\"/>
 <ModelVariables>
 <!-- Index of variable = \"1\" -->
 <ScalarVariable
-name=\"component.m.p\"
+name=\"\\\\'component.measurement\\\\'\"
```

**Comment by adeas31** [comment]
> This is what I get with the recent master branch -- \-quotes are gone, thank you. Still splitting though and the variable values have been replaced with empty entry boxes?!
> 
> ![Screenshot from 2024-04-26 16-30-54](https://private-user-images.githubusercontent.com/4224368/326013061-b6fb87fb-0a5e-49fc-82b6-09ce0739268a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzQyMjEsIm5iZiI6MTcxNDE3MzkyMSwicGF0aCI6Ii80MjI0MzY4LzMyNjAxMzA2MS1iNmZiODdmYi0wYTVlLTQ5ZmMtODJiNi0wOWNlMDczOTI2OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMjMyNTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxMzJmODgyNDNmZGEzNjgwZGRhN2EyY2Q0ODJhOTMxNTBmMTVhMGFiZDFlNmE4ZGJjNmU5M2VlNDhmZWQ5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BhFNJlzFjchLle4HcpwB3n7MX3g5ad54KEhPhyoR3tQ)

Strange. Are you sure you compiled OMEdit with the latest changes.

**Comment by casella** [comment]
> Unfortunately \-quotes are still present in FMI export, see e.g. modelDescription.xml for Quoted defined above.
This wasn't the case with version 1.22.3.
> @casella looks like related to Base Modelica. Why have those \-quotes of Modelica '-quotes been introduced?

@rfranke, as far as I understand, Base Modelica stuff is only activated with [--BaseModelica](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-basemodelica). @perost can you please confirm?

@AnHeuermann did something to make sure that valid CSV files are generated when you have quoted identifiers (independently of Base Modelica, those could be used in any Modelica model, though they haven't been used much).  I guess that could be the reason, @AnHeuermann can you please comment on that?

**Comment by perost** [comment]
> > Unfortunately -quotes are still present in FMI export, see e.g. modelDescription.xml for Quoted defined above.
> > This wasn't the case with version 1.22.3.
> > @casella looks like related to Base Modelica. Why have those -quotes of Modelica '-quotes been introduced?
> 
> @rfranke, as far as I understand, Base Modelica stuff is only activated with [--BaseModelica](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-basemodelica). @perost can you please confirm?

Yes, the frontend only prints out quotes when dumping Base Modelica models, which doesn't affect the actual flat model sent to the backend but only the textual output. So any such issues are not related to Base Modelica but rather how quoted identifiers are handled in general.

**Comment by rfranke** [comment]
Not directy. Just speculated that Base Modelica brought attention to quoted identifiers, triggering the fix 32420612402cd85aa7d05f9b40b357b66e3b7a22 for CSV files and probably braking FMI (and OMEdit variable browser until two days ago).

**Comment by rfranke** [comment]
> > This is what I get with the recent master branch -- -quotes are gone, thank you. Still splitting though and the variable values have been replaced with empty entry boxes?!
> > ![Screenshot from 2024-04-26 16-30-54](https://private-user-images.githubusercontent.com/4224368/326013061-b6fb87fb-0a5e-49fc-82b6-09ce0739268a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzQyMjEsIm5iZiI6MTcxNDE3MzkyMSwicGF0aCI6Ii80MjI0MzY4LzMyNjAxMzA2MS1iNmZiODdmYi0wYTVlLTQ5ZmMtODJiNi0wOWNlMDczOTI2OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMjMyNTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUxMzJmODgyNDNmZGEzNjgwZGRhN2EyY2Q0ODJhOTMxNTBmMTVhMGFiZDFlNmE4ZGJjNmU5M2VlNDhmZWQ5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BhFNJlzFjchLle4HcpwB3n7MX3g5ad54KEhPhyoR3tQ)
> 
> Strange. Are you sure you compiled OMEdit with the latest changes.

Everything except the latest commit ae47b0440a72b56e756c9b4711b68e4b7bd62a14

**Comment by rfranke** [comment]
The FMI problem is gone in my local dev version when reverting 32420612402cd85aa7d05f9b40b357b66e3b7a22.
```XML
  <ModelVariables>
  <!-- Index of variable = "1" -->
  <ScalarVariable
    name="'sub.y'"
    valueReference="0"
    initial="exact">
    <Real start="0.0"/>
  </ScalarVariable>
  <!-- Index of variable = "2" -->
  <ScalarVariable
    name="sub.'y'"
    valueReference="1"
    initial="exact">
    <Real start="0.0"/>
  </ScalarVariable>
  </ModelVariables>
```

**Comment by rfranke** [comment]
Finally also a result for the elegant side of quotes. The above given Example looks nicer with `'a.b'` instead of `a_b`. Also having the exposed IOs sorted at the top is neat :)

![Screenshot from 2024-04-27 12-14-26](https://github.com/OpenModelica/OpenModelica/assets/4224368/8f390b86-dad1-4c6a-a573-33fc1c9e65ad)

**Comment by casella** [comment]
OK. @AnHeuermann please check #12250 and make sure @rfranke's issue is fixed. Thanks!

**Comment by rfranke** [comment]
> OK. @AnHeuermann please check #12250 and make sure @rfranke's issue is fixed. Thanks!

"My" issue is `modelDescription.xml` for FMI export with quoted identifiers.

**Comment by AnHeuermann** [comment]
> @AnHeuermann did something to make sure that valid CSV files are generated when you have quoted identifiers

Well no, it's really easy to break the CSV files with `Real '\"'` and similar, see https://github.com/OpenModelica/OpenModelica/issues/12309.

BaseModelica has it's own grammar file which I did not change: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Parser/BaseModelica_Lexer.g#L427-L439

So we need to update that as well, similar to https://github.com/OpenModelica/OpenModelica/pull/12250.

> The best thing with this: as we are removing quotes when importing FMUs to our runtime, users won't see a difference between non-standard feedback.u1 with OM 1.22 and standard feedback.u1 (removed quotes) with OM 1.23 :)

Remember that some madman decided that `''` is a valid quoted identifier 😆

**Comment by AnHeuermann** [comment]
Oh and I need to find the location where quoted identifiers are generated for the XML code where `'` doesn't need to be escaped.

```diff
  <ModelVariables>
  <!-- Index of variable = "1" -->
  <ScalarVariable
    name="\\'sub.y\\'"
    valueReference="0"
    initial="exact">
    <Real start="0.0"/>
  </ScalarVariable>
  <!-- Index of variable = "2" -->
  <ScalarVariable
    name="sub.\\'y\\'"
    valueReference="1"
    initial="exact">
    <Real start="0.0"/>
  </ScalarVariable>
  </ModelVariables>
```

**Comment by casella** [comment]
@AnHeuermann as far as I understand the grammar of quoted identifiers is not Base-Modelica-specific, it's been part of the Modelica grammar since the beginning :)

The idea was that by using it one could use Japanese variable names or something like that, thanks to Unicode support. In fact, nobody ever did that, so we never supported Q-IDENTs and nobody cared, until Base Modelica made them compulsory, to deal with variable names such as m[2].x[4] which are not legal in Modelica.

So, we are not really adding support to Base Modelica, only making sure we completely support the Modelica grammar 😃

**Comment by casella** [comment]
As discussed during today's devmeeting, we also need to make sure that OMSimulator can read all the escaped stuff

**Comment by AnHeuermann** [comment]
We'll ignore `'` for now and will fix it when someone needs this. It would involve changes to OMSimulator. As of now OMSimulator can handle the FMU from https://github.com/OpenModelica/OpenModelica/pull/12346.
@adeas31 so nothing to do for OMSimulator.

**Comment by casella** [comment]
@rfranke are you fine with this fixed being in 1.24.0?
