### ISSUE TITLE
co-simulation FMU export: memory leak in simulation

### ISSUE THREAD

**Issue by sturmk** [OpenModelica/OpenModelica#10790]
### Description
Detected a memory leak in exported C-code / FMUs.
Memory pool continues to grow until simulation crashes/is killed by the OS due to excessive memory usage.

### Steps to Reproduce
If a modelica module contains a function with a protected real array (e.g. in Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.dptofT or Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.tsat), the generated C-code allocates space for the real_array, but does not free it before function return. Thereby the memory pool keeps growing. The garbage collector does not catch this.

### Expected Behavior
If possible, code generator should issue a "free" on the allocated array before function return to prevent memory leak.

### Screenshots
Memory profiling output of valgrind/massif
```
100.00% (3,221,512,364B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->99.99% (3,221,266,528B) 0x5950BEF: malloc_zero (in /path/to/FMU/binaries/linux64/PSS.so)
| ->99.99% (3,221,225,472B) 0x5950B9C: pool_malloc (in /path/to/FMU/binaries/linux64/PSS.so)
| | ->99.99% (3,221,225,472B) 0x5953554: alloc_real_array (in /path/to/FMU/binaries/linux64/PSS.so)
| |   ->66.66% (2,147,483,648B) 0x58B72F8: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_dptofT (PSS_functions.c:9636)
| |   | ->66.66% (2,147,483,648B) 0x589D8E2: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_boilingcurve__p (PSS_functions.c:20111)
| |   |   ->66.66% (2,147,483,648B) 0x58FBA93: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_hl__p (PSS_functions.c:20766)
| |   |     ->66.66% (2,147,483,648B) 0x58B3282: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_region__ph (PSS_functions.c:21580)
| |   |       ->66.66% (2,147,483,648B) 0x58B15DB: omc_Modelica_Media_Water_IF97__Utilities_waterBaseProp__ph (PSS_functions.c:1847)
| |   |         ->66.66% (2,147,483,648B) 0x590894F: PSS_eqFunction_216 (PSS_02nls.c:326)
| |   |           ->66.66% (2,147,483,648B) 0x5908D20: residualFunc219 (PSS_02nls.c:383)
| |   |             ->66.66% (2,147,483,648B) 0x5972792: wrapper_fvec (in /home/karl/OpenFOAM/karl-9/platforms/linux64GccDPInt32Debug/lib/FMUs/v01/binaries/linux64/PSS.so)
| |   |               ->66.66% (2,147,483,648B) 0x59766F2: getNumericalJacobianHomotopy (in /home/karl/OpenFOAM/karl-9/platforms/linux64GccDPInt32Debug/lib/FMUs/v01/binaries/linux64/PSS.so)
| |   |               | ->66.66% (2,147,483,648B) 0x59727E0: wrapper_fvec_der (in /home/karl/OpenFOAM/karl-9/platforms/linux64GccDPInt32Debug/lib/FMUs/v01/binaries/linux64/PSS.so)
| |   |               |   ->66.66% (2,147,483,648B) 0x597212E: solveHomotopy (in /home/karl/OpenFOAM/karl-9/platforms/linux64GccDPInt32Debug/lib/FMUs/v01/binaries/linux64/PSS.so)
| |   |               |     ->66.66% (2,147,483,648B) 0x595D624: solve_nonlinear_system (in /home/karl/OpenFOAM/karl-9/platforms/linux64GccDPInt32Debug/lib/FMUs/v01/binaries/linux64/PSS.so)
| |   |               |       ->66.66% (2,147,483,648B) 0x588F6B3: PSS_eqFunction_219 (PSS.c:470)
| |   |               |         ->66.66% (2,147,483,648B) 0x5897666: functionODE_system0 (PSS.c:3529)
| |   |               |           ->66.66% (2,147,483,648B) 0x58974B9: PSS_functionODE (PSS.c:3677)
| |   |               |             ->66.66% (2,147,483,648B) 0x594EEE6: internalGetEventIndicators (fmu2_model_interface.c.inc:1989)
| |   |               |               ->66.66% (2,147,483,648B) 0x59500A4: fmi2DoStep (fmu2_model_interface.c.inc:2311)
| |   |               |                 ->66.66% (2,147,483,648B) 0x48D246E: fmi2_capi_do_step (fmi2_capi_cs.c:41)
| |   |               |                   ->66.66% (2,147,483,648B) 0x486E7DE: fmi2_import_do_step (fmi2_import_capi.c:374)
[...]
| |   |               |                         ->66.66% (2,147,483,648B) 0x10C100: main (memleak.cpp:72)
| |   |               |                           
| |   |               ->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)
| |   |               
| |   ->33.33% (1,073,741,824B) 0x58B6268: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Basic_tsat (PSS_functions.c:11576)
| |   | ->33.33% (1,073,741,824B) 0x58B341D: omc_Modelica_Media_Water_IF97__Utilities_BaseIF97_Regions_region__ph (PSS_functions.c:21625)
| |   |   ->33.33% (1,073,741,824B) 0x58B15DB: omc_Modelica_Media_Water_IF97__Utilities_waterBaseProp__ph (PSS_functions.c:1847)
| |   |     ->33.33% (1,073,741,824B) 0x590894F: PSS_eqFunction_216 (PSS_02nls.c:326)
| |   |       ->33.33% (1,073,741,824B) 0x5908D20: residualFunc219 (PSS_02nls.c:383)
| |   |         ->33.33% (1,073,741,824B) 0x5972792: wrapper_fvec (in /path/to/FMU/binaries/linux64/PSS.so)
| |   |           ->33.33% (1,073,741,824B) 0x5972113: solveHomotopy (in /path/to/FMU/binaries/linux64/PSS.so)
| |   |           | ->33.33% (1,073,741,824B) 0x595D624: solve_nonlinear_system (in /path/to/FMU/binaries/linux64/PSS.so)
| |   |           |   ->33.33% (1,073,741,824B) 0x588F6B3: PSS_eqFunction_219 (PSS.c:470)
| |   |           |     ->33.33% (1,073,741,824B) 0x5897666: functionODE_system0 (PSS.c:3529)
| |   |           |       ->33.33% (1,073,741,824B) 0x58974B9: PSS_functionODE (PSS.c:3677)
| |   |           |         ->33.33% (1,073,741,824B) 0x594EEE6: internalGetEventIndicators (fmu2_model_interface.c.inc:1989)
| |   |           |           ->33.33% (1,073,741,824B) 0x59500A4: fmi2DoStep (fmu2_model_interface.c.inc:2311)
| |   |           |             ->33.33% (1,073,741,824B) 0x48D246E: fmi2_capi_do_step (fmi2_capi_cs.c:41)
| |   |           |               ->33.33% (1,073,741,824B) 0x486E7DE: fmi2_import_do_step (fmi2_import_capi.c:374)
[...]
| |   |           |                     ->33.33% (1,073,741,824B) 0x10C100: main (memleak.cpp:72)
| |   |           |                       
| |   |           ->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)
| |   |           
| |   ->00.00% (0B) in 1+ places, all below ms_print's threshold (01.00%)
| |   
| ->00.00% (41,056B) in 1+ places, all below ms_print's threshold (01.00%)
| 
->00.01% (245,836B) in 1+ places, all below ms_print's threshold (01.00%)

```
### Additional Context
I would like to fix the issue, but I am not familiar with the OMC backend or how its code generation works. I need assistance in fixing this issue.

**Comment by casella** [comment]
@mahge, @arun3688 can you please help?

**Comment by sturmk** [comment]
update: this problem presents itself not only with protected real arrays, but with *all* real arrays
(e.g. Media.Interfaces.PartialMedium.BaseProperties: `MassFraction[nX] X`)

**Comment by sturmk** [comment]
turns out the proposed solution is not that easy: while there is a function definition for `void free_real_array_data` in util/real_array.h, nobody seems to have implemented it yet.
Also, looking at the interface to the garbage collector, I can't seem to readily find a function that lets me tag an object as "to be freed" @adrpo do you have more insights on the topic?

**Comment by casella** [comment]
@mahge this is definitely worth fixing with high priority, I'd say

**Comment by mahge** [comment]
The problem with this is that the normal (non-fmu) simulations use garbage collector. Due to this, most of the code is written (or has been adjusted since it was written first) with the assumption that there is a garbage collector. FMUs, however, do not use the garbage collector. They use the small memory pool implementation we have. 

The memory pool should be told to reclaim some of the "allocated" memory (by simulation variable arrays, for example) periodically. We need to issue this manual reclaim requests when we are 100% sure that the allocated memory (simulation variable arrays, for example) are no longer needed. We can not reclaim the memory in every function because some arrays can be returned from functions.    

I am not sure what the best place for this is. I guess we can issue it somewhere around `fmi2DoStep` and see if it makes a difference for now. @AnHeuermann maybe you can help.

@sturmk can you also tell me exactly how to reproduce your issue. Just so we can duplicate it easily and also verify it if we manage to find a solution. Thanks.

**Comment by sturmk** [comment]
@mahge 
[memleak.zip](https://github.com/OpenModelica/OpenModelica/files/11651617/memleak.zip)

**Comment by mahge** [comment]
@sturmk This should be now be mitigated to some extent now. Valgrind will probably still report some leaks but I think the model should be fine now. 

Unfortunately, I never managed to run your testcase itself because I did not have all the requirements installed. The issue is common anyway, so I tested it with other models and setup. Please check the latest nightly build and let us know if the issue is still there in your setup.

**Comment by sturmk** [comment]
@mahge Thank you for the mitigation, it is a lot better now!
However, unfortunately, for our use cases, we still run into trouble with the remaining memory leak after a while.
> LOG_ASSERT | debug | /tmp/OpenModelica_karl/OMEdit/PSS/PSS.fmutmp/sources/gc/memory_pool.c:97: pool_expand: Assertion '0 && "Attempt to allocate an unusually large memory. The memory management does not seem to be working as intended. Please create an issue on https://github.com/OpenModelica/OpenModelica/issues."' failed.

**Comment by casella** [comment]
One wonders what "unusually large" actually means 😅. Is that 1 MB or 1 GB?

**Comment by mahge** [comment]
> One wonders what "unusually large" actually means 😅. Is that 1 MB or 1 GB?

It was set at 1GB 🙂. I figured once you ask for 1GB allocation, something has gone wrong in the first place. 

The improvement done in #10901 reclaimed the memory in some specific places where it made sense to do so. I think we might need to cover even more execution paths.   

I was unable to test your provided test case (assuming it is the same model that still exabits the issue) because I did not have all the required tools/libraries to use the provided python script. Can you tell me exactly how to reproduce the issue step by step?

**Comment by casella** [comment]
@JavierArroyoBastida are you trying with the latest omc nightly build, including #10901?

**Comment by JavierArroyoBastida** [comment]
I'm using `OpenModelica 1.23.0~dev-97-g7e09cdd` which includes #10901.

**Comment by casella** [comment]
It seems there are other memory leaks than the one fixed in #11233. @sturmk would like like to hunt for that?

**Comment by sturmk** [comment]
I can't promise any memory leak hunting before the new year;
In the meantime, as a workaround, I can only suggest saving the FMU's state, serializing it, and restarting the simulation (that's how we did it in the end)

**Comment by JavierArroyoBastida** [comment]
Could you provide some further insights into how to implement your solution in [this comment](https://github.com/OpenModelica/OpenModelica/issues/10790#issuecomment-1832821946)?
Thanks for looking into this! even if from January, it'll be very helpful :) Just noting that my model is rather large, with many inputs and outputs to be stored. So this may not apply to other models.

**Comment by JavierArroyoBastida** [comment]
That sounds like a nice approach. I'll give it a try. Thanks for the hint @sturmk!

**Comment by sturmk** [comment]
Sorry for the long delay, but I only just got back to the topic.
The problem still persists for functions where an array is allocated.

For example: take the following function from the MSL: `omc.Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.g2`.

In this function, the array of auxiliary variables `Real[55] o` is allocated (in an FMU, this translates to the following C code: `alloc_real_array(&(_o), 1, (_index_t)55);`). Since this function should be 'pure'/stateless, the auxiliary variables `o[]` should not persist between repeated function calls, and it should be "forgotten" (free'd). Unfortunately, before function return, OMC does not insert a de-allocation call to free the temporary variable in the generated C code.
Therefore, upon repeated calls to the function, the memory pool is expanded more and more until it overflows.

The pattern is the same with `omc.Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.g1`,
`omc.Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.g2`,
`omc.Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.tsat` and
`omc.Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.dptofT`.
These are the functions that I can pinpoint currently in my application in terms of the overgrowing memory issue, and they coincide with my initial bug report in this issue thread.

So I am still convinced this is a compiler problem that should be dealt with. At least from compiler theory and context-sensitive grammars, one should be able to catch the case of "pure function" and "temporary allocation of array", and generate a fitting "release memory from pool at function exit" statement. Unfortunately I am not familiar with the intricacies of the OMC, and unable to fix it myself...

What are your opinions @casella @mahge ?

**Comment by sturmk** [comment]
@casella indeed, only with FMUs with repeated calls to doStep(). Not with regular simulations.

**Comment by guntern** [comment]
What is the status on this issue (or memory leaks in general)? A very simple function seems to bring us in the same position. I am now at the point of rewriting our matrix multiplication without the usage of arrays to avoid this issue. This is OK for our 2x2 case, but for larger applications, this would be very tedious.

**Comment by casella** [comment]
Our developers are mostly on holiday now. We'll resume work on that around mid-August.

**Comment by Ziyan0825** [comment]
I observed a likely memory leak when using OpenModelica-exported co-simulation FMUs in long-running with PyFMI.

The problem becomes worse as the number of FMU instances increases: with 5 PV FMUs, the training terminates after about 57,600 steps, while with 3 PV FMUs, it terminates after about 97,300 steps. This may suggest that memory usage may accumulate across repeated calls and/or repeated episode resets, and that the issue scales with the number of FMU instances.

I also tried re-initializing the FMU instances every 300 steps, but this did not solve the problem.

After long-running training, FMU loading eventually fails with the following error:

FMIL: module = b'FMILIB', log level = 5: b'Allocating FMIL context'
FMIL: module = b'FMILIB', log level = 5: b'Detecting FMI standard version'
FMIL: module = b'FMIZIP', log level = 5: b'Unpacking FMU into C:\\Users\\Ziyan\\AppData\\Local\\Temp\\JModelica.org\\jm_tmp8b5v40rn'
FMIL: module = b'FMIXML', log level = 5: b'Parsing XML to detect FMI standard version'
FMIL: module = b'FMIXML', log level = 1: b"Cannot open file 'C:\\Users\\Ziyan\\AppData\\Local\\Temp\\JModelica.org\\jm_tmp8b5v40rn\\modelDescription.xml' for parsing"
FMIL: module = b'FMILIB', log level = 4: b'XML specifies FMI standard version unknown'
FMIL: module = b'JMPRT', log level = 5: b'Removing C:\\Users\\Ziyan\\AppData\\Local\\Temp\\JModelica.org\\jm_tmp8b5v40rn'

Traceback (most recent call last):
pyfmi.exceptions.InvalidVersionException: The FMU could not be loaded. The FMU version is unsupported.

I would appreciate any guidance on whether this could be related to a memory leak or another issue in the FMU export/runtime path.

**Comment by casella** [comment]
See #14509. There are a number of related issues #13991, #13905, #13488, #13336, #12225, #10790. We haven't figured out yet what is the root cause.

**Comment by casella** [comment]
@sturmk this should hopefuly be fixed by PR #15363.

Could you please check with the next nightly build and report? Thanks!

**Comment by jschueller** [comment]
it still leaks

Modelica functions with local arrays (like IF97 water property functions
dptofT, tsat) are generated as C functions that call alloc_real_array()
which allocates from the process-wide memory pool (pool_malloc).
The memory pool uses a bump allocator — allocations are never freed during
the simulation, only bulk-freed at fmi2FreeInstance via free_memory_pool().

When such functions are called inside a nonlinear solver iteration loop
(e.g. homotopy + numerical Jacobian), the pool grows without bound until
the simulation finishes or the OS kills the process.

Reproduced:
- Generated C code for a function with a protected Real[1000] shows
  alloc_real_array(&_arr, 1, 1000) at line 20 of AllocFunc2_functions.c.
- No free_real_array() is emitted; the allocation lives in the pool.
- RSS does NOT grow linearly for small arrays because the pool reuses
  space within each 4 MB block, but large arrays (MB-scale) called
  thousands of times will exhaust blocks and cause GB-scale growth.

The fix would need to either:
a) Use stack allocation for small/medium local arrays instead of pool,
b) Add save/restore of pool state around function-local allocations so
   the array is freed on function exit, or
c) Generate explicit free_real_array() calls in the epilogue of
   functions that allocate temporary arrays.

How should we fix this a, b or c ?

**Comment by casella** [comment]
@AnHeuermann another interesting case for you 😃

**Comment by AnHeuermann** [comment]
I'm not sure how to handle this in our current runtime. 

We should move to a language that does proper memory handling with arrays. C++ in my opinion.

**Comment by casella** [comment]
@adrpo, what do you think?

**Comment by jschueller** [comment]
option b) looks simple enough: https://github.com/OpenModelica/OpenModelica/pull/16081

**Comment by jschueller** [comment]
fixed by #16227

**Comment by casella** [comment]
I'm closing this now. @sturmk please reopen/report if there is something wrong yet.
