### ISSUE TITLE
Instantiation of function fails without error message

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10821]
### Description

A specific function class produces an error without a message when it is checked. It can however be used in other classes without problems.

### Steps to Reproduce

1. Consider the following modelica package:
```modelica
package ErrorWithoutMessage

  function FunctionWithError
    parameter input Real inputTable[:, 2];
    parameter input Boolean positiveSide;
    output Real outputTable[size(inputTable, 1), 1];
  protected
    parameter Integer sizeInputTable = size(inputTable, 1);
    Integer zeroIndex;
  algorithm
    zeroIndex := 0;
    for i in 1:sizeInputTable loop
      if Modelica.Math.isEqual(inputTable[i, 1], 0.0, Modelica.Constants.eps) then
        zeroIndex := i;
      end if;
    end for;
    outputTable := zeros(sizeInputTable, 1);
    if positiveSide then
      outputTable[(zeroIndex + 1):sizeInputTable, 1] := inputTable[(zeroIndex + 1):sizeInputTable, 2];
    else
      outputTable[1:(zeroIndex - 1), 1] := inputTable[1:(zeroIndex - 1), 2];
    end if;
  end FunctionWithError;

  model ModelUsingFunction
    parameter Real[:,2] inputTable = [-1.0,75.0; 0.0,0.0; 1.0,75.0];
    parameter Boolean positiveSide = true;
    Real[:,1] outputTable = ErrorWithoutMessage.FunctionWithError(inputTable, positiveSide);
  end ModelUsingFunction;
  
end ErrorWithoutMessage;
```
2. Try to check the function `ErrorWithoutMessage.FunctionWithError`. The following error message appears: "Internal error Instantiation of ErrorWithoutMessage.FunctionWithError failed with no error message."
3. The model `ErrorWithoutMessage.ModelUsingFunction`, which internally uses `ErrorWithoutMessage.FunctionWithError`, however, can be checked and simulated successfully. 

### Expected Behavior

The function checks successfully or at least throws a meaningful error message.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-164-g35b2943a7c (64-bit) with instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by perost** [comment]
#10826 fixes the issue by handling the function like a function rather than a normal class.

One minor issue is that the message you get when checking a function is still the same, but the part about the number of equations/variables (which will always be 0 for a function) should probably be omitted in that case. But changing that is more complicated than it should be unfortunately.

**Comment by abuntrock** [comment]
@perost Thanks a lot. I think that a not useful message about equations/variables is definitely better than having an error message.

**Comment by casella** [comment]
This was actually a quite old issue, see #5045. Good that it is now fixed 😄

**Comment by casella** [comment]
@perost I haven't actually tested this yet. Is if really fixed, or are only bogus error messages avoided?

**Comment by perost** [comment]
> @perost I haven't actually tested this yet. Is if really fixed, or are only bogus error messages avoided?

It will now instantiate/type/flatten the function properly, the same thing it would normally do with functions, so check model can now be used to check if a function is correct or not. The only issue is that the message from check model is still the same, which might be a bit confusing when checking a function. But having a different message for functions is a bit tricky because of how check model is currently implemented.

**Comment by abuntrock** [comment]
It looks perfect with today's nightly. Thanks a lot.
