### ISSUE TITLE
variable name of the exported .fmu not following FMI 2.0

### ISSUE THREAD

**Issue by MatteoSchiavon** [OpenModelica/OpenModelica#11265]
### Description

variable name not following the FMI standard 2.0 when exporting the model into .fmu from OpenModelica

### Steps to Reproduce

If I try to export into .fmu this model:

      parameter Real T = 0.1;
      parameter Real k = 1;
      Real u;
      Real a;
      Real x(start = 0);
      Modelica.Blocks.Interfaces.RealOutput y;
      Real Ts = interval(u);
      equation
      a = sin(time);
      when Clock(0.1) then
          u = sample(a);
          x = previous(x) + previous(Ts) / T * u;
      end when;
      y = k * hold(x);

I notice that in the "modelDescription.xml" there are:
...
<ScalarVariable
    name="previous(x)"
...
<ScalarVariable
    name="previous(Ts)"
...

Therefore, when importing the .fmu in another tool it can give an error if the variable name is checked.

### Expected Behavior

According to the variable naming convention in FMI standard 2 (see Section: Variable Naming Conventions (variableNamingConvention)), for structured naming, such variable names (previous(x) an previous(Ts)) do not follow the standard. 

Moreover, are those variables necessary?

### Version and OS

 - OpenModelica Version:  v1.21.0 (64-bit)
 - Windows 10, 64 bit

**Comment by casella** [comment]
@arun3688 can you please check?

**Comment by arun3688** [comment]
@MatteoSchiavon I did a quick testing and  verified the` modeldescription.xml ` with FMI-2.0 schema with the `xerces validator` and  the problem is not with the following variable 

```
  <ScalarVariable
    name="previous(Ts)"
    valueReference="0"
    variability="discrete"
    >
    <Real/>
  </ScalarVariable>
  <!-- Index of variable = "2" -->
  <ScalarVariable
    name="previous(x)"
    valueReference="1"
    variability="discrete"
    >
    <Real/>
  </ScalarVariable>
```
These two variables `follow the FMI-2.0 standard variable name conventions`,  But as you said these two variables are not necessary.   But however the `modeldescription.xml` still do not follow the FMI-2.0 standard in `<ModelStructure>` see below 

 ```
 <ModelStructure>
    <Outputs>
      <Unknown index="7" dependencies="" dependenciesKind="" />
    </Outputs>
    <DiscreteStates>
      <Unknown index="3" dependencies="" dependenciesKind="" />
      <Unknown index="6" dependencies="" dependenciesKind="" />
    </DiscreteStates>
  </ModelStructure>
```
`DiscrteStates` are not allowed in `modeldescription.xml`  and when i run with xerces validator which is used in `OMSimulator` reports me the following error 

```
invalid modeldescription.xml detected in C:/OPENMODELICAGIT/test/test/modeldescription.xml at line 175 column 21, no declaration found for element 'DiscreteStates'
modeldescription.xml: C:/OPENMODELICAGIT/test/test/modeldescription.xml doesn't conform to the schema: C:/FMI-Standard-2.0.2/schema/fmi2ModelDescription.xsd
```
we are doing this to support our `cpp runtime`, we have a flag `exportClocksInModeldescription=false` where all the variables related to clocks are not exported by default unless it is set to `true` , but somehow still previous pops up in scalar variable, I will try to debug more and fix it.

**Comment by arun3688** [comment]
@MatteoSchiavon the issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/d1144cfa8880aad8779e4e48fe62f122e95c38f7, Filtering the clock related variables is not the problem , but the other issues in `modeldescription.xml` is fixed  according to FMI-schema and standard.

**Comment by casella** [comment]
@MatteoSchiavon you can test this with the latest 1.23.0-dev nightly build.

**Comment by MatteoSchiavon** [comment]
Thank you @arun3688 and @casella! I will test it today and I'll let you know here.
Matteo

**Comment by MatteoSchiavon** [comment]
Hi, I am testing the 1.23 nightly build! To be honest I was a little lost, we might not be entirely on the same page about this issue. And I still see the issue about variable names when importing the fmu into other tools.
Could you please recap what the issue was and how the problem has been solved? 
Was the issue inside <ModelVariables> or <ModelStructure> part of the modelDescription.xml? 
Matteo

**Comment by arun3688** [comment]
@MatteoSchiavon The issue was not about these variables

```
  <ScalarVariable
    name="previous(Ts)"
    valueReference="0"
    variability="discrete"
    >
    <Real/>
  </ScalarVariable>
  <!-- Index of variable = "2" -->
  <ScalarVariable
    name="previous(x)"
    valueReference="1"
    variability="discrete"
    >
    <Real/>
  </ScalarVariable>
```

These variables can be present in the `modeldescription.xml` and they are according to the FMI-Standard-Schema see here https://github.com/modelica/fmi-standard/blob/1324a73a09bffa488ed40402e69bf2480fb39c0f/schema/fmi2ModelDescription.xsd,  We have done the schema validation and it does not report errors.  What was fixed in this issue was in `<ModelStructure>` we should not have `<DiscreteStates>` see below 

```
<ModelStructure>
   <Outputs>
     <Unknown index="7" dependencies="" dependenciesKind="" />
   </Outputs>
   <DiscreteStates>
     <Unknown index="3" dependencies="" dependenciesKind="" />
     <Unknown index="6" dependencies="" dependenciesKind="" />
   </DiscreteStates>
 </ModelStructure>
```
And we have fixed this by not exporting in `modeldescription.xml` . Can you tell us what error you are getting with the tool you are importing?

**Comment by MatteoSchiavon** [comment]
Hi,

thanks for the clarification! The error I still get is the following:
" Import failed: modelDescription.xml of the FMU contains errors.
Variable name 'previous(Ts)' is not allowed.  etc etc".

We are looking at the standard FMI 2.0.4 version page 67. 

We also tested the created .fmu with 1.23-latest in "https://fmu-check.herokuapp.com/" and we get the following message: "previous(Ts)" (line 183) is not a legal variable name for naming convention "structured....".

Matteo

**Comment by arun3688** [comment]
@MatteoSchiavon Hi i tested with `https://fmu-check.herokuapp.com/` and i confirm that i got the same error like you, But according to the schema validation from `xerces` this looks good. Obviously we can filter the `previous` vars but you can see the `modelstructure` dependencies 

```
  <ModelStructure>
    <Outputs>
      <Unknown index="7" dependencies="1 2" dependenciesKind="dependent dependent" />
    </Outputs>
    <InitialUnknowns>
      <Unknown index="7" dependencies="1" dependenciesKind="dependent" />
    </InitialUnknowns>
  </ModelStructure>
```
The output variable depends on the two variables,

@casella can you please comment on this should we filter the previous variables in `modeldescription.xml` ?

**Comment by MatteoSchiavon** [comment]
We are also checking a few things on our side. We'll be back on this :)
Many thanks,
Matteo

**Comment by MatteoSchiavon** [comment]
Hi,
Any update on this?
Matteo

**Comment by arun3688** [comment]
@casella can you comment on this, because according to our xerces validation those variables are validated and they are according to fmi naming specification, but the https://fmu-check.herokuapp.com/ does not allow this

**Comment by casella** [comment]
@arun3688 the original Modelica model contains clocked variables. As far as I understand clocked variables were only introduced in FMI 3.0.0, even though there are some provisions in FMI 2.0.4 to get "poor man's clocked variables".

Are we already supporting them? If not, that explains why we get both wrong names (apparently) but also a bad structure.

**Comment by casella** [comment]
Regarding variable names, I checked the FMI spec 2.0.4, Section 2.2.9. There are two conventions. In the "flat" convention, names can be any Unicode string. In the "structured" convention instead, there is a grammar that only allows operator-syntax `xxx()` for `der(xxx)`, hence `previous(x)` is not valid. This is, again, because there is no proper support of clocked variables in FMI 2.0.4.

**Comment by MatteoSchiavon** [comment]
Hi @casella, hi @arun3688
Thanks for the investigation. I will modify myself the clocked variable's names from the generated "modelDescription.xml" for now otherwise I won't be able to use the model in other tools; that's fine because I understand that with FMI 3.0 the instructions are more clear. Anyways, if you'll take any action on the "export FMU 2.0.4" it would be nice if you could let me know 
Best regards,
Matteo

**Comment by casella** [comment]
You can periodically check the [closed FMI issues](https://github.com/OpenModelica/OpenModelica/issues?q=label%3ACOMP%2FFMI+is%3Aclosed), any new feature will most likely show up there. Also the [release notes](https://github.com/OpenModelica/OpenModelica/releases).
