### ISSUE TITLE
Function call with type 'record'  fails at compilation time

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#11725]
The following model seems OK. 
```modelica
model Bug
  record MyRec
   parameter Real a;
  end MyRec;
  parameter MyRec rec0(
    a=1 );
  parameter MyRec rec1(
    a=0);

  function BuildK
    input MyRec kdata[2];
  algorithm
  end BuildK;

  parameter MyRec data[:]={rec0,rec1};
 equation
     BuildK(kdata=data);
end Bug;
```

However, while compiling, I get the following error:
```
In file included from OMCppBugCalcHelperMain.cpp:29:
./OMCppBugInitialize.cpp:136:26: error: use of undeclared identifier 'data_'
  _functions->Bug_BuildK(data_);
                         ^
In file included from OMCppBugCalcHelperMain.cpp:33:
./OMCppBug.cpp:147:26: error: use of undeclared identifier 'data_'
  _functions->Bug_BuildK(data_);
                         ^
2 errors generated.
mingw32-make: *** [<builtin>: OMCppBugCalcHelperMain.o] Error 1
```

I'm working with:
 - OpenModelica Version: v1.22.1 (64-bit),
- Windows 11, 64 bits

**Comment by casella** [comment]
@arouhan, I tried this with the latest nightly build and it works fine. I guess the issue has been fixed in the meantime. Please reopen if it doesn't work for you.

**Comment by mahge** [comment]
I think this is the CPP Codegen and runtime. @arouhan can you tell us how to duplicate this? Did you specify C++ as the target for code generation?

**Comment by arouhan** [comment]
@mahge , you are correct:  I did specifcy the following for the target code generation
![image](https://github.com/OpenModelica/OpenModelica/assets/20094263/54d5b9b2-5f44-4bcc-963a-ee69eb990565)
and then code compilation fails.
when I change to code generation with 'C', instead of 'Cpp' then compilation works OK.
@casella I tried also with lastest nightly build and issue remains.

**Comment by arouhan** [comment]
@casella  I would re-open the issue, however, I cann't find the «re-open» button. I can only «add a comment».
