### ISSUE TITLE
OpenModelica 1.22.1: SSP Standard not recognized, ME FMI models not recognized, SSP simulation broken

### ISSUE THREAD

**Issue by GorbadPS3** [OpenModelica/OpenModelica#11821]
### Description

In the previous release, 1.21, SSP Simulations were working fine. We've been able to create FMI models in openmodelica and define a larger SSP model using them, and simulate them. We've been able to export the model and import the model into OMEdit without issues and simulate it.

However, in 1.22.1 we first noticed issues with OMSimulator.exe running from the command-line. Simply running this:
"C:\Program Files\OpenModelica1.22.1-64bit\bin\OMSimulator.exe" --startTime=0.0 --stopTime=60.0 Demo.ssp
Gives the following errors:

```
warning: invalid "SystemStructureDescription" detected in file "Demo.ssp" at line: 0 column: 0, unable to open primary document entity 'C:/Program'
warning: invalid "SystemStructureDescription" detected in file "Demo.ssp" at line: 0 column: 0, unable to open file 'https://ssp-standard.org/SSP1/SystemStructureParameterValues'
warning: invalid "SystemStructureDescription" detected in file "Demo.ssp" at line: 10 column: 17, fatal error during schema scan
warning: "SystemStructureDescription" does not conform to the SSP standard schema
(a bit later)
error:   [fmi2logger] c:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo-7ylqqvg7/temp/0004_process_CarT2_FMU (logStatusError): fmi2GetDirectionalDerivative: Function not implemented.
```

When I inspect that .dll of the FMU model above, we see it includes fmi2GetDirectionalDerivative:

```
        383  17E 0001126A fmi2CancelStep
        384  17F 000101C9 fmi2CompletedIntegratorStep
        385  180 0000F50C fmi2DeSerializeFMUstate
        386  181 00010D9F fmi2DoStep
        387  182 0000FEC6 fmi2EnterContinuousTimeMode
        388  183 0000FDCB fmi2EnterEventMode
        389  184 0000C0EC fmi2EnterInitializationMode
        390  185 0000CE85 fmi2ExitInitializationMode
        391  186 0000F0A2 fmi2FreeFMUstate
        392  187 0000BC73 fmi2FreeInstance
        393  188 0000D6FB fmi2GetBoolean
        394  189 000113C6 fmi2GetBooleanStatus
        395  18A 00010936 fmi2GetContinuousStates
        396  18B 000106AC fmi2GetDerivatives
        397  18C 0000FA15 fmi2GetDirectionalDerivative
        398  18D 0001080D fmi2GetEventIndicators
        399  18E 0000EBCC fmi2GetFMUstate
        400  18F 0000D669 fmi2GetInteger
        401  190 0001136F fmi2GetIntegerStatus
        402  191 00010A4A fmi2GetNominalsOfContinuousStates
        403  192 0000D439 fmi2GetReal
        404  193 00010C46 fmi2GetRealOutputDerivatives
        405  194 00011318 fmi2GetRealStatus
        406  195 000112C1 fmi2GetStatus
        407  196 0000D968 fmi2GetString
        408  197 0001141D fmi2GetStringStatus
        409  198 0000A8B3 fmi2GetTypesPlatform
        410  199 0000A8C7 fmi2GetVersion
        411  19A 0000AB1D fmi2Instantiate
        412  19B 0000FE4F fmi2NewDiscreteStates
        413  19C 0000D262 fmi2Reset
        414  19D 0000F30B fmi2SerializeFMUstate
        415  19E 0000F18D fmi2SerializedFMUstateSize
        416  19F 0000DFB4 fmi2SetBoolean
        417  1A0 00010424 fmi2SetContinuousStates
        418  1A1 0000A8DB fmi2SetDebugLogging
        419  1A2 0000EEBD fmi2SetFMUstate
        420  1A3 0000DE64 fmi2SetInteger
        421  1A4 0000DC40 fmi2SetReal
        422  1A5 00010A9C fmi2SetRealInputDerivatives
        423  1A6 0000E25C fmi2SetString
        424  1A7 0001021B fmi2SetTime
        425  1A8 0000C004 fmi2SetupExperiment
        426  1A9 0000D1AC fmi2Terminate
```

When importing an SSP model into OMEdit, we see:

```
[3] 07:56:25 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 0 column: 0, unable to open primary document entity 'C:/Program'

[4] 07:56:25 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 0 column: 0, unable to open file 'https://ssp-standard.org/SSP1/SystemStructureParameterValues'

[5] 07:56:25 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 10 column: 17, fatal error during schema scan

[6] 07:56:25 Scripting Notification
"SystemStructureDescription" does not conform to the SSP standard schema
```

Note: The same "Demo.ssp" works fine in OpenModelica 1.21 and can be imported without issues.

Attempting to simulate the model causes the following error in OMEdit:

```
python C:/Program Files/OpenModelica1.22.1-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/<redacted>/AppData/Local/Temp/OpenModelica/OMEdit//Demo.ssp --endpoint-pub=tcp://127.0.0.1:53436 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "C:/Program Files/OpenModelica1.22.1-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 11, in <module>
    import OMSimulator as oms
  File "C:\Program Files\OpenModelica1.22.1-64bit\lib\omc\OMSimulator\__init__.py", line 17, in <module>
    Scope._init()
  File "C:\Program Files\OpenModelica1.22.1-64bit\lib\omc\OMSimulator\Scope.py", line 5, in _init
    _capi = capi()
  File "C:\Program Files\OpenModelica1.22.1-64bit\lib\omc\OMSimulator\capi.py", line 14, in __init__
    dllDir = os.add_dll_directory(os.path.dirname(omslib))
  File "C:\Program Files\OpenModelica1.22.1-64bit\tools\msys\mingw64\lib\python3.8\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\OpenModelica1.22.1-64bit\\lib\\omc\\OMSimulator\\../../bin'
Simulation process failed. Exited with code 0x00000001.
```

### Steps to reproduce

Simply create a new SSP model and a very simple Model Exchange FMI model (FMI 2.0) in openmodelica and attempt simulation.
Create the same model in 1.21 and notice everything works. Attempt to export from 1.21 and import into 1.22, notice the errors about invalid SSP Standard.

I've created an obfuscated version of the SSP model, with dummy FMU model implementations, to demonstrate the SSP Import and SSP Standard not recognized issue, see: 

[Demo_IP_Protected.zip](https://github.com/OpenModelica/OpenModelica/files/13972780/Demo_IP_Protected.zip)

NOTE: Do not attempt to simulate this SSP model, only import it into OMEdit to see the "SSP Standard not correct issue"! The FMU models within this obfuscated version are NOT WORKING and are dummy implementations of the FMI interface, i.e. they return fmi2OK and fmiOK for every fmi call without doing anything with the pointers provided to them!

### Expected behavior

SSP models should not complain that SSP format is not recognized when imported.
ME FMI models should be able to be simulated in SSP simulations.
SSP model simulation as a whole should as a result work like it did in 1.21 version.

### Version and OS
 - OpenModelica Version: OpenModelica v1.22.1 (64-bit)
 - OMSimulator version: v2.1.1.post247-g614c663-mingw-notlm-debug
 - OS: Windows 11, 64 bit

**Comment by arun3688** [comment]
@GorbadPS3 I am able to import the ssp in OMEdit without any issues. see the image below
![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/dd63e2db-a7fd-4ec6-aeae-b8335f69471c)

### Version 
```
OpenModelica Version : v1.23.0-dev-199-g49a342bd79-cmake
OMSimulator v2.1.1.post248-gf7c50c9-mingw-notlm-debug
```
We had some issues with OpenModelica Version 1.22.0, but we have fixed it, You should download the latest nightly builds and test it and it should work fine.

**Comment by GorbadPS3** [comment]
@arun3688 

I am still seeing this error, even with nightly version:

```
[3] 12:23:05 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 0 column: 0, unable to open primary document entity 'C:/Program'

[4] 12:23:06 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 0 column: 0, unable to open file 'https://ssp-standard.org/SSP1/SystemStructureParameterValues'

[5] 12:23:06 Scripting Notification
invalid "SystemStructureDescription" detected in file "C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp" at line: 10 column: 17, fatal error during schema scan

[6] 12:23:06 Scripting Notification
"SystemStructureDescription" does not conform to the SSP standard schema
```

It looks like it cannot handle spaces in the installation path?

Also, in the nightly version, simulation still fails:

```
python C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/MiroEklund/AppData/Local/Temp/OpenModelica/OMEdit//Demo.ssp --endpoint-pub=tcp://127.0.0.1:55978 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 11, in <module>
    import OMSimulator as oms
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\__init__.py", line 17, in <module>
    Scope._init()
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\Scope.py", line 5, in _init
    _capi = capi()
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\capi.py", line 14, in __init__
    dllDir = os.add_dll_directory(os.path.dirname(omslib))
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\mingw64\lib\python3.8\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files\\OpenModelica1.23.0-dev-64bit\\lib\\omc\\OMSimulator\\../../bin'
Simulation process failed. Exited with code 0x00000001.
```

This is the version I installed: https://build.openmodelica.org/omc/builds/windows/nightly-builds/64bit/OpenModelica-v1.23.0-dev-226-g3237397174-64bit.exe 

It looks like this version has a slightly different OMSimulator than yours:

```
>> C:\Program Files\OpenModelica1.23.0-dev-64bit\bin\OMSimulator.exe --version
OMSimulator v2.1.1.post247-g614c663-mingw-notlm-debug

>> C:\Program Files\OpenModelica1.23.0-dev-64bit\bin\omc.exe --version
OpenModelica v1.23.0-dev-226-g3237397174 (64-bit)
```

**Comment by arun3688** [comment]
@GorbadPS3 based on your error message i can see that your path of ssp is from onedrive 

invalid "SystemStructureDescription" detected in file "`C:/Users/<redacted>/OneDrive - <redacted>/Documents/projects/SSP Specification/Demo.ssp`" at line: 0 column: 0, unable to open primary document entity 'C:/Program'

Could you please put the ssp outside the onedrive location and also make sure your path does not have spaces and test it and see

**Comment by GorbadPS3** [comment]
Also running OMSimulator.exe from the command-line directly will also fail, resulting in error-output such as:

```
error:   [getDerivatives] fmi2_getDerivatives failed for FMU "Demo.Root.process_Load2_FMU"
error:   [getReal] getReal returned NAN
```

It almost looks like the OMSimulator's internal FMI implementation is using incorrect function name when trying to load FMI models.

**Comment by arun3688** [comment]
@GorbadPS3 I know the issue, the problem is as you see i am having the OMSimulator version `OMSimulator v2.1.1.post248-gf7c50c9-mingw-notlm-debug` which has the fixes and we did not the update the OMSimulator with OpenModelica master due to some other solver issues, but for the time being we can fix it directly in your computer, if you open this file location in your computer `C:\local\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\capi.py `  and in `line no #12 ` you will see this block of code

```
    if os.name == 'nt': # Windows
      omslib = os.path.join(dirname, "../../bin", "libOMSimulator.dll")
      dllDir = os.add_dll_directory(os.path.dirname(omslib))
```
The above code basically search for the libOMSimulator.dll and currently in the newer OpenModelica version the folder structure is slightly different so you have to look 3 directories behind for the dll, so the code should be 

```
    if os.name == 'nt': # Windows
      omslib = os.path.join(dirname, "../../../bin", "libOMSimulator.dll")
      dllDir = os.add_dll_directory(os.path.dirname(omslib))
```

change the line number 13 to this code `omslib = os.path.join(dirname, "../../../bin", "libOMSimulator.dll")
`

**Comment by GorbadPS3** [comment]
@arun3688  Right, makes sense. Making this modification did "fix" the issue in the sense that now OMEdit program can find OMSimulator's dll, however, simulating the FMI models is still causing the same error as below:

```
error:   [getDerivatives] fmi2_getDerivatives failed for FMU "Demo.Root.process_Load2_FMU"
error:   [getReal] getReal returned NAN
```

Meaning, there's still something wrong in the OMSimulator.exe itself.

I tried simulating the failing .fmu models directly using OMSimulator. This works:

OMSimulator.exe <path to FMU>

However, when used inside an SSP file, it doesn't work, showing the "fmi2_getDerivatives failed for FMU" error, i.e:

OMSimulator.exe <path to SSP>

**Comment by arun3688** [comment]
@GorbadPS3 looking into the ssp i see that it is a strongly connected components and it is trying to get the fmi2_getDirectives for the system, Can you regenerate the fmu with the following flag if you are running from mos script you can use the following command

```
setCommandLineOptions("-d=-disableDirectionalDerivatives"); 
getErrorString()
```
if you are using OMEdit to export the fmus,  please add this flag in the simulation setup

simulationsetup -> transalationFlags

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/373b4f73-224a-4aae-974f-1ee55ff304b7)

and test it and see

**Comment by GorbadPS3** [comment]
The way I see it, fmi2_getDirectives is not an FMI function. If OMSimulator is trying to find a function called fmi2_getDirectives , it will never find it in any FMU model, because the function name is "fmi2GetDirectives". This means the currently version of OMSimulator's SSP simulation, utilizing FMI models that have Model Exchange 2.0 as their interface, will not work.

It'll take a while for my colleague and me to generate a new FMU function and test things. I'll get back to you when we do.

**Comment by arun3688** [comment]
@GorbadPS3 Or if you can provide me the list of models, i can generate the fmu and see it it works. if the models are not confidential

**Comment by GorbadPS3** [comment]
We noticed that with both flags, or neither flags, the FMUs were working correctly. With only fmuExperimental, they did not work in 1.23/1.22.

**Comment by arun3688** [comment]
@GorbadPS3 `providesDirectionalDerivative` is an experimental feature which provides the first order derivatives for the cosimulation fmus, But this should not cause problem in simulation of the fmus, I see that you have resolved the issue in the newer version of OpenModelica and moreover the latest nightly builds contains the latest OMSimulator commits, If you see that the fmus are working fine we can close this issue, otherwise can you provide a minimal example to reproduce the issue

**Comment by GorbadPS3** [comment]
@arun3688  Yes this ticket can be closed, I no longer run into this issue.
