### ISSUE TITLE
Translation error using data reconciliation feature with an assertion 

### ISSUE THREAD

**Issue by bmazurie** [OpenModelica/OpenModelica#12277]
### Description
When using data reconciliation feature with a model having an assertion which use an array: OpenModelica runs into a translation error.

### Steps to reproduce
Please take the following model (sorry I don't know the mos command for data reconciliation):
[DR_withAssert.zip](https://github.com/OpenModelica/OpenModelica/files/15027417/DR_withAssert.zip)

```modelica
model model_assert_DR
Real a(uncertain = Uncertainty.refine);
Real b(uncertain = Uncertainty.refine);
parameter Real c=5 annotation(__OpenModelica_BoundaryCondition = true);

Real table_real[2]={1.0,2.0};
equation
a=b;
a=c;
assert(table_real[1]==1.0,"Assert");

end model_assert_DR;
```
Try to run data reconciliation with a corresponding data file such as : [CSV_model_assert_DR.csv](https://github.com/OpenModelica/OpenModelica/files/15027425/CSV_model_assert_DR.csv)

It should run into a translation error such as : 
![Capture d’écran de 2024-04-18 17-32-54](https://github.com/OpenModelica/OpenModelica/assets/138198674/d90af20e-3997-4ef1-85a5-6fe92e355adb)

The problem happens with the data reconciliation feature, not if you try to simulate.

Comment the assertion and try again the data reconciliation feature. It should run perfectly. [model_assert_DR_html.zip](https://github.com/OpenModelica/OpenModelica/files/15027473/model_assert_DR_html.zip)

It seems that the translation error is due to the manipulation of an array (I tried with reals and integers).

### Expected behavior
There should be no translation error even with the assertion.
@audrey-jardin @adrpo @arun3688 @lenaRB 

### Version and OS
I tried with:
- OM 1.22.3 and OM1.19.2 with Linux Scibian11
- OM1.22.3 with Windows10 64 bits

Modelica4.0 was loaded.

**Comment by audrey-jardin** [comment]
@@adrpo , @arun3688 , @bmazurie : should be retested and solved in the framework of the ongoing DFD contract about "data reconciliation"

**Comment by audrey-jardin** [comment]
@bmazurie : could you retest that and tell us whether we can close the ticket or not?

**Comment by adrpo** [comment]
@adrpo and @bmazurie will test.

**Comment by bmazurie** [comment]
I've try with the nightly. 

The OG model: 
```modelica
model model_assertTable_DR
Real a(uncertain = Uncertainty.refine);
Real b(uncertain = Uncertainty.refine);
parameter Real c=5 annotation(__OpenModelica_BoundaryCondition = true);

Real table_real[2]={1.0,2.0};
equation
a=b;
a=c;
assert(table_real[1]==1.0,"Assert");
end model_assertTable_DR;
```

still not work during data reconciliation with the same error as before. 

In order to make it works, the table `table_real` should be a parameter:
```modelica
model model_assertTable_DR
Real a(uncertain = Uncertainty.refine);
Real b(uncertain = Uncertainty.refine);
parameter Real c=5 annotation(__OpenModelica_BoundaryCondition = true);

parameter Real table_real[2]={1.0,2.0};
equation
a=b;
a=c;
assert(table_real[1]==1.0,"Assert");
end model_assertTable_DR;
```

**In this case, data reconciliation algorithm works. This does not really make sense to me.** 

Note: My example is with a table made from Reals, but please note that in fact the same issue exists if this is a simple Real and not a table.

**Comment by arun3688** [comment]
@bmazurie the issue should be fixed with this commit e82ad534c1d4633346fe5f58f01a39e9a0386d39, please test it from nightly builds tomorrow (13-08-2026)

**Comment by adrpo** [comment]
@bmazurie will test this and report.

**Comment by bmazurie** [comment]
It works, thanks @arun3688
