### ISSUE TITLE
Question: Rules behind resimulation with changed initial values

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12272]
### Description

We are very happy that OMEdit generally allows the change of initial values for variables without a recompilation. However, this is not possible for all start values with `fixed=true`. Since for start values, the evaluate annotation has no effect, we are curios to know if there are any general principles that define, which start values can be edited in the variable browser and which cannot.

### Steps to Reproduce

1. Simulate `Modelica.Blocks.Examples.PID_Controller` and look at the variable browser.
2. `inertia1.phi.start` can be edited there but `inertia1.a.start` cannot. In Dymola for example both start values can be edited via the variable browser.

### Expected Behavior

It is possible to edit the start value of `inertia1.a` from `Modelica.Blocks.Examples.PID_Controller` in the variable browser and start a resimulation with the changed value.

### Version and OS

 - OpenModelica Version: v1.24.0-dev-9-g3bdce2a898 (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

### Additional Context

Thanks for looking at this.
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@perost @adeas31  @phannebohm would you like to comment on that?

**Comment by phannebohm** [comment]
I think this MWE reproduces the issue.
```modelica
model M
  Real y(start = 1, fixed = true);
  parameter Real p(fixed = false);
equation
  y = 2*p;
end M;
```
The variable in question is not a state, maybe that's the reason?

**Comment by abuntrock** [comment]
It seems that is kind of what happens. When simulating `Modelica.Blocks.Examples.PID_Controller` the following states are selected during simulation in my case:
1. PI.I.y
2. intertia1.phi
3. inertia2.w
4. integrator.y
5. spring.phi_rel
6. spring.w_rel

All of these can be edited in the variable browser except for `PI.I.y`. For `integrator.y` to start at a different value when resimulating `integrator.y_start` must be changed in the variable browser. 

However, `inertia2.w` can be edited in the variable browser (presumably because it is a state) but changing its initial value via the variable browser has no effect since its start value is not fixed I assume. Maybe not allowing to edit start values of variables, which do not have an effect, would be an easier fix to start with.

**Comment by casella** [comment]
> Maybe not allowing to edit start values of variables, which do not have an effect, would be an easier fix to start with.

Sounds like a good proposal to me. Not sure how easy that is.

**Comment by adeas31** [comment]
From the GUI point of view, OMEdit relies on `isValueChangeable` attribute in the `model_init.xml` file. I am not sure on what rules that attribute is set to true.

**Comment by casella** [comment]
I guess the backend decides that, based on whether the parameter is constant-evaluated, and therefore hard-wired in the code, or kept as generic. @phannebohm, @kabdelhak can you please comment on that?

**Comment by casella** [comment]
@phannebohm has a fixed in the works, after which only `inertia.1.phi` will be changeable at runtime. He'll push it ASAP. I'd keep it for 1.24.0, because I guess such a change must be tested for a while before releasing it.

This seems right to me in the case at hand, because the PI controller has a SteadyState initialization, which means that the initial velocity error must be zero, so `inertia1.w` is indirectly fixed by the reference speed generator signal and cannot be assigned at will; furthermore, the spring model has `w_rel(start = 0, fixed = true)`, which means that the speed of the second inertia is fixed as well, and so is the relative angle between the two inertias, which must correspond to the value needed to transfer the 10 N of the load while getting the fixed initial acceleration `inertia1.a = 0`.

Hence, only the initial angle of the first inertia can be set at will, all the other initial states of the rotating system are constrained by the structure of the initialization problem.

**Comment by abuntrock** [comment]
Sounds good. From our perspective it is also not urgent and so we agree that it is probably better to include this feature in 1.24.0.

However, from your good explanation of the rotary system I still cannot understand why it shouldn't be possible to change `inertia.a` and resimulate the model. I mean, I can change its initial value in the parameter dialog and run a successful simulation with a new compilation (when duplicating the example out of the MSL). So the structure of the rotating system does not require `inertia.a.start=0`. So for the future, I would still argue that all start values of variables with `fixed=true` should be editable in the variable browser.

**Comment by abuntrock** [comment]
That sounds great. Thanks a lot :)

**Comment by phannebohm** [comment]
I opened #12294. Unfortunately there are still some bad cases:

`speedSensor.flange.tau` has no start value and indeed has the explicit equation `speedSensor.flange.tau = 0.0` so it shouldn't be fixed, but it is somehow. So its start value can be set in OMEdit but it has no effect on the results.

Also some parameters are marked as changeable, e.g., `PI.Dzero.y` which has the equation `PI.Dzero.y = PI.Dzero.k` so I guess it shouldn't be changeable, or should it? It has no`final` prefix. Anyway changing its start value currently also has no effect on the simulation results.

**Comment by phannebohm** [comment]
What is the expected behavior for the following model?
```modelica
model M
  parameter Real a = 1.0;
  final parameter Real b = 2.0;
  parameter Real c = a^2 + b;
end M;
```
It's pretty clear that `a` should be changeable. Because of the `final` prefix, `b` should not be. Should `c` be changeable?

The current omc makes `c` not changeable. #12294 would make it changeable.

**Comment by casella** [comment]
> `speedSensor.flange.tau` has no start value and indeed has the explicit equation `speedSensor.flange.tau = 0.0` so it shouldn't be fixed, but it is somehow. 

?? What do you mean by "somehow fixed"? That would lead to a singular initialization problem, since there would be two linearly dependent equations in it.

> Also some parameters are marked as changeable, e.g., `PI.Dzero.y` which has the equation `PI.Dzero.y = PI.Dzero.k` so I guess it shouldn't be changeable, or should it? It has no`final` prefix. Anyway changing its start value currently also has no effect on the simulation results.

With the current nightlly, `PI.Dzero.k` can be changed. This has no effect if you initialize the controller in steady-state, because any value you put there will be compensated by the value of the integral controller output to get the system at equilibrium. However, asking the backend to understand that is probably a bit too much, this borders on AI 😄

**Comment by casella** [comment]
> It's pretty clear that `a` should be changeable. Because of the `final` prefix, `b` should not be. Should `c` be changeable?
> 
> The current omc makes `c` not changeable. #12294 would make it changeable.

I think this is OK. It conforms to the spirit of the MLS, though it actually says nothing about "changeable parameter", which is very much dependent on the specific compiler technology. In many cases, modellers just forger to set the `final` keyword to mean that the binding expression is definitive and should never be changed, but if they don't, that's their problem.

**Comment by phannebohm** [comment]
The problem is that changing the value has no influence on the simulation in some cases. I don't really understand what is happening. But I suspect having a non-constant binding makes the variable ignore the changed start value.

**Comment by casella** [comment]
> The problem is that changing the value has no influence on the simulation in some cases.

This is very much possible in Modelica. Consider this MWE
```
model TestStart
  Real x(start = 2);
equation
  der(x) = 1;
initial equation
  x = 3;
end TestStart;
```
I can always change the start attribute of `x`, but this has no influence on the initial value of `x`, which is determined by the initial equation.

Is that a problem?

Figuring out _in general_ which start attributes do indeed have an influence on the simulation seems to me something on the border of indecidability.

**Comment by phannebohm** [comment]
In `TestState` the variable `x` is not fixed, so it will be considered not changeable. No problem.

Currently a variable is changeable only if all of these conditions are true:
- it is fixed
- it has no annotation(Evaluate=true)
- it is not final
- it is not protected
- it has a constant binding or no binding

The only exception is if it is an input, in which case it is always changeable. (That's how it was handled before.)

**Comment by phannebohm** [comment]
The problem is some variables have their fixed attribute set to true for some reason unknown to me, and yet they are not fixed in the sense that their start value is not used.

**Comment by casella** [comment]
> Currently a variable is changeable only if all of these conditions are true:
> 
>     * it is fixed (because otherwise the start value would be of no use)
> 
>     * it has no `annotation(Evaluate=true)` (because we couldn't change that anymore after compilation I guess)
> 
>     * it is not final (by the definition of final)
> 
>     * it is not protected (because protected variables would not be visible anyway I think)

Sounds reasonable.

>     * it has a constant binding or no binding (not sure why, perhaps because we're not yet able to overwrite the non-constant case)

I'm not sure I get why having a constant binding should mean it's changeable. Could you make a concrete example of that?
 
> The only exception is if it is an input, in which case it is always changeable. (That's how it was handled before.)

I guess you mean top-level input here, right? In that case, if there is no CSV, we use the start value for the input, so it makes sense that one can change it through the GUI. BTW is there any hint to this possibility in the MLS? I could not find it.

**Comment by phannebohm** [comment]
> Figuring out _in general_ which start attributes do indeed have an influence on the simulation seems to me something on the border of indecidability.

I hope not. For the initial system we use some of the start values (i.e. the ones we fix) and we don't use the others. At that point we know exactly which ones influence the system. Am I missing something?

**Comment by phannebohm** [comment]
> > ```
> > * it has a constant binding or no binding (not sure why, perhaps because we're not yet able to overwrite the non-constant case)
> > ```
> 
> I'm not sure I get why having a constant binding should mean it's changeable. Could you make a concrete example of that?

That's just the normal case
```modelica
  parameter Real p = 1.0;
```
The binding is constant.

> > The only exception is if it is an input, in which case it is always changeable. (That's how it was handled before.)
> 
> I guess you mean top-level input here, right? In that case, if there is no CSV, we use the start value for the input, so it makes sense that one can change it through the GUI.

Not sure, I think only top-level inputs survive until the backend.

> BTW is there any hint to this possibility in the MLS? I could not find it.

I searched but didn't find anything. I was counting on you @casella :sweat_smile:

**Comment by phannebohm** [comment]
> > The problem is some variables have their fixed attribute set to true for some reason unknown to me, and yet they are not fixed in the sense that their start value is not used.
> 
> Huh? This looks weird to me. [MLS Sect 4.8.6](https://specification.modelica.org/maint/3.6/class-predefined-types-and-declarations.html#attributes-start-fixed-nominal-and-unbounded) says:
> 
> > `fixed = true` means a required value
> 
> i.e. an initial equation `x = x.start;`, I understand. How can it possibly not be used?

That's what bugs me.

> Do you have any concrete example?

In `Modelica.Blocks.Examples.PID_Controller` look at `speedSensor.flange.tau`. Its start value can be changed after compilation but it has no effect when resimulating. In the initial system it's assigned to zero explicitly. But the fact that OMEdit allows the change means (at leas in SimCode) the variable is considered fixed.

**Comment by casella** [comment]
> > Figuring out _in general_ which start attributes do indeed have an influence on the simulation seems to me something on the border of indecidability.
> 
> I hope not. For the initial system we use some of the start values (i.e. the ones we fix) and we don't use the others. At that point we know exactly which ones influence the system. Am I missing something?

OK, I was thinking of the effects of start attributes for `fixed = false` variables, but those are not available in the GUI. Yes, if we are talking about variables with `fixed = true`, we could mark them as changeable.

**Comment by casella** [comment]
> > I'm not sure I get why having a constant binding should mean it's changeable. Could you make a concrete example of that?
> 
> That's just the normal case
> 
> ```modelica
>   parameter Real p = 1.0;
> ```

Sorry, now I'm totally confused (and this ticket is becoming too long...). You wrote

> a **variable** is changeable only if all of these conditions are true:

I thought you really meant _variable_ here, but now I guess you meant `variable or parameter`. Is that the case?

**Comment by casella** [comment]
> > Do you have any concrete example?
> 
> In `Modelica.Blocks.Examples.PID_Controller` look at `speedSensor.flange.tau`. Its start value can be changed after compilation but it has no effect when resimulating. In the initial system it's assigned to zero explicitly. But the fact that OMEdit allows the change means (at leas in SimCode) the variable is considered fixed.

Wait, `speedSensor.flange.tau` is a _variable_ (not a parameter), which is set to zero by an [_equation_](https://github.com/modelica/ModelicaStandardLibrary/blob/a877f527e29c47e344d2c05e393b65c6c4eee01b/Modelica/Mechanics/Rotational/Interfaces/PartialAbsoluteSensor.mo#L11), not by an _initial equation_. So, it's not fixed, in the sense of having `fixed = true`, which would correspond to an _initial equation_.

The backend is smart enough to figure out that it is only necessary to compute `speedSensor.flange.tau := 0` only once during initialization, rather than recomputing it every time step; that is good, but is just a code optimization, it doesn't make that variable a parameter, nor it gives it a `fixed = true` attribute. So, there is no reason why it should be marked as changeable, according to [your rules](https://github.com/OpenModelica/OpenModelica/issues/12272#issuecomment-2072625821).

Does this help solving your problem?

**Comment by casella** [comment]
> > I thought you really meant _variable_ here, but now I guess you meant `variable or parameter`. Is that the case?
> 
> Whoops. Yes I meant both. But checking now, I realize that it makes no sense for non-parameters to have a binding and be fixed at the same time. In case of a variable, the _constant_-ness should apply to the start attribute, not the binding expression.

The first four conditions are OK sense for both variables and parameters. Technically speaking, for variables what you change is the start attribute, for parameters it will be the constant bound value, but at the end of the day the effect is the same, i.e. changing the initial value which is then constant for the entire simulation in case of parameters.

Regarding the fifth condition:
- for variables, it is essential to have `fixed = true`; whether or not there is a binding equation doesn't matter; a binding equation for a variable is just another equation - since in general we can't change equations at runtime (not even binding equations) I would just ignore it
- for parameters, instead, it is necessary to have both `fixed = true` and a binding. If you have `fixed = true` and no binding, it's an error. If you have `fixed = false` and no binding, it means that the parameter value is determined when solving the initial equations, so it can't be set by the GUI. If you have `fixed = false` and a binding, it's most likely an error, and a warning is issued in that case when compiling.

Strictly speaking, the binding need not be constant (as long as it is not final). But in practice it often happens that people forget about setting final modifiers when you have non-constant binding expressions (e.g. `parameter SI.Area A = pi*r^2;`), so I agree not to make these modifiable at runtime.

**Comment by casella** [comment]
Summing up, this is my recommendation:

A parameter or variable should be modifiable at runtime if it is top-level input variable or an input variable of a top-level public connector, or if the following five conditions are verified:
- it has `fixed = true`, either set in the Modelica code or added by the backend to make the initialization problem fully specified, otherwise the start attribute is just a guess value
- it has no `annotation(Evaluate=true)`, otherwise it will be hard-wired ad hence not modifiable at runtime
- it is not `final` (by the definition of final)
- it is not `protected` (because protected variables should not be visible)
- it has a constant binding, in case it is a parameter

**Comment by abuntrock** [comment]
Looks like a pocked into a bit of a wasp nest here, but the last comment from @casella exactly describes what I expected as well. Thanks for the good explanations. I learned some things about how to describe modelica problems nicely as well.

**Comment by casella** [comment]
Wasp nests are meant to be eventually tamed 😄

**Comment by phannebohm** [comment]
I improved the code some more in #12311. In addition to @casella's [recommendations](https://github.com/OpenModelica/OpenModelica/issues/12272#issuecomment-2072883957), I also check if it's not a parameter then it must have a constant start attribute. This is because if we make the variable
```modelica
  Real x(start = p, fixed = true); // not changeable, because the runtime cannot handle it
```
changeable, the changed value will be ignored and `x` will be initialized with `p` anyways. Maybe in the future we can have `x` changeable, but currently it doesn't work so I disabled it.

Also there was the case
```modelica
  parameter Real p(start = 1.0); // changeable now
```
where there is no binding but a start attribute. If that is constant then `p` will also be changeable now.

**Comment by abuntrock** [comment]
So in your second example I will be able to change the guess value for the initialization problem since the start value is not fixed?

**Comment by phannebohm** [comment]
> So in your second example I will be able to change the guess value for the initialization problem since the start value is not fixed?

Changing the initial guess would be useful I guess. Not sure if we can do that easily.

But anyway, that is not what I meant. By default parameters are fixed, so these two should be pretty much equivalent
```modelica
  parameter Real p = 1.0;
  parameter Real q(start = 1.0);
```

I'm reopening this issue, since we're still discussing. :sweat_smile:

**Comment by abuntrock** [comment]
Makes sense. The parameter 
```modelica 
parameter Real p(start = 1.0);
``` 
gets  `fixed=true` from the backend (1st point from @casella list)  and since all the other points are also fulfilled it should be changeable.

**Comment by abuntrock** [comment]
I was also to test the changes with v1.24.0-dev-38-g2d2e5b67f8 and they look really good from my perspective.

**Comment by phannebohm** [comment]
So should we also allow changing start values for non-fixed variables like `y` in this model?
```modelica
model NotFixed
  Real y(start = -1.0); // not fixed, but start attribute is used as initial guess
equation
  y^2 = 1.0;
end NotFixed;
```
I couldn't find a quick way to identify those variables in SimCode yet.

**Comment by abuntrock** [comment]
It would be a nice feature but its not so important for us at least compared to changing the start attributes of fixed variables.

But when this is is added, I would propose that there should be a GUI distinction in the Variable Browser between changing the guess value and changing the actual initial value.

**Comment by casella** [comment]
> Makes sense. The parameter
> 
> ```modelica
> parameter Real p(start = 1.0);
> ```
> 
> gets `fixed=true` from the backend (1st point from @casella list) 

Not exactly, parameters always have `fixed=true` by default. This is the (in)famous case of parameters not having a default binding but an explicitly set start attribute, see [MLS 8.6](https://specification.modelica.org/maint/3.6/equations.html#initialization-initial-equation-and-initial-algorithm):

> If a parameter has a value for the start-attribute, does not have `fixed = false`, and neither has a binding equation nor is part of a record having a binding equation, the value for the start-attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.

Anyway, the end result is the same.
