### ISSUE TITLE
Fuell cell models fail at the boundary between frontend and new backend (and later)

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12977]
Please check the test results of the SOFCPoliMi library. With the [old backend](https://libraries.openmodelica.org/branches/master/SOFCPoliMi/SOFCPoliMi.html), all tests run fine. With the [new backend](https://libraries.openmodelica.org/branches/newInst-newBackend/SOFCPoliMi/SOFCPoliMi.html) they all [fail in the same way](https://libraries.openmodelica.org/branches/newInst-newBackend/SOFCPoliMi/files/SOFCPoliMi_SOFCPoliMi.Tests.BenchmarkCammarata.err):
```
Notification: Performance of FrontEnd: time 0.0007618/0.6757, allocations: 126.2 kB / 0.7581 GB, free: 14.5 MB / 0.4981 GB
Error: Internal error NBackendDAE.lowerIfEquationBody failed for:
```
@perost, @phannebohm can you please check why? Thanks!

**Comment by casella** [comment]
@perost reports that the failure is due an if-equation without any branch, so something has been lost previously. Maybe split-up if equations is faulty.

**Comment by kabdelhak** [comment]
Initial problem is solved in #12985, but follow up issues occurred. Will we make new issues or just track it here?

**Comment by kabdelhak** [comment]
The culprit was
```
  for $i1 in 1:10 loop
    if {true, true, true, true, true, true, true, true, true, false} then
      der(stack.module[$i1].anodeChannel.pOut) = 0.0;
    end if;
  end for;
  ```
It's properly handled now.

**Comment by kabdelhak** [comment]
Oh, i just realized it is not properly handled. I have to do it differently, well will look at it again after the meeting here in hamburg.

**Comment by kabdelhak** [comment]
i think  i properly handle it now in #12986 . There is still one issue though, the condition of the if-equation is just a plain array, doesnt it to be indexed by the iterator?

@perost I think the fronted needs to put an indexed expression around the array with `$i`, right?

**Comment by casella** [comment]
Maybe this model is such that not all elements of an array are states, which I understand the NB still doesn't handle. @matteodepascali can you please comment on that?

**Comment by matteodepascali** [comment]
The tests for the fuel cell in this library are such that the outlet pressures of the channels are fixed boundary conditions, thus the pressures of the last discretization volumes are just parameters at the end.

**Comment by perost** [comment]
> i think i properly handle it now in #12986 . There is still one issue though, the condition of the if-equation is just a plain array, doesn't it need to be indexed by the iterator?
> 
> @perost I think the frontend needs to put an indexed expression around the array with `$i`, right?

Should be fixed with #12988. The issue was that the iterators can only be added to crefs so we know where to put them, but the condition was evaluated to an array before that.

I just disabled the early evaluation of if-conditions during flattening when scalarization is turned off. I'm not sure if we need to do anything more with them, they'll usually be evaluated later anyway, but we'll see if it breaks anything.

**Comment by perost** [comment]
It seems my change breaks the `testVectorizedBlocks` test case, the flat model looks correct but the old backend can't handle it anymore. We could make the change only for the new backend, but it's necessary regardless of backend so I'll have to investigate a bit more.

Also, the `BenchmarkCammarata` model I tested still fail in the backend with the same error about `NFOperator.repairMultary`, so that might be due to something else that you need to look into.

**Comment by kabdelhak** [comment]
> It seems my change breaks the `testVectorizedBlocks` test case, the flat model looks correct but the old backend can't handle it anymore. We could make the change only for the new backend, but it's necessary regardless of backend so I'll have to investigate a bit more.

Okay, yea that sounds right!
> 
> Also, the `BenchmarkCammarata` model I tested still fail in the backend with the same error about `NFOperator.repairMultary`, so that might be due to something else that you need to look into.

Yes i did not expect it to be fixed, i just saw that this indexing issue would become problematic later on.

**Comment by perost** [comment]
The issue with `testVectorizedBlocks` is that we end up with a for-loop as an initial equation, which the old backend can't handle. This is because there's a case in `Flatten.vectorizeEquation` which skips wrapping array equations in some specific cases, which doesn't trigger because an if-equation hasn't been simplified to a single equation like before.

So we kind of do want to simplify if-equations before vectorizing them, but we can't simplify them correctly before they've been vectorized. I'm not sure how to deal with that, but for now I just changed my fix to only apply to the new backend.

**Comment by casella** [comment]
> The tests for the fuel cell in this library are such that the outlet pressures of the channels are fixed boundary conditions, thus the pressures of the last discretization volumes are just parameters at the end.

@matteodepascali are we using C-R-C or R-C-R finite volume structure?

**Comment by casella** [comment]
The original problem is fixed, now the compilation fails later in the NB, I'll open a separate ticket for that.

**Comment by casella** [comment]
Next issue #13031 😃
