### ISSUE TITLE
Reinit() not executed depending on initial condition 

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#13247]
### Description
I'm simulating photon impacts on a non-linear heat capacitance. The energy should change instantaneously on impact, but also be able to change slowly due to other continuous power sources (dissipated heat in a resistor, flow to a colder place). The implementation is an integrator with reinit() on photon impact.

The included model (test.zip, attached) shows two simple example detector circuits which only differ in initial condition. When running the model, one of the circuits shows a temperature step (indicating reception of an energy impulse) while the other -- which has the same photon source and same heat capacitance -- has a constant temperature.

### Steps to reproduce
- Run the provided model TEST->Test->testTES2
- plot variables Heatcap1.T and Heatcap2.T
![image](https://github.com/user-attachments/assets/af723a2d-cdf6-40ac-9fd3-df47f1cc076e)
Heatcap2 has no step. Note that test variable 'x' does make a step in both cases, thus the 'when' clause around the reinit() call is executed.
- Head over to TEST->CryoLib->HeatCapWithImpulse and change `T^2 = 2*E/k;` to `T = sqrt(2*E/k);` (lines 21 -- 22)
![image](https://github.com/user-attachments/assets/ccb83030-38bf-4ce4-bf87-b8c88c46f4e3)
Now both heatcaps have a temperature step.

I'm guessing that the different initial conditions have an effect on the order of calculation, which make heatcap2 miss the reinit(), 
In that case, the code change fixes the calculation order.

### Expected behavior
The reinit() increasing the heat capacitance energy should be executed no matter the initial condition or order of calculation.

### Version and OS
 - OpenModelica Version at least 1.24.0.and 1.24.2
 - OS: Windows 10, 64 bit

[TEST.zip](https://github.com/user-attachments/files/17817157/TEST.zip)

**Comment by casella** [comment]
@paultjevdh thanks for reporting this!

The reason why your model doesn't work properly is that, depending on the choice of equations or initial equations, the backend tries to play smart to better solve the equations and selects
```
Number of states: 2 (Heatcap1.E,Heatcap2.T)
```
This is the reason why the reinit statement on Heatcap2 doesn't work: because the state variable is not E.

In fact, according to the MLS 3.7.5, this is choice of states is wrong:
>  x is a scalar or array Real variable that is implicitly defined to have StateSelect.always.
> _[It is an error if the variable cannot be selected as a state.]_ 

@phannebohm, @kabdelhak, we should fix the OB so that `reinit(x, <expr>)` automatically sets `x(stateSelect = StateSelect.always)`

**Comment by casella** [comment]
Of course please remember this when you implement reinit() in the NB.

**Comment by phannebohm** [comment]
#13282 fixes the model `TEST.Test.testTES2`. Unfortunately it still fails if more complicated state selection is needed, but at least there is a warning now that state selection couldn't select all variables with `StateSelect.always`.

**Comment by casella** [comment]
Thanks @phannebohm!

@paultjevdh please check when PR #13282 is merged in, on the following day you can try the new nightly build.

**Comment by paultjevdh** [comment]
Hi,
Today's nightly build fixed the problem. Thanks!

**Comment by casella** [comment]
Than, you for reporting 🥇
