### ISSUE TITLE
Exported FMU is missing sources of ModelicaStandardTables_* functions

### ISSUE THREAD

**Issue by t-sommer** [OpenModelica/OpenModelica#13260]
### Description

The sources of the `ModelicaStandardTables_*` functions are missing when a model that contains e.g. `Modelica.Blocks.Tables.CombiTable1Ds` is exported as an FMU.

### Steps to Reproduce

- export the following model as an FMU with OpenModelica v1.24.2 (64-bit) on Windows

```Modelica
model TableTest
  Modelica.Blocks.Tables.CombiTable1Ds table(extrapolation = Modelica.Blocks.Types.Extrapolation.HoldLastPoint,smoothness = Modelica.Blocks.Types.Smoothness.LinearSegments, table = [0, 0; 1, 10; 2, 0; 3, 10; 4, 0; 5, 10])  annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interfaces.RealInput real_setpoint annotation(
    Placement(visible = true, transformation(origin = {-120, 0}, extent = {{-20, -20}, {20, 20}}, rotation = 0), iconTransformation(origin = {-94, 6}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Blocks.Interfaces.RealOutput real_output annotation(
    Placement(visible = true, transformation(origin = {110, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {64, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(real_setpoint, table.u) annotation(
    Line(points = {{-120, 0}, {-12, 0}}, color = {0, 0, 127}));
  connect(table.y[1], real_output) annotation(
    Line(points = {{12, 0}, {110, 0}}, color = {0, 0, 127}));
end TableTest;
```

- run `fmpy compile TableTest.fmu` on the command line

```
$ fmpy compile TableTest.fmu
Compiling platform binary...

[...]

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.10.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[...]

   Creating library TableTest.lib and object TableTest.exp
TableTest_functions.obj : error LNK2019: unresolved external symbol ModelicaStandardTables_CombiTable1D_maximumAbscissa referenced in function omc_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmax
TableTest_functions.obj : error LNK2019: unresolved external symbol ModelicaStandardTables_CombiTable1D_minimumAbscissa referenced in function omc_Modelica_Blocks_Tables_Internal_getTable1DAbscissaUmin
TableTest_functions.obj : error LNK2019: unresolved external symbol ModelicaStandardTables_CombiTable1D_getValue referenced in function omc_Modelica_Blocks_Tables_Internal_getTable1DValueNoDer2
TableTest_functions.obj : error LNK2019: unresolved external symbol ModelicaStandardTables_CombiTable1D_init2 referenced in function omc_Modelica_Blocks_Types_ExternalCombiTable1D_constructor
TableTest_functions.obj : error LNK2019: unresolved external symbol ModelicaStandardTables_CombiTable1D_close referenced in function omc_Modelica_Blocks_Types_ExternalCombiTable1D_destructor
TableTest.dll : fatal error LNK1120: 5 unresolved externals

[...]

Exception: Failed to compile shared library
```

### Expected Behavior

The compilation finishes successfully.

### Version and OS

 - OpenModelica Version: v1.24.2
 - OS: Windows 11, 64 bit

**Comment by casella** [comment]
@arun3688 can you please check?

**Comment by arun3688** [comment]
@t-sommer @casella I debugged the issue today and identified the problem, The generated fmu statically links to the ModelicaStandardTables, but to cross compile with fmpy which uses the source files, we need to copy the ModelicaStandardTables.c and other dependent files to fmu sources, to compile successfully. I will try to fix the issue

**Comment by arun3688** [comment]
@t-sommer the issue is fixed with this commit fbfa0ae502fae59dcb45ae44fa97c033fcee128f, please test it from the nightly builds tomorow (24-4-2025), I hope my commit gets into the nightly builds

**Comment by casella** [comment]
@t-sommer we has some issues with the CI infrastructure, I hope this is resolved soon. You can check the nightly build hash code against the [commits](https://github.com/OpenModelica/OpenModelica/commits/master) to see if fbfa0ae is included.

**Comment by casella** [comment]
Very good results, looking at the [regression report](https://libraries.openmodelica.org/branches/history/master-fmi-fmpy/2025-04-23%2011:16:56..2025-05-01%2000:43:19.html).

@arun3688 please port to maintenance/v1.25, so we can close this ticket.

@t-sommer you can try the Windows nightly build now. Unfortunately, we still have issues building the Linux nightly, I hope they'll be resolved soon.

**Comment by arun3688** [comment]
@casella i have ported the commit to `maintenance/v1.25`

**Comment by casella** [comment]
@t-sommer please re-open if you still see issues.
