### ISSUE TITLE
Ensure that time-invariant conditions are constant-evaluated by the frontend in Chemical

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#14402]
Please check [Chemical.Processes.Tests.Diffusion](https://libraries.openmodelica.org/branches/master/Chemical/files/Chemical_Chemical.Processes.Tests.Diffusion.err). As discussed in MarekMatejak/Chemical#42, it currently fails because of issues with dynamic state selection. 

I tried to compile the same model by disabling dynamic state selection with [--indexReductionMethod=dummyDerivatives](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-indexreductionmethod). It then fails in the backend with this error:

```modelica
[5] 13:20:19 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo: 342:7-342:48]: Internal error BackendDAETransform.analyseStrongComponentBlock failed
variables:
  
equations:
0.0 = if s2.substance.FixedDefinition and Chemical.Interfaces.Properties.selfClustering(s2.substance.definitionParam)
or Chemical.Interfaces.Properties.selfClustering(Chemical.Interfaces.DefinitionInput(
  Chemical.Interfaces.DataRecord(s2.substanceDefinition.data.MM, s2.substanceDefinition.data.Hf, 
  s2.substanceDefinition.data.H0, {s2.substanceDefinition.data.alow[1], s2.substanceDefinition.data.alow[2],
  s2.substanceDefinition.data.alow[3], s2.substanceDefinition.data.alow[4], s2.substanceDefinition.data.alow[5], 
  s2.substanceDefinition.data.alow[6], s2.substanceDefinition.data.alow[7]}, {s2.substanceDefinition.data.blow[1], 
  s2.substanceDefinition.data.blow[2], s2.substanceDefinition.data.blow[3]}, {s2.substanceDefinition.data.ahigh[1], 
  s2.substanceDefinition.data.ahigh[2], s2.substanceDefinition.data.ahigh[3], s2.substanceDefinition.data.ahigh[4], 
  s2.substanceDefinition.data.ahigh[5], s2.substanceDefinition.data.ahigh[6], s2.substanceDefinition.data.ahigh[7]}, 
  {s2.substanceDefinition.data.bhigh[1], s2.substanceDefinition.data.bhigh[2], s2.substanceDefinition.data.bhigh[3]},
  s2.substanceDefinition.data.z, s2.substanceDefinition.data.phase, s2.substanceDefinition.data.VmBase, 
  s2.substanceDefinition.data.VmExcess), s2.substanceDefinition.SelfClustering, s2.substanceDefinition.SelfClustering_dH,
  s2.substanceDefinition.SelfClustering_dS))
 then s2.x - 0.5 * (2.0 * s2.substance.SelfClustering_K + s2.solutionParam.n / s2.n 
   - sqrt(4.0 * s2.substance.SelfClustering_K * s2.solutionParam.n / s2.n 
   + (s2.solutionParam.n / s2.n) ^ 2.0)) / s2.substance.SelfClustering_K ^ 2.0
 else s2.n - s2.substance.amountOfFreeMolecule
```
As far as I understand, the condition of the conditional expression is not time-varying and it definitely has important structural consequences, so I think the frontend should definitely constant-evaluate it by default, unless `--evaluateStructuralParameters=strictlyNecessary` is set.

@perost can you please check why this condition is not evaluated and ensure it is? Thanks!

**Comment by casella** [comment]
Keeping @MarekMatejak in the loop.

**Comment by perost** [comment]
I looked into this and the if-expression doesn't actually exist in the flat model, but is constructed by the backend from an if-equation. I'm not sure why the if-equation isn't evaluated in this case, I think it should be. Unfortunately @adrpo broke the MetaModelica debugger with his recent bootstrapping changes, I will take a closer look once its working again.

**Comment by perost** [comment]
The reason for why the if-equation isn't evaluated is simply because the condition isn't actually a parameter expression. The condition contains `selfClustering(s2.substance.definition)`, where `s2.substance.definition` is an input connector and not a parameter. So evaluating it isn't an option, I guess we need some other solution.

**Comment by MarekMatejak** [comment]
Yes, the definition comes trough input connector, but its source is always a parameter and remains constant during each simulation.

**Comment by casella** [comment]
@perost, @phannebohm should then the backend take care of constant-evaluating those conditions?

**Comment by perost** [comment]
> [@perost](https://github.com/perost), [@phannebohm](https://github.com/phannebohm) should then the backend take care of constant-evaluating those conditions?

I don't know what analysis the backend can do in this case, but evaluating the condition in the frontend is at least out of the question if it's not a parameter expression.

**Comment by casella** [comment]
> I don't know what analysis the backend can do in this case,

In principle, the backend should figure out during dependency analysis which variables/expressions are exclusively parameter- and constant-depending, so that they can be computed once and for all during initialization. Once we had that feature, we could apply it to conditions of if-equations to figure out if they are constant- and parameter-depending, and in that case mark the parameters they depend on as structural and evaluate them at compile time, so that only one branch of the if-equation survives for the subsequent code generation.

Unless, of course, `--evaluateStructuralParameters=strictlyNecessary` is set, in which case we should avoid marking those parameters as structural, so they can be changed at run time.

This issue is discussed in #8026. In June 2022 @phannebohm, in there you proposed to handle this with your "eval-graph analysis". Unfortunately the discussion stopped there and there was no progress ever since. Is this related to the RHS selective evaluation feature currently being finalized, see #11432? Can you comment on the current status?

Currently, if I compile this model
```modelica
model M
  Real x;
  Real y;
  parameter Real p = 2;
equation
  x = 2*p 
  y = x^2;
end M;
```
the OB figures out that `x` can be computed at initialization only (I guess because the parameter dependence is explicitly). Unfortunately, it doesn't take into account _indirect_ parameter dependence, so it re-computes `y` in the regular equations, even though it eventually only depends on parameters. Same for the NB. So I understand this feature still needs to be implemented fully in both cases.

> but evaluating the condition in the frontend is at least out of the question if it's not a parameter expression.

Sure. To each his own 😃

**Comment by phannebohm** [comment]
> Once we had that feature, we could apply it to conditions of if-equations to figure out if they are constant- and parameter-depending, and in that case mark the parameters they depend on as structural and evaluate them at compile time

I'm not sure if the backend can do the structural marking, AFAIK this needs to happen in the frontend, right?

> so that only one branch of the if-equation survives for the subsequent code generation.

This will probably not work. It looks like a chicken and egg problem to me. We need to causalize in order to know what is non-changing during simulation. But we would need to evaluate `if`-conditions and remove branches before we do the causalization, so that these strong components are removed correctly. Or do I miss something?

> This issue is discussed in [#8026](https://github.com/OpenModelica/OpenModelica/issues/8026). In June 2022 [@phannebohm](https://github.com/phannebohm), in there you proposed to handle this with your "eval-graph analysis". Unfortunately the discussion stopped there and there was no progress ever since. Is this related to the RHS selective evaluation feature currently being finalized, see [#11432](https://github.com/OpenModelica/OpenModelica/issues/11432)? Can you comment on the current status?

No progress. It's on my todo list, I just did not spend any time on it yet. This feature is loosely connected to #11432 but it happens in the backend rather than in the runtime.

**Comment by MarekMatejak** [comment]
In my opinion this problem is also fixed via #14447 and #14451

**Comment by casella** [comment]
@MarekMatejak #14451 indeed fixed #14447, if I look at the current [test report](https://libraries.openmodelica.org/branches/master/Chemical/Chemical.html) I see that [Chemical.Examples.Definitions](https://libraries.openmodelica.org/branches/master/Chemical/files/Chemical_Chemical.Examples.Definitions.err) run fine.

However, [Chemical.Processes.Tests.Diffusion](https://libraries.openmodelica.org/branches/master/Chemical/files/Chemical_Chemical.Processes.Tests.Diffusion.err) still fails because of dynamic state selection issues during backend handling. Have you tried with the latest nightly build with [indexReductionMethod=dummyDerivatives](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-indexreductionmethod)?

**Comment by casella** [comment]
> I'm not sure if the backend can do the structural marking, AFAIK this needs to happen in the frontend, right?

No idea. I mean, the frontend can figure out structural stuff and constant-evaluate it, but the backend could also do something more sophisticated and do further constant-evaluation, why not?
 
> This will probably not work. It looks like a chicken and egg problem to me. We need to causalize in order to know what is non-changing during simulation. But we would need to evaluate `if`-conditions and remove branches before we do the causalization, so that these strong components are removed correctly. Or do I miss something?

Yeah, in general you are right. But I guess one could try a partial causalization of the variables involved in those if-conditions only. It is quite likely that they will not depend on anything that needs to be evaluated by the if-equations themselves, but rather that they depend on parameters through some simple assignments. Seems doable to me.

Maybe that's not really necessary, see the previous comment.

> > This issue is discussed in [#8026](https://github.com/OpenModelica/OpenModelica/issues/8026). In June 2022 [@phannebohm](https://github.com/phannebohm), in there you proposed to handle this with your "eval-graph analysis". Unfortunately the discussion stopped there and there was no progress ever since. Is this related to the RHS selective evaluation feature currently being finalized, see [#11432](https://github.com/OpenModelica/OpenModelica/issues/11432)? Can you comment on the current status?
> 
> No progress. It's on my todo list, I just did not spend any time on it yet. This feature is loosely connected to [#11432](https://github.com/OpenModelica/OpenModelica/issues/11432) but it happens in the backend rather than in the runtime.

OK.

**Comment by casella** [comment]
I tried to reproduce the issue with an MWE:
```modelica
model TestInferredParameterCondition
  parameter Boolean b1;
  parameter Boolean b2;
  Boolean b3;
  Real x;
equation
  b3 = b1 and b2;
  if b3 then
    x + x^4 = time;
  else
    x = time;
  end if;
end TestInferredParameterCondition;
```
where the condition of the if-equation is given by a time-varying Boolean `b3`, which is then assigned to a parameter expression. If I run this model, I get this structure from the backend

<img width="848" height="230" alt="Image" src="https://github.com/user-attachments/assets/87ed8c6c-4264-4110-b66f-f91507c560fa" />

which is of course quite inefficient. With the given choice of parameters `b1` and `b2`, we should just get `x := time` all over the place, no implicit equations involved.

@phannebohm, as I wrote above

> I guess one could try a partial causalization of the variables involved in those if-conditions only. It is quite likely that they will not depend on anything that needs to be evaluated by the if-equations themselves, but rather that they depend on parameters through some simple assignments

here you would only have to figure out the dependency tree of `b3`, which is simply `b3 := b1 + b2`. The chicken-and-egg problem can be resolved by assuming that there are no loops, if there are loops, we just give an error. Same as the case where you cannot put when-equations into separate blocks of the BLT from other equations.

Anyway, I tried to see what happens if we do not rely on the backend to figure out the structural parameters but do so by marking `b1` and `b2` for constant evaluation:

```modelica
model TestInferredConstantCondition
  parameter Boolean b1 = false annotation(Evaluate = true);
  parameter Boolean b2 = false annotation(Evaluate = true);
  Boolean b3;
  Real x;
equation
  b3 = b1 and b2;
  if b3 then
    x + x^4 = time;
  else
    x = time;
  end if;
end TestInferredConstantCondition;
```
and, lo and behold, that's enough for the backend to do the right thing:

<img width="466" height="140" alt="Image" src="https://github.com/user-attachments/assets/ff2d0a7b-6f12-49d4-9ea9-5b51a868185a" />

@MarekMatejak I guess we could make one step forward by adding `annotation(Evaluate = true)` to those parameters that are eventually funneled through the input connector. To me it's pretty clear that those are structural parameters that should be constant-evaluated at compile time to generate efficient code, I guess you don't care if changing them requires re-compiling the code. So, we just need to give OpenModelica a hint to do so with the Evaluate annotation.

 Could you please indicate what are those parameters in the library models used by for the [Chemical.Processes.Tests.Diffusion](https://libraries.openmodelica.org/branches/master/Chemical/files/Chemical_Chemical.Processes.Tests.Diffusion.err) example, so I can try it and play around a bit more?

Thanks!

**Comment by casella** [comment]
Unfortunately it seems that @MarekMatejak's commit [b36d0f2](https://github.com/MarekMatejak/Chemical/commit/b36d0f2174c796e3613644bd2ef5c261ff85f8be) was not enough to get [Chemical.Processes.Tests.Diffusion](https://libraries.openmodelica.org/branches/master/Chemical/files/Chemical_Chemical.Processes.Tests.Diffusion.err) to work, it still fails because of dynamic state selection issues. 

I'm not sure because this is is due to some further issues with the OMC backend, or if it's because of some missing `Evaluate = true` annotation.

Adding @TomasKulhanek to the loop.
