### ISSUE TITLE
Hierarchical editing of models

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#2891]

**Comment by casella** [comment]
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/2891

**Comment by casella** [comment]
Discussion with @adrpo, @adeas31 and @perost. All the required information is already provided by the new instance-based interface, which returns the information for the entire instance all the way down to the leaves.

This is actually already used to support redeclares: when editing the parameters of a redeclare, among them one can find another replaceable class, and that works recursively.

So,  given the new inst-based infrastructure, most of the work is on the OMEdit GUI. Basically, the current editing is always referred to the top level anonymous node of the instance tree, the whole graphical rendering needs to be made parametric with respect of that reference node, that could be any component of the model, not just the top-level one. This could give access to the components in a graphical way (showing a diagram), where one can double-click on a component to change its parameter. Dymola calls this option "Show component", we could also name it "Edit component parameters" since it's not only showing.

A further way to allow hierarchical editing is to show the instance tree in a separate window, that can be explored. Double-clicking on a node shows the corresponding diagram, right-clicking on it should allow to select a menu item to change the parameters of that node.

**Comment by casella** [comment]
BTW, we should also allow to edit the top-level parameters of a model. Currently, if you open this model in OMEdit
```modelica
model Test
  parameter Real p = 1;
  Modelica.Blocks.Sources.Constant const(k = 3) (
    Placement(visible = true, transformation(origin = {-24, -14}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
end Test;
```
you can change the value of the `k` parameter in the component `const` using the GUI, by double-clicking on the Constant source icon. However, there is no way to inspect and change the parameters of the model itself, `p` in this case. Right-clicking on the model diagram or icon view (or on the node in the future instance tree view) should bring up a parameter dialog to edit the top-level parameters using the GUI.

**Comment by adeas31** [comment]
@casella this is up for testing now. In the diagram view, right click the element and choose `Show Element` or double click on the element while holding the ctrl key will take you inside the element. You will see new buttons, to navigate in the elements, next to icon, diagram and text buttons.

I haven't updated the users guide yet. Will do it asap.

**Comment by dietmarw-se** [comment]
Just tested this with the nightly. This looks already promising. What still seems to be missing is:
 - connection lines are not displayed when one goes to show component
 - modifications give an error. Example:
 ```
Unable to set the extends modifier value using command setExtendsModifierValue(CompleteTF_Real, OpenHPL.ElectroMech.Turbines.Turbine, turbine.torqueLimit, $Code((uMin = -100)))
```

**Comment by adeas31** [comment]
Thanks for the quick feedback.

> * connection lines are not displayed when one goes to show component

To be honest, I didn't test the connection lines and expected this to work :). Do you have an example model to test this?

> * modifications give an error. Example:
> 
> ```
> Unable to set the extends modifier value using command setExtendsModifierValue(CompleteTF_Real, OpenHPL.ElectroMech.Turbines.Turbine, turbine.torqueLimit, $Code((uMin = -100)))

I did test this one and strange that it fails. Perhaps some case that is not handled well. Can you please provide a test model this one as well.

**Comment by adeas31** [comment]
@casella and @dietmarw-se one thing I forgot to mention is that, when you go in show element the changes done are not reflected directly inside the editing mode e.g., conditional connectors, parameter values etc. This is intentional in order to avoid calling `getModelInstance`. The complete changes are applied once you go out of the editing mode.

**Comment by dietmarw-se** [comment]
You can test this with OpenHPL.Examples.Simple (which is available via the library manager) and there look into the turbine model. You probably need to make a duplicate first in order to test the modifications of something inside the turbine model.

**Comment by casella** [comment]
> @casella and @dietmarw-se one thing I forgot to mention is that, when you go in show element the changes done are not reflected directly inside the editing mode e.g., conditional connectors, parameter values etc. This is intentional in order to avoid calling `getModelInstance`. The complete changes are applied once you go out of the editing mode.

I'm not sure I understand this fully. If I change parameters in top-level models (as was only possible until now), as soon as I click "OK" the changes are reflected immediately in the diagram. For example, if I set useHeatPort in a Resistor instance, the port appears immediately after clicking OK on the parameter editing window. This is of course needed if I then want to connect that port to something else. I understand this requires `getModelInstance` and we have to live with it, see #11920.

Is there a compelling reason to do it differently when editing non-top level component parameters? It is true that I cannot add connection to a sub-component, but there are probably other parameter-driven aspects that one would like to see immediately.

**Comment by dietmarw** [comment]
I discovered another quirk with the "Show element" functionality. If you have graphical annotations (like text or boxes) on the main diagram layer then these annotations are still shown when you dive into sub components. You can see this by opening: `Modelica.Blocks.Examples.PID_Controller` and dive into the PID controller. You then get this image (at least in the Linux version of OMEdit):
![bilde](https://github.com/user-attachments/assets/c4a9a447-522b-465e-8e4e-eecf93f6b51c)

**Comment by adeas31** [comment]
@dietmarw PR #13087 fixes the connections and graphical annotations issues. I still haven't looked into the modification error but will do it soon.

@casella thanks for the feedback. I will debug more and see what is wrong or missing.

**Comment by dietmarw** [comment]
@adeas31 I was just going to test this in the latest nightly. However it looks like the nightly channel got the 1.24.1 placed into it instead of the latest 1.25.0~dev-...  (probably not the right place to complain about this) so I can't test it.

**Comment by adeas31** [comment]
> @adeas31 I was just going to test this in the latest nightly. However it looks like the nightly channel got the 1.24.1 placed into it instead of the latest 1.25.0~dev-... (probably not the right place to complain about this) so I can't test it.

@adrpo can you please fix it.

**Comment by adrpo** [comment]
Ouch, don't tell me I tagged v1.24.1 on master! I will check.

**Comment by adrpo** [comment]
I tagged v1.24.1 on maintenance/v1.24 which should be on the stable channel not nightly.
![image](https://github.com/user-attachments/assets/d9f8ece2-1a6d-4531-9db4-77df234e3452)

**Comment by adrpo** [comment]
This is what we have in our json:
```json
{
      "nightly": "1.25.0~dev-121-g3b470d1",
      "release": "1.24.0",
      "release-buildscriptbranch": "maintenance/v1.24",
      "repo": "OpenModelica",
      "stable": "1.24.1~2-ge6b7b28",
      "stable-buildscriptbranch": "maintenance/v1.24",
      "stable-followbranch": "maintenance/v1.24"
}
```

So on the nightly chan you should get 1.25.

**Comment by dietmarw** [comment]
I'm on the nightly channel on ubuntu 24.04.

**Comment by adrpo** [comment]
> I'm on the nightly channel on ubuntu 24.04.

Something seems wrong. The packages for that are v1.25:
https://build.openmodelica.org/apt/dists/noble/nightly/binary-amd64/Packages

**Comment by dietmarw** [comment]
@adrpo Never mind, different machines, different channels. I got confused. Everything is fine now. Sorry for wasting your time.

@adeas31 Just to confirm, the display issues are now fixed as you said. Thanks again.

**Comment by ceraolo** [comment]
In some cases several error messages arre displayed.

If, for instance I  open Modelica.Electrical.PowerConverters.ThreePhasetwoLevel_PWM
and choose "show model" on multiPhase2Level

I get several error messages:

```
[1] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.

[2] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.

[3] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.

[4] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.

[5] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.

[6] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.

[7] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.

[8] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.

[9] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.

[10] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.

[11] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.

[12] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.

[13] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.

[14] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.

[15] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.

[16] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.

[17] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.

[18] 09:14:42 Scripting Error
Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.


```

**Comment by ceraolo** [comment]
Another comment.
Hierarchical editing would be very useful also in plotting perspective, as an helper to choose output variables to plot.
Is it possible to enable it also there? In case, should I hopen a separate ticket on this?

**Comment by adeas31** [comment]
> In some cases several error messages arre displayed.
> 
> If, for instance I open Modelica.Electrical.PowerConverters.ThreePhasetwoLevel_PWM and choose "show model" on multiPhase2Level
> 
> I get several error messages:
> 
> ```
> [1] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.
> 
> [2] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.
> 
> [3] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.
> 
> [4] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.
> 
> [5] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.
> 
> [6] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.
> 
> [7] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.
> 
> [8] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.
> 
> [9] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.
> 
> [10] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.
> 
> [11] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.
> 
> [12] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.
> 
> [13] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.
> 
> [14] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.fire_n, multiPhase2Level.andCondition_n.u1) already exists.
> 
> [15] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_n.u2) already exists.
> 
> [16] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.andCondition_p.u1, multiPhase2Level.fire_p) already exists.
> 
> [17] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.enable, multiPhase2Level.enable) already exists.
> 
> [18] 09:14:42 Scripting Error
> Connection connect(multiPhase2Level.enableLogic.internalEnable, multiPhase2Level.andCondition_p.u2) already exists.
> ```

This is what @dietmarw reported earlier and is already fixed. Please try the latest nightly.

**Comment by adeas31** [comment]
> Another comment. Hierarchical editing would be very useful also in plotting perspective, as an helper to choose output variables to plot. Is it possible to enable it also there? In case, should I open a separate ticket on this?

Yes, please open a new ticket.

**Comment by ceraolo** [comment]
> 
> This is what @dietmarw reported earlier and is already fixed. Please try the latest nightly.

This was with the latest hightly available this morning on Ubuntu.
Maybe it is not the latest version that was downloaded this morning?
I'll check again in a few days.

**Comment by dietmarw** [comment]
I tested it again and the modification works fine at least when trying the Modelica.Blocks.Example.PID_Controller model. One thing that might be useful though is that there is currently no UI feedback that a modification of components on a lower level was done. You need to check the modelica text. Dymola usually adds a new parameter line with the modification in the parameter dialogue of the component. Maybe that might be an idea.

**Comment by ceraolo** [comment]
> This is what @dietmarw reported earlier and is already fixed. Please try the latest nightly.

The latest nightly today is 1-.25.0-dev-124. Tried it, and found that the issue is still there.

**Comment by casella** [comment]
@dietmarw would you mind opening a separate ticket for that?

**Comment by dietmarw** [comment]
Done in #13112

**Comment by casella** [comment]
After a couple of weeks from when @adeas31 introduced this feature, I think the overall feedback is positive and the feature is here to stay as provided, though there are of course bugs to fix and possible enhancements to consider.

Regarding the issues raised so far in this ticket:
- connection lines not displayed: fixed
- modifications give errors: fixed 
- graphical annotation of model one level up are erroneously displayed: fixed
- missing 'each' when modifying parameters on arrays: see #13126
- error messages showing up: fixed
- enhancement: hierarchical editing as helper for choosing output variables to plot: see #13108.
- feedback on applied modifiers in the GUI: see #13112

I would close this ticket and continue the discussion on specific issues elsewhere.

**Comment by casella** [comment]
> The latest nightly today is 1.25.0-dev-124. Tried it, and found that the issue is still there.

@ceraolo if this doesn't yet work for you, please open a separate ticket so we can follow the issue up properly. Thanks!

**Comment by ceraolo** [comment]
It is not that it does not work for me, It does not work with a MSL model, see
https://github.com/OpenModelica/OpenModelica/issues/2891#issuecomment-2451728904
and 
https://github.com/OpenModelica/OpenModelica/issues/2891#issuecomment-2452908093

OM 1.25.0-dev-124

**Comment by casella** [comment]
> It is not that it does not work for me, it does not work (i.e. it displays a lot of undue error messages) with a MSL model, see [#2891 (comment)](https://github.com/OpenModelica/OpenModelica/issues/2891#issuecomment-2451728904) and [#2891 (comment)](https://github.com/OpenModelica/OpenModelica/issues/2891#issuecomment-2452908093)

Could you please open a separate ticket about that? Thanks!
