### ISSUE TITLE
Fix DynamicSelect for new API

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5631]

**Comment by mwetter** [comment]
The model `Buildings.Fluid.FixedResistances.Examples.FlowJunction` should look like this:
![Screenshot from 2021-09-15 05-16-13](https://user-images.githubusercontent.com/1329080/133431690-a37409f3-fa69-4f06-9a82-98774ac41d1c.png)


In OMEdit, this model looks like this:
![Screenshot from 2021-09-15 05-11-41](https://user-images.githubusercontent.com/1329080/133431037-b5a53e19-3c2e-4b2d-b6bc-54e10b2b574f.png)

Other models however work. For example, `Buildings.Controls.OBC.CDL.Continuous.Validation.Abs` shows the DynamicSelect

**Comment by casella** [comment]
@mwetter, thanks for the report. @perost will investigate and try to fix this.

**Comment by perost** [comment]
The issue with FlowJunction is that is uses `DynamicSelect("", String((if use_T_in then T_in else T) - 273.15, format = ".1f"))`, and we only kind of handle the other overload of `String(Real)`.

So this is mostly an OMEdit issue, the frontend can return whatever format we want but OMEdit needs to handle it somehow. @adeas31, any comments?

**Comment by casella** [comment]
> we only kind of handle the other overload of `String(Real)`.

That is?

I'm not sure I understood what the problem is.

**Comment by perost** [comment]
> > we only kind of handle the other overload of `String(Real)`.
> 
> That is?
> 
> I'm not sure I understood what the problem is.

There are two overloads for `String(Real)`:
```
 String(r, significantDigits=d, <options>)
 String(r, format=s) 
```
We only kind of handle `DynamicSelect` with the first overload (we use `significantDigits` but ignore the other options), but not the second overload.

There's also the added issue that the first argument in the `String` call is an expression and not just a variable name, which I don't know how OMEdit should handle. Since the frontend doesn't know what to do with this it just returns the first argument, in this case an empty string.

**Comment by adrpo** [comment]
To properly fix this we need an expression parser/evaluator in OMEdit. We already have the ANTLR4 Modelica parser linked with OMEdit. I have started working on the evaluator but had no time to finish it. I'll see if I can dig out the code. 

Basically OMEdit should be able to evaluate the Dynamic select expression by looking up the component names in the result file (or the model init file for parameters). OMC should constant evaluate all the constants (or the stuff that doesn't end up in the result files / model init file). This will handle most of the cases but not all.

I think that to make sure we handle all the cases we would need to sent the annotations to OMEdit and evaluate them there as DynamicSelect can be used anywhere in the annotations. OMC should qualify the component names of the components that appear in the annotations so that OMEdit can find them in the init files or the result file.

**Comment by casella** [comment]
> To properly fix this we need an expression parser/evaluator in OMEdit.

This would also finally resolve the long-standing issues [#2081](https://trac.openmodelica.org/OpenModelica/ticket/2081) and [#2661](https://trac.openmodelica.org/OpenModelica/ticket/2661), which would be really good. The first in particular is a major obstacle to proper usability of OMEdit with libraries that use the construct, first of all MSL that usese them extensively since version 3.0.

Although it would be nice to close this ticket by the end of September, we have time to do that until the end of the year. If the task can be handed over to Per, maybe we have a chance of getting it done by then.

BTW, we don't need a particularly sophisticated expression evaluator, the kind of expressions that are used as dynamicSelect or Dialog annotation are usually very simple.

**Comment by casella** [comment]
In any case, it would probably be good to support [all five variants of Strings()](https://specification.modelica.org/maint/3.5/operators-and-expressions.html#numeric-functions-and-conversion-functions), eventually.

**Comment by perost** [comment]
> In any case, it would probably be good to support [all five variants of Strings()](https://specification.modelica.org/maint/3.5/operators-and-expressions.html#numeric-functions-and-conversion-functions), eventually.

That would be solved if OMEdit could evaluate expressions. The arguments of each String overload uniquely identify which overload it is though, so if we need it sooner we can just pass the arguments as a list and let OMEdit figure out what to do. I was going to implement that when I realised it wouldn't help since the first argument is an expression that OMEdit can't evaluate.

**Comment by casella** [comment]
OK. The question then is what is the status of @adrpo's code and if it can be taken over easily by someone else.

A possible workaround on the library side is that we define additional variables/parameters to compute those expressions, and then just use their names in the dynamicSelect annotations, Dialog annotations, and conditional component activation conditions, so that evaluating them would be trivial.

The problem is, we can't really do that with MSL, which is alread released, and it may not be particularly convenient for the user, so I would rather avoid that. 

Maybe one possible solution is to have the NF automatically do that, i.e. generate auxiliary variable/parameter definitions with binding equations corresponding to those expressions, and then using the aux names in the dynamicSelect, Dialog and conditional component activation expressions. For example
```
DynamicSelect("", String((if use_T_in then T_in else T) - 273.15, format = ".1f"))
```
would be transformed into
```
String $aux1 = String((if use_T_in then T_in else T) - 273.15, format = ".1f");
DynamicSelect("", $aux1);
```
and
```
parameter Boolean p1;
parameter Boolean p2;
MyConnector c if p1 and not p2;
```
would become
```
parameter Boolean p1;
parameter Boolean p2;
parameter Boolean $aux1 = p1 and not p2;
MyConnector c if $aux1;
```
etc.

Evaluating them would become trivial for OMEdit. For parameters, there could be an API doing that by (partial?) instantiation. For variables, you just need to pick them in the result file and display them properly.

Seems rather straightforward to implement to me.

@perost, @adrpo, what do you think?

**Comment by perost** [comment]
> @perost, @adrpo, what do you think?

It would be trivial if we only had to change the flattened model, but I'm not sure how it would work in the API. We'd have to change the Absyn, which I guess means changing the user's model too?

**Comment by casella** [comment]
@perost, sorry but I don't get your point. I understand the currently available implementation of dynamicSelect works if the quantity to be displayed is given by a variable or parameter, but it doesn't if it is given by an expression, because OMEdit cannot evaluate it. Is that correct?

In that case, we simply define an additional variable or parameter bound to the original expression, that will be displayed as other "native" non-expression values. Why is it required to change Absyn?

**Comment by perost** [comment]
> @perost, sorry but I don't get your point. I understand the currently available implementation of dynamicSelect works if the quantity to be displayed is given by a variable or parameter, but it doesn't if it is given by an expression, because OMEdit cannot evaluate it. Is that correct?

Yes

> In that case, we simply define an additional variable or parameter bound to the original expression, that will be displayed as other "native" non-expression values. Why is it required to change Absyn?

Because the annotations are not in the flat model, they're in the parsed Absyn. OMEdit fetches the annotations by using the API to query the Absyn model, so we would need to actually change the user's model to make it work.

**Comment by casella** [comment]
I'm sorry, I'm still not sure I get it. If the NF defined additonal variables bound to the original expressions, and then uses then in the annotations instead of the original expressions, in a sense we are changing the user's model. 

So be it, as long as we do that automatically and without changing the model source code on mass storage. Is that a problem?

**Comment by perost** [comment]
> I'm sorry, I'm still not sure I get it. If the NF defined additonal variables bound to the original expressions, and then uses then in the annotations instead of the original expressions, in a sense we are changing the user's model.
> 
> So be it, as long as we do that automatically and without changing the model source code on mass storage. Is that a problem?

The issue is that the NF is not really involved. When using the nfAPI we instantiate the annotations using the NF, but only the annotations. For this to work we'd have to change the Absyn after parsing the model, which will also change what OMEdit shows to the user unless we try to hide it somehow.

I don't really see how to implement that in a sane way, so I will just implement some expression evaluation in OMEdit instead. It's not actually that complicated to do.

**Comment by casella** [comment]
> The issue is that the NF is not really involved. When using the nfAPI we instantiate the annotations using the NF, but only the annotations.

OK. So you just get the expression and that's it. I thought that in these particular cases (dynamicSelect, conditional connectors) we could instantiate the entire model - I thought this was not particularly efficient, but it is already implemented. In fact, it's not really implemented either.

> I don't really see how to implement that in a sane way, so I will just implement some expression evaluation in OMEdit instead. It's not actually that complicated to do.

LGTM. I just wanted to avoid duplicate work, possibly at the cost of slower performance. That can be improved later on.

However if that becomes insane, go for the expression evaluator, you are in a much better position to judge on sanity and on trade/offs than I am in this case 😃

**Comment by perost** [comment]
To keep you up to date I've now implemented an expression class that can parse and evaluate flat modelica expressions and supports most of the builtin operators and functions. There are a few gotchas due to flat modelica lacking type information and all variables are treated as Real, but hopefully that won't cause too many issues. My code is currently written as a standalone program to make it easier to iterate, but I will start integrating it into OMEdit on monday.

One question I have though is how DynamicSelect is actually supposed to work? The specification talks about editing state and non-editing state but doesn't explain what that is. It seems like we don't do anything special with it in OMEdit, but maybe I've missed something?

**Comment by adrpo** [comment]
What I understand is:
- the first is used when showing and editing the diagram and it needs to be constant evaluated to a literal (Modeling perspective, diagram)
- the second will apply dynamic changes on the non-editable diagram (Plotting perspective, diagram)

**Comment by adrpo** [comment]
Basically OMEdit will get the entire annotation as it is but with all the names prefixed properly:

original annotation:
```
annotation (
  Icon(graphics={Rectangle(
     extent=DynamicSelect({{0,0},{20,20}},{{0,0},{20,level}}),
     fillColor=DynamicSelect({0,0,255},
                                             if overflow then {255,0,0} else {0,0,255}))}
  );
```

prefixed annotation:
```
annotation (
  Icon(graphics={Rectangle(
     extent=DynamicSelect({{0,0},{20,20}},{{0,0},{20,prefix.with.what.is.needed.level}}),
     fillColor=DynamicSelect({0,0,255},
                                             if prefix.with.what.is.needed.overflow then {255,0,0} else {0,0,255}))}
  );
```

When displaying the diagram in the Modeling perspective it will use the first argument of DynamicSelect.
When displaying the diagram in the Plotting perspective will evaluate the second argument of DynamicSelect and change the diagram accordingly.

**Comment by adeas31** [comment]
And in the non-editing state i.e., diagram in plotting perspective, you can animate the diagram using the slider and the play controls above the variables browser.

**Comment by perost** [comment]
I've now made PR #7946 that implements expression parsing/evaluation for handling DynamicSelect. There are still some issues, see my comment in that PR, but I can now simulate Buildings.Fluid.FixedResistances.Examples.FlowJunction and the values in the diagram window will then update as I move the time slider.

**Comment by casella** [comment]
Great! As soon as we have it in the nightly we'll ask for feedback from LBL

**Comment by perost** [comment]
The PR is now merged in, so it should be in tomorrow's nightly build. There are still some issues to resolve so I will continue working on it a bit more, but the basic functionality should be there at least.

**Comment by casella** [comment]
@mwetter, can you try this out on the nightly build starting tomorrow and report?

Thanks!

**Comment by mwetter** [comment]
@casella : Yes, I will do tomorrow Thursday.

**Comment by mwetter** [comment]
I don't see any changes to what is reported in the figure of https://github.com/OpenModelica/OpenModelica/issues/5631#issuecomment-919967144.
This is with 1.19.0~dev-232-g2af9139 on Ubuntu 18.04.

**Comment by perost** [comment]
> I don't see any changes to what is reported in the figure of [#5631 (comment)](https://github.com/OpenModelica/OpenModelica/issues/5631#issuecomment-919967144). This is with 1.19.0~dev-232-g2af9139 on Ubuntu 18.04.

Did you try to simulate the model and open a diagram window in the plotting view? The normal diagram view won't change since those values are defined as `DynamicSelect("", ...)", i.e. an empty string for the editing state.

**Comment by mwetter** [comment]
@perost : Yes, I seem to be in the right mode:
![image](https://user-images.githubusercontent.com/1329080/135468804-85891175-3cd0-48d5-b4ad-955ad19f0604.png)

**Comment by perost** [comment]
> @perost : Yes, I seem to be in the right mode: ![image](https://user-images.githubusercontent.com/1329080/135468804-85891175-3cd0-48d5-b4ad-955ad19f0604.png)

Yes, it seems the reason is that our Linux nightly builds are broken for some reason. I will investigate.

**Comment by perost** [comment]
The Windows nightly builds are still working though, if someone wants to test it out.

**Comment by perost** [comment]
The root cause of the issues with the nightly builds is that I updated OMEdit to use C++17, but that broke the job on some of the oldest distros we build for (which made everything fail). We probably only need C++14 for now, but now we're having certification issues on Jenkins instead so I can't push that in. So it seems like it's going to take a while before we get the situation sorted.

**Comment by casella** [comment]
@perost, could you quantify "a while?". One day, one week, one month? Who's responsible for the fix?

**Comment by sjoelund** [comment]
It should be fixed today, probably. We communicate mostly via slack and it also went down around the same time. https://github.com/OpenModelica/OpenModelica/pull/7957 will be merged soon and then it's possible to build with the disable cmake label.

**Comment by perost** [comment]
#7956 is also merged now, hopefully that fixes the Linux nightly builds.

**Comment by mahge** [comment]
There were still certificate related issues. I think the certificate for _build.openmodelica.org_ did not get renewed until a few hours ago. It shows me that it is issued today and valid until 2021-12-31. Something is not right there.

I have restarted the nightly builds again. Hopefully this time there will be no more issues.

**Comment by sjoelund** [comment]
I guess the Debian stretch image just needs to be upgraded. I'll look into that

**Comment by casella** [comment]
Been running for 2hrs now. I hope it gets until the end, previous runs were terminated earlier

**Comment by sjoelund** [comment]
```
GDBMIParser.cpp:439:22: error: no member named 'emplace_back' in 'std::__cxx11::list<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > >'
    parserErrorsList.emplace_back(output);
    ~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
Makefile.lib.common:25: recipe for target 'GDBMIParser.o' failed
make[3]: *** [GDBMIParser.o] Error 1
make[3]: Leaving directory '/var/lib/jenkins/ws/LINUX_BUILDS/tmp.build/openmodelica-1.19.0~dev-253-gba2cc3c/OMEdit/OMEditLIB/Debugger/Parser'
```

@perost OMEdit/OMEditLIB/Debugger/Parser uses its own Makefile and not the one from qmake. I suppose we need to change `AX_CXX_COMPILE_STDCXX_11` to a newer STDCXX_14 or 17.

**Comment by sjoelund** [comment]
I'll try to fix that error

**Comment by perost** [comment]
> I'll try to fix that error

I fixed it in #7964. There's no real reason to use emplace_back instead of push_back there anyway.

**Comment by casella** [comment]
On Windows now it looks like this
![immagine](https://user-images.githubusercontent.com/4233148/135661130-dcec08c2-88cf-46f3-b7d7-888fa14ccd71.png)

The icons with the DynamicSelect annotations are pitch black. @adeas31, @perost, any idea what is still missing?

**Comment by perost** [comment]
> The icons with the DynamicSelect annotations are pitch black. @adeas31, @perost, any idea what is still missing?

I've only implemented it for textString so far, I will change the rest of the annotation attributes to handle DynamicSelect next week.

**Comment by adeas31** [comment]
That is because we now return DynamicSelect as it is and that is only handled for `textString` attribute yet. The ellipse icons are black since the `fillColor` attribute has DynamicSelect in the the annotation and there is no support for it yet so the default black color is color.

**Comment by perost** [comment]
On second thought it's easy to just remove the DynamicSelect calls and use the first argument for annotations that don't yet support it, so I did that in #7967. That way we at least don't break annotations until we implement full support for DynamicSelect.

**Comment by casella** [comment]
OK, thanks!

**Comment by perost** [comment]
It looks like the Linux nightly builds are working again, and the latest one should be up to date with the DynamicSelect improvements.

**Comment by casella** [comment]
OK, with the latest nightly the right static icons are back:
![immagine](https://user-images.githubusercontent.com/4233148/135765314-67e3b26a-a1ab-473f-9de8-e794f1c8f246.png)

I stand by for the complete implementation, then.

**Comment by perost** [comment]
I found an issue that I feared might show up, which is that some parameters used in the annotation does not show up in the result file (in this case `bouX.use_T_in`). OMEdit just returns 0.0 if it can't find a variable, which is bad since it means it works but can give the wrong result (it's happens to be correct for FlowJunction though since `use_T_in` is always false, which is what 0.0 is interpreted as).

I'm not sure what determines whether a parameter is recorded in the result file or not. The ones I've seen have `HideResult=true` which might be what's causing the issue. We could make sure any such parameters are evaluated by the frontend when dealing with annotations, but that's not guaranteed to work since it can only evaluate fixed parameters.

**Comment by casella** [comment]
> I found an issue that I feared might show up, which is that some parameters used in the annotation does not show up in the result file (in this case `bouX.use_T_in`). OMEdit just returns 0.0 if it can't find a variable

I guess it should give NaN instead, unless there are good reasons to use this default value. It seems a bit dangerous to me.

> which is bad since it means it works but can give the wrong result (it's happens to be correct for FlowJunction though since `use_T_in` is always false, which is what 0.0 is interpreted as).

See above.

> I'm not sure what determines whether a parameter is recorded in the result file or not. The ones I've seen have `HideResult=true` which might be what's causing the issue.

Certainly, it is set [in here](https://github.com/lbl-srg/modelica-buildings/blob/c10d15de853e42c6af194727b975e82be12f9019/Buildings/Fluid/Sources/Boundary_pT.mo#L15). By default also protected variables are not saved, but there is a flag [-emit-protected](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-emit-protected) to override that.

> We could make sure any such parameters are evaluated by the frontend when dealing with annotations, but that's not guaranteed to work since it can only evaluate fixed parameters.

I guess in most if not all cases these parameters have some kind of structural value. In this specific case there is actually an `Evaluate = true` annotation, but even absent that this parameter is used to activate conditional components, so it can't for sure be changed at runtime. 

So, I'm fine with a solution that evaluates them and makes the frontend return their numerical value.

**Comment by mwetter** [comment]
The time series are corrected when plotted as a graph in OMEdit, just the schematic model view shows these wrong results.

**Comment by mwetter** [comment]
@perost : With
```modelica
DynamicSelect("", String(T, format="1.f"))
```
I get the correct display.

(Tested using OpenModelica 1.19.0~dev-271-gb6f3a96 which also reproduces the wrong display reported in https://github.com/OpenModelica/OpenModelica/issues/5631#issuecomment-939143157)

**Comment by casella** [comment]
Is it perhaps a Fahrenheit reading? 😄 

@mwetter this is really strange, any of your collegues reporting the same issue?

**Comment by perost** [comment]
The issue with the old API is solved in #7995, and with that I think we can finally close this issue.

The problem was that e.g. `T - 273.15` was "simplified" by the old frontend to `-273.15 - T`, which due to a mistake in the Expression class was parsed as `-(273.15 - T)`.
