### ISSUE TITLE
instantiateModel works fine, but dumpXMLDAE fails with stack overflow error

### ISSUE THREAD

**Issue by CSchoel** [OpenModelica/OpenModelica#6919]
In my current quest to fully switch to the new OMC front-end using `-d=newInst,nfAPI` I came across a strange error that would only occur in the function `dumpXMLDAE`, which I use to get the model equations as content MathML to generate a HTML documentation.

When I run the following script

```modelica
setCommandLineOptions("-d=newInst,nfAPI");
loadModel(Modelica);
loadModel(InaMo);
instantiateModel(InaMo.Examples.SodiumChannelSteady); // works fine
simulate(InaMo.Examples.SodiumChannelSteady); // also works fine
getErrorString();
dumpXMLDAE(InaMo.Examples.SodiumChannelSteady); // errors with stack overflow
getErrorString();
```

I get this error message from the final `getErrorString()`:

```verbatim
"[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/IonChannelGHK.mo:8:3-8:61:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Temperature na.temp declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:11:3-11:41:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Concentration na.na_ex declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:12:3-12:38:writable] Warning: No corresponding 'inner' declaration found for component .InaMo.PermeabilityFM na.na_p declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateAB.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.act.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateAB$na$act.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.inact_fast.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateTS$na$inact_fast.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.inact_slow.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateTS$na$inact_slow.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:9:3-9:53:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Concentration na.na_in declared as 'outer '.
  The existing 'inner' components are:
    .Modelica.SIunits.Voltage na.v_gate; defined in scope: InaMo.Components.IonCurrents.SodiumChannel.
    .Modelica.SIunits.Current na.i_ion; defined in scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
Error: Stack overflow occurred while evaluating dumpXMLDAE(InaMo.Examples.SodiumChannelSteady):
[bt] #1 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaRuntimeC.so(mmc_setStacktraceMessages_threadData)
[bt] #2 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaRuntimeC.so(mmc_do_stackoverflow)
[bt] #3 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(FGraph.currentScope)
[bt] #4 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupUnqualifiedImportedClassInFrame)
[bt] #5 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassInFrame)
[bt] #6 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassInEnv)
[bt] #7 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassQualified)
[bt] #8 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClass2)
[bt] #9 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupUnqualifiedImportedClassInFrame)
[bt] #10 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassInFrame)
[bt] #11 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassInEnv)
[bt] #12 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClassQualified)
[bt] #13 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupClass2)
[bt] #14 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupUnqualifiedImportedClassInFrame)
...
[bt] #1024 /usr/bin/../lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so(Lookup.lookupUnqualifiedImportedClassInFrame)
[bt] #1025 [...]
"
```

The models that I used for the above script can be found in this repository: https://github.com/CSchoel/inamo
The model `SodiumChannelIV` is only slightly different from `SodiumChannelSteady` but does not show this stack overflow error.
For easier debugging I have also attached a flat version of the `SodiumChannelSteady` model ([SodiumChannelSteadyTotal.zip](https://github.com/OpenModelica/OpenModelica/files/5524724/SodiumChannelSteadyTotal.zip)), which I obtained with the "Save Total" feature of OMEdit.

The models are still under development and may very well contain some errors on my end, which was also the case in previous issues. However, I wanted to report this error since it is at least strange that it only occurs in `dumpXMLDAE` and not in `instantiateModel` or `simulate`.

OpenModelica version used: OMCompiler v1.17.0-dev.94+g4da66238ab

**Comment by perost** [comment]
`dumpXMLDAE` uses the old frontend so it should in theory not be affected by `-d=newInst`, but it seems there's some interference anyway. I will take a look.

Unrelated though is that for me your script failed because `loadModel(Modelica)` loaded Modelica 4.0.0 (because that's the latest version I have installed), while your library seems to use Modelica 3.2.x. You can fix that by adding a `uses` annotation to the package.mo in your library (like `uses(Modelica(version="3.2.3"))`), which is a good idea regardless. OMC will then load that library automatically when loading your library, so you won't need to load it manually anymore.

**Comment by perost** [comment]
The issue should be fixed in #6921. Eventually we'll want to change `dumpXMLDAE` to use the new frontend, but for now we just disable the new frontend before running `dumpXMLDAE` and then turn it on again after.

**Comment by CSchoel** [comment]
Thank you so much for the quick fix! `dumpXMLDAE` is essential for the documentation features of my library and while it would have been possible, it would have been quite cumbersome to internally switch between activating and deactivating the new frontend. I will try out the new version ASAP. :+1: 

Also thanks for the heads up on the MSL version conflict! :smile: I was neither aware that there are version conflicts nor of the `uses` annotation.

**Comment by perost** [comment]
> Also thanks for the heads up on the MSL version conflict! smile I was neither aware that there are version conflicts nor of the `uses` annotation.

You might also want to add a version-annotation, see [18.8 in the specification](https://specification.modelica.org/master/annotations.html#annotations-for-version-handling) for the annotations relevant to version control of libraries.

**Comment by CSchoel** [comment]
I can confirm that with version `OMCompiler v1.17.0-dev.134+gaead3d1077` the stack overflow error does no longer occur. :+1: 

However, I still get the errors related to missing `inner` declarations, which is odd, as the simulation of the model runs without errors both with my local OMC version and on Travis CI with the latest Ubuntu package (i think that is version 1.16.0?) and with version 1.14.2.

Also I now get a different error stating that the equation system is underdetermined:

```verbatim
"[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/IonChannelGHK.mo:8:3-8:61:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Temperature na.temp declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:11:3-11:41:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Concentration na.na_ex declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:12:3-12:38:writable] Warning: No corresponding 'inner' declaration found for component .InaMo.PermeabilityFM na.na_p declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateAB.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.act.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateAB$na$act.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.inact_fast.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateTS$na$inact_fast.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.ElectricPotential na.inact_slow.v_gate declared as 'outer '.
  The existing 'inner' components are:
    There are no 'inner' components defined in the model in any of the parent scopes of 'outer' component's scope: InaMo.Components.IonCurrents.GateTS$na$inact_slow.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/SodiumChannel.mo:9:3-9:53:writable] Warning: No corresponding 'inner' declaration found for component .Modelica.SIunits.Concentration na.na_in declared as 'outer '.
  The existing 'inner' components are:
    .Modelica.SIunits.Voltage na.v_gate; defined in scope: InaMo.Components.IonCurrents.SodiumChannel.
    .Modelica.SIunits.Current na.i_ion; defined in scope: InaMo.Components.IonCurrents.SodiumChannel.
  Check if you have not misspelled the 'outer' component name.
  Please declare an 'inner' component with the same name in the top scope.
  Continuing flattening by only considering the 'outer' component declaration.
Error: Too few equations, under-determined system. The model has 55 equation(s) and 58 variable(s).
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: Variable na.inact_slow.v_gate does not have any remaining equation to be solved in.
  The original equations were:
  Equation 13: na.inact_slow.tau = InaMo.Components.IonCurrents.GateTS$na$inact_slow.ftau(na.inact_slow.v_gate, 0.00295, 0.12295, -0.06, -500.0, 1.0, 1.0, 1.0), which needs to solve for na.inact_slow.tau
  Equation 12: na.inact_slow.steady = InaMo.Components.IonCurrents.GateTS$na$inact_slow.fsteady(na.inact_slow.v_gate), which needs to solve for na.inact_slow.steady
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateTS.mo:8:3-8:80:writable] Warning: Variable na.inact_fast.v_gate does not have any remaining equation to be solved in.
  The original equations were:
  Equation 10: na.inact_fast.tau = InaMo.Components.IonCurrents.GateTS$na$inact_fast.ftau(na.inact_fast.v_gate, 0.00035, 0.03035, -0.04, -166.6666666666667, 1.0, 1.0, 1.0), which needs to solve for na.inact_fast.tau
  Equation 9: na.inact_fast.steady = InaMo.Components.IonCurrents.GateTS$na$inact_fast.fsteady(na.inact_fast.v_gate), which needs to solve for na.inact_fast.steady
[/home/cslz90/Documents/Promotion/code/2019-schoelzel-inada/InaMo/Components/IonCurrents/GateAB.mo:8:3-8:80:writable] Warning: Variable na.act.v_gate does not have any remaining equation to be solved in.
  The original equations were:
  Equation 5: na.act.beta = InaMo.Components.IonCurrents.GateAB$na$act.fbeta(na.act.v_gate, -0.0444, -78.90791446382072, 18400.0), which needs to solve for na.act.beta
  Equation 4: na.act.alpha = InaMo.Components.IonCurrents.GateAB$na$act.falpha(na.act.v_gate, -0.0444, 5829.58, -78.90791446382072), which needs to solve for na.act.alpha
"
```

This seems to be related to the `inner` variables that were falsely repored as missing, since `checkModel` reports 55 equations and variables while  error message reports 58 variables.

**Comment by perost** [comment]
That's odd, neither the old nor the new frontend gives such errors normally, only when using `dumpXMLDAE`. It might be using the frontend wrong or something, I will have a look.

**Comment by perost** [comment]
The issue with dumpXMLDAE should be fixed in #6935. I've changed so that we now use the normal "run frontend" function everywhere instead of calling the instantiation directly, which besides fixing the issue you encountered also automatically loads any missing packages and uses the chosen frontend.

Since `dumpXMLDAE` previously always used the old frontend it's a bit uncertain how well it works with the new. I changed our tests of `dumpXMLDAE` to use the new frontend and they look ok to me, but please let us know if you find any issues.

**Comment by CSchoel** [comment]
Nice! :+1:  :1st_place_medal:  Can confirm that the issues is fixed in `OMCompiler v1.17.0-dev.159+gc2ca162139`. Thank you so much for the quick response! :smiley: 

I will close this issue and report back, should I encounter any additional issues.
