### ISSUE TITLE
Persisting medium issue after defining Medium in Open Modelica

### ISSUE THREAD

**Issue by WernerWaho** [OpenModelica/OpenModelica#7556]
### Description

In Open Modelica Fluid Environment, I´m seeing the Error "Medium is partial, name lookup is not allowed in partial classes." Which is commonly solved properly defining the media in each element.

I followed the related instruction of the post (How to specify medium in Openmodelica?) Namely I have redeclared the medium in each component of my system but still get this error when I try to simulate, although the check went through just fine.

Now this error is referenced to the Interfaces file, specificaly the line:

"stream Medium.ExtraProperty C_outflow[Medium.nC] "Properties c_i/m close to the connection point if m_flow < 0"; "

Do you understand why this still happens? I guess this C_outflow refers to concentration or other specific property of fluid. However I haven´t set any particular property. I tried turning false the allowFlowReversal option in order to not have m_flow < 0 but it didn´t help.

Additionally I have a translation issue as you may see in the first image, but I didn´t define the factor 1.1 anywhere with the unit "m". The second image shows the source of the issue in the machine library. This is confusing as well...

Do you have any ideas of how to solve this issue? I´d appreciate any help from the team.

Here my model code (in .txt since the OM_model cannot be uploaded).  Many thanks in advance.

### Steps to Reproduce

Copy model and Simulate

### Expected Behavior

I wish to model a system that simulates the performance of pressure temperature and air saturaturation in the fluid that flows through two tanks, a pump and a pipe. This Model uploaded is the first simplified version of the system and as I´m able to simulate I´ll introduce more aspects, such as heat transfer and air influx in Tank_1.

[Prufstand1.txt](https://github.com/OpenModelica/OpenModelica/files/6647758/Prufstand1.txt)

### Screenshots
![image](https://user-images.githubusercontent.com/85873402/121877915-6bb09100-cd0b-11eb-868e-dd05755b4299.png)

![image](https://user-images.githubusercontent.com/85873402/121880845-c8617b00-cd0e-11eb-9bda-ea1d1f311a8d.png)

### Version and OS

 - OpenModelica Version:  the lastest version (Official Release, 1.17.0, (32bit/64bit)]
 - OS:  Windows 10, 64 bit

**Comment by perost** [comment]
The issue is that you haven't redeclared Medium in your `valveIncompressible` component.

**Comment by perost** [comment]
Perhaps I was a bit hasty, I missed that you had a second issue with the unit checking. That might not be your fault, it could be an issue with the unit checking or the library itself. I'll see if I can get someone who knows more about such issues to take a look.

**Comment by perost** [comment]
I noticed that we used to have a better error message in the old frontend which got lost when implementing the new one. I implemented the old error message in the new one (in #7559), so in the next release the error message will instead be:
```
[~/.openmodelica/libraries/Modelica 4.0.0+maint.om/Fluid/Interfaces.mo:218:45-218:68:writable] Notification: From here:
[~/Prufstand1.mo:23:1-24:115:writable] Error: component valveIncompressible contains the definition of a partial class Medium.
Please redeclare it to any package compatible with Modelica.Media.Interfaces.PartialMedium.
```

**Comment by WernerWaho** [comment]
thank you Perost for noticing that missing declaration. I guessed that went unnoticed by me cause the valve seem to not take further parameters, as it had no parenthesis. I fixed the model, which I attach but have the issue of having 1 variable more as equations. Maybe the issue still lies in the "machines" library unit checking ?

![image](https://user-images.githubusercontent.com/85873402/121959573-45b7da80-cd65-11eb-9f4b-ddefdb4298c2.png)
[Prufstand1.txt](https://github.com/OpenModelica/OpenModelica/files/6651283/Prufstand1.txt)

**Comment by WernerWaho** [comment]
I opened new issue to follow-up this question :) #7562

**Comment by casella** [comment]
> thank you Perost for noticing that missing declaration. I guessed that went unnoticed by me cause the valve seem to not take further parameters, as it had no parenthesis. I fixed the model, which I attach but have the issue of having 1 variable more as equations.

Is it because the valve opening input signal is not connected?
