### ISSUE TITLE
Distribution of the OpenModelica variant with encryption

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#7560]
This ticket is for a discussion on how to distribute the OpenModelica variant with encryption.

1. distribute from openmodelica website via one public link
   - pros: easy and clear
   - cons: 
              * anybody can unpack encrypted libraries if they don't have any licensing executable
              * we don't know who uses the OpenModelica with encryption
           
2. distribute from openmodelica website with registration
   and a unique link that can be used once for download 
   (with captcha so that automatic link checkers can't access it)
   - pros: 
              * we know who uses the OpenModelica with encryption
              * still an easy process
              * we keep the executable with encryption from being public
   - cons: a bit of administration and implementation to generate the forms

Currently only the OMSC members can access the OpenModelica build with encryption support.

**Comment by niklwors** [comment]
I think proposal two is very good. 
Is the effort for the creation of the unique link and the possibility of registration large?
What data should all be entered during registration. E.g. the name and surname, email address and organization?

**Comment by sjoelund** [comment]
You could also do:

3. Public download as usual installer (Windows, Linux, etc). But we include our own license check (you can do it like 2 except you get a license file instead of an installer; this could include requiring online access to check for newer versions, and refusing to load encrypted libraries e.g. if the version is broken). This way you get fewer installers to maintain.

**Comment by niklwors** [comment]
Proposal three sounds also very good. We found these licensing tools which could be used for example:
https://github.com/amrayn/licensepp
https://github.com/plstcharles/meta-licensor
http://open-license-manager.github.io/licensecc/index.html

**Comment by siscosan** [comment]
Hi all,

I'm a colleague of @niklwors.

I like proposal three, and I would like to understand it better because of the online access to check for newer version feature.

I would like to have the encryption feature included in the "normal" version. This way you do not need to maintain more installers as @sjoelund  mentioned.

To prevent everybody to use this feature, the user needs a license (which is not part of the installer). If you want to use encryption, OM checks that there is no valid license and opens a "request license" dialog. The dialoge shows the hardware ID of the machine and has a "request license" button that opens/sends a mail to your team using the mail client of the machine. 

This way you will know that somebody out there want's to use encryption, and you can provide them the license file that is valid for a certain period of time.

The user receives this license in the mail and uses the same "request license" dialog to "import the license". Now he can use the encryption feature.

You get
- no additional installer
- direct information who wan'ts to use encryption
- a way to "controlled provide" future features to users

I think the "check for newer [OMEdit] versions" is something that should be implemented parallel, as a new version can also be released without anything changed to the encryption feature.

Niklas mentioned some C++ licensing libraries that could help in implementing such a feature. 

There is one open question for me - I don't understand the "refusing to load encryptied libraries e.g. if the version is broken". Can you @sjoelund  provide more information to us?

Best regards,
Francisco

**Comment by sjoelund** [comment]
> There is one open question for me - I don't understand the "refusing to load encryptied libraries e.g. if the version is broken". Can you @sjoelund provide more information to us?

There are some open tickets about older versions of the version with encryption support not working as it should (ignoring some license checks, etc). I think we would actually need some way of disabling older versions (or changing the encryption key, but then perhaps some version could be used to extract information from the libraries)...

The disadvantage of 3 is that there is a lot more that would need to be implemented (taking time from other planned features).

**Comment by niklwors** [comment]
@sjoelund  You can make sure that only new version of OMEdit is used with the new SEMLA integration by changing the public key of OpenModelica. Then the libraries must be encrypted with the new OpenModelica public key so that they can be used with the latest version.

**Comment by sjoelund** [comment]
> @sjoelund You can make sure that only new version of OMEdit is used with the new SEMLA integration by changing the public key of OpenModelica.

That does nothing for people with an older version of OMEdit installed.

**Comment by siscosan** [comment]
Thanks @sjoelund  - now I understand this.

After typing several lines I came to the conclusion that it would be the best to discuss this in a meeting ;-)

If you want to disable a version A installed on the user PC, you need some kind of connection between the version on the PC and kind of "master switch" in your hands. A license could solve this problem - think about "encryption features available for 1 year". After this year it does not work anymore....

A better solution would be a license server so the version A checks online if the feature is still valid or not... 

but a license server is kind of more implementation, administration and budget...

**Comment by petfr** [comment]
Feel free to organize a web meeting on this topic.

Peter

**Comment by niklwors** [comment]
@sjoelund you can than not load the encryped library because the encrypted library does not support the old OpenModelica public key

**Comment by siscosan** [comment]
@niklwors - yes, but you can still use your old version A with the old encrypted library A 

Niklas will ask in the next DEV meeting when we could do such a meeting to discuss this topics.

**Comment by sjoelund** [comment]
> @sjoelund you can than not load the encryped library because the encrypted library does not support the old OpenModelica public key

It should be possible to have multiple public keys. Need Adeel to check that.

> @niklwors - yes, but you can still use your old version A with the old encrypted library A

Not with my proposal...

**Comment by adrpo** [comment]
We will have a meeting about this in 30 June @ 13:00, let me know if you want to join that meeting.

**Comment by adrpo** [comment]
Option 3
- have a license server on openmodelica.org
- if there are issues, fallback to option 2 or have a file based license
- 2 versions are needed so no debug symbols in the encrypted one

Issues:
- fix SEMLA and OMC bugs
- remove the C comments which show the model equations
- C code obfuscation, how about the names of the variables?
  * check C/C++ obfuscation libraries
- debug flags that dump a lot of information from the models
- FMU export should be restricted
- FMU source code removed

Harder things:
- Modelica code obfuscation?
- using the debugger?

**Comment by adrpo** [comment]
MA - MCP encryption: https://github.com/modelica/ModelicaSpecification/tree/MCP/0039/RationaleMCP/0039

**Comment by casella** [comment]
- Regarding Modelica code obfuscation, @perost just implemented that for NDA-free Save Totals in #8067. I guess this could be easily adapted to encrypted libraries
- Regarding removing comments from C code, we could do the same as in #7643

@adrpo's comment on 30 Jun is a good summary of the requirements, but we need to turn that into an actual work plan. @niklwors, we can discuss this in detail in one of the next devmeetings

**Comment by casella** [comment]
Additional info:
- SEMLA and OMC bugs should be fixed now.
- Remove comments from C, same as @rfranke's -> @perost
- Obfuscation should only be applied to instances of encrypted models, check with @perost
- FMU export should not have source code, only the binaries -> @mahder can take care of this
- Debugger will become "useless" on the obfuscated parts

Distribution:
- have a form to fill in under a password-protected part of the website
- generate a use-once URL so we keep track on who has it
- only problem: we can't take back a license, but given the development pace of OMC that shouldn't be a big deal
- probably change the key with each new version, so you get stuck with old library and old omc

**Comment by casella** [comment]
@adeas31 can you please help with the form handling? Please ask @adrpo for details, it should be straightforward.

**Comment by casella** [comment]
@adeas31 please ask @adrpo about details, I guess you can take care of the implementation. This is needed anytime soon

**Comment by niklwors** [comment]
It is still missing that the download page is still empty and has no content, such as an OpenModelica logo and a short description of what the page is for.

**Comment by casella** [comment]
@adeas31 could you please take care of that?

**Comment by adeas31** [comment]
I don't know much about it. @arun3688 designed the download page.

**Comment by arun3688** [comment]
@adeas31 Adrian decided not to use the keycloak interface as it was too complicated to fix few stuffs and he decided to use a very simple web interface using Apache, but I don't know how the web interface looked like 
@adrpo can you please comment on this
