### ISSUE TITLE
Conversion scripts not fully working

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OpenModelica#7683]
Example of an error, possibly due to imports not being converted (I did not have time to check this):
https://libraries.openmodelica.org/branches/conversion/OpenIPSL_release/files/OpenIPSL_release_OpenIPSL.Examples.Controls.PSSE.ES.EXNI.err

https://libraries.openmodelica.org/branches/overview-special-jobs.html

**Comment by perost** [comment]
The issue is that OpenIPSL contains code like this:
```Modelica
package OpenIPSL
  import SI = Modelica.SIunits;

  model Bus
    SI.Conversions.NonSIunits.Angle_deg angleDisplay;
  end Bus;
end OpenIPSL;
```
The conversion script for MSL 4.0.0 then contains the rules:
```Modelica
convertClass("Modelica.SIunits", "Modelica.Units.SI")
convertClass("Modelica.SIunits.Conversions", "Modelica.Units.Conversions")
```
Since the SI units where moved to their own subpackage in MSL 4.0.0 it's not possible to only convert the import statement and end up with correct code. Unless I've missed something it seems like we'd have to apply the imports everywhere to be able to handle this, but that seems too intrusive (would be fine if the only goal was to simulate a model, but not for updating libraries).

So I'm not sure how we should handle this case.

**Comment by sjoelund** [comment]
If you could detect only the cases where this is necessary, that would be totally fine. How would you even manually update references to these imports? Perhaps:

```
package OpenIPSL
  import NonSI = Modelica.Units.NonSI;

  model Bus
    NonSI.Angle_deg angleDisplay;
  end Bus;
end OpenIPSL;
```

But you'd need to see if NonSI was already in that scope, and it seems easier to just update the references...

**Comment by casella** [comment]
Adding tweaks that look at specific class names seems to me a bit borderline. We can use this as a temporary hack, but the issue should be resolved properly, otherwise it may not work with other libraries and other conversion scripts.

What is not clear to me is what does the specification say in these two cases? Is it clear what the outcome should be, or is it ambiguous?

**Comment by perost** [comment]
> What is not clear to me is what does the specification say in these two cases? Is it clear what the outcome should be, or is it ambiguous?

The specification says nothing about this. I opened [#2981](https://github.com/modelica/ModelicaSpecification/issues/2981), and from the answers I got from Hans it seems it's not possible to handle this case without name lookup. And that requires using the old version of the library that the conversion script is from, which may not be available. 

We could probably handle this better by just applying imports to all names before converting them and disregarding any possible shadowing, but handling that correctly while not needlessly fully qualifying names might be tricky. If we want to also do name lookup in the old library we might as well start over from scratch.

**Comment by sjoelund** [comment]
Is this something that can be fixed by changing the conversion script in MSL 4? If so, it might be an appropriate place for it

**Comment by perost** [comment]
> Is this something that can be fixed by changing the conversion script in MSL 4? If so, it might be an appropriate place for it

No, as conversion is specified I don't think it's possible to handle conversion 100% correctly without access to the old library and looking up all names in the library being converted.

**Comment by casella** [comment]
As agreed during the devmeeting, @perost will implement a solution that assumes no shadowing is taking place, then we see how it goes and possibly continue the discussion in Modelica ticket [#2981](https://github.com/modelica/ModelicaSpecification/issues/2981)

**Comment by casella** [comment]
@mahge noticed some shadowing in the MSL that was not fixed in 4.0.0, see https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Fluid/Dissipation.mo#L471 vs. https://github.com/modelica/ModelicaStandardLibrary/blob/4577c01e1f71fc684c256837250b5adcbf58fd5a/Modelica/Fluid/Dissipation.mo#L500

**Comment by perost** [comment]
> @mahge noticed some shadowing in the MSL that was not fixed in 4.0.0, see https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Fluid/Dissipation.mo#L471 vs. https://github.com/modelica/ModelicaStandardLibrary/blob/4577c01e1f71fc684c256837250b5adcbf58fd5a/Modelica/Fluid/Dissipation.mo#L500

That won't be an issue since there are no conversion rules for `Modelica.Constants.eps`. If there were we could handle it by ignoring imports shadowed by local elements. It's only an issue if imports are shadowed by inherited names, i.e. names that require lookup to find.

**Comment by perost** [comment]
I have now implemented a new solution in #7881 that takes imports into account and also handles shadowing by local elements (but not inherited), and the OpenIPSL model now works without any manual hacks.

@sjoelund: Can you run the conversion job again?

**Comment by sjoelund** [comment]
> @sjoelund: Can you run the conversion job again?

https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/3845/parameters/ - I guess it's ready tomorrow morning at latest.

**Comment by casella** [comment]
[This page](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/3845/) tells me the job is finished, but the [report](https://libraries.openmodelica.org/branches/overview-special-jobs.html) still shows OpenIPSL with only 20 models passing the frontend after conversion.

Do I miss something?

**Comment by perost** [comment]
> [This page](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/3845/) tells me the job is finished, but the [report](https://libraries.openmodelica.org/branches/overview-special-jobs.html) still shows OpenIPSL with only 20 models passing the frontend after conversion.
> 
> Do I miss something?

It reports that `OpenIPSL.Examples.Controls.PSSE.ES.EXNI` still has conversion issues, but that model is definitely working for me. So I'm not sure what's going on either, did it miss my changes somehow? I don't know how to see which commit the job is testing.

**Comment by sjoelund** [comment]
c4c85238ef according to the OMC version on the library page

**Comment by sjoelund** [comment]
Although... I'm wondering if it does the conversion with the compiled omc or the saved omc. I might need to change something in the testing script

**Comment by casella** [comment]
> Although... I'm wondering if it does the conversion with the compiled omc or the saved omc. I might need to change something in the testing script

@sjoelund, did you check in the meantime?

**Comment by sjoelund** [comment]
Yes. It seems omc now crashes somewhere during conversions...

**Comment by casella** [comment]
The conversion test job was finally reported successfully, see [report](https://libraries.openmodelica.org/branches/overview-special-jobs.html). The situation has vastly improved, but there are still some issues, mostly with imports and SIunits lookup, e.g.:

- [PowerGrids](https://libraries.openmodelica.org/branches/conversion/PowerGrids/PowerGrids.html), most test cases failing with `Error: Function CM.'abs' not found in scope PortAC`, where `CM` is `import CM = Modelica.ComplexMath;`
- [ScalableTestSuite](https://libraries.openmodelica.org/branches/conversion/ScalableTestSuite/ScalableTestSuite.html), many tests failing with `Error: Class SIunits.Voltage not found in scope TransmissionLineEquations` because `import Modelica.SIunits;` didn't work
- [ThermoFluidStream](https://libraries.openmodelica.org/branches/conversion/ThermofluidStream/ThermofluidStream.html) most tests failing because of `Error: Class SI.Conversions.NonSIunits.Pressure_bar not found in scope BaseProperties`
- [Buildings](https://libraries.openmodelica.org/branches/conversion/Buildings_7.0.0/Buildings_7.0.0.html) a few classes failing because of broken package constant lookup `Error: Variable R not found in scope gasConstant`, see e.g. [Buildings.Media.Examples.AirProperties](https://libraries.openmodelica.org/branches/conversion/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Media.Examples.AirProperties.err)
- [HelmholtzMedia](https://libraries.openmodelica.org/branches/conversion/HelmholtzMedia/HelmholtzMedia.html): `Error: Base class Modelica.Media.Examples.Tests.Components.PartialTestModel not found in scope ButaneTestModel_dT`, see e.g. [HelmholtzMedia.Examples.MediaTestModels.ButaneTestModel](https://libraries.openmodelica.org/branches/conversion/HelmholtzMedia/files/HelmholtzMedia_HelmholtzMedia.Examples.MediaTestModels.ButaneTestModel_dT.err)

@perost, could you please have a look? I guess we're almost done with this, it would be nice to have conversions ready ASAP.

**Comment by perost** [comment]
> @perost, could you please have a look? I guess we're almost done with this, it would be nice to have conversions ready ASAP.

As sjoelund mentioned there's still some issue with omc crashing or something, so the results are still without my fixes unfortunately.

**Comment by casella** [comment]
Ah, OK. There was already a marked improvement, so I thought they were the ones.

@perost, can you please confirm that those models work fine on your own branch?

BTW, how could I run them on my nighlty build, is there an API to call already?

**Comment by perost** [comment]
@sjoelund found out that the conversion crashed on the SolarTherm library, which turned out to be due to a bug in MetaModelica. I opened #7898 which works around the bug, and have also reported the bug itself in #7899.

**Comment by casella** [comment]
OK, now we have the [test results](https://libraries.openmodelica.org/branches/overview-special-jobs.html) with the latest commits by @perost.

They are quite good but not yet perfect, we have about 200 failures out of 11000 models, 2/3 of which are in EDF libraries, probably because of some common pattern. I'll investigate and report.

**Comment by casella** [comment]
One common issue is shown, e.g., in [AixLib.Media.Examples.AirProperties](https://libraries.openmodelica.org/branches/conversion/AixLib_latest/files/AixLib_latest_AixLib.Media.Examples.AirProperties.err):
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries/.openmodelica/libraries
/AixLib 1.0.0-master/Media/Air.mo:294:5-294:64:writable]
Error: Variable R not found in scope gasConstant.
```
In the original library, package Air extends `Modelica.Media.Interfaces.PartialCondensingGases`, and expects to find the package constant R there, which is defined in the base package. Apparently something goes wrong, @perost could you please check?

**Comment by casella** [comment]
Another issue is found in [HanserModelica.Electrical.RLSeriesFrequencySweep](https://libraries.openmodelica.org/branches/conversion/HanserModelica/files/HanserModelica_HanserModelica.Electrical.RLSeriesFrequencySweep.err):
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries/
.openmodelica/libraries/HanserModelica 1.1.1-master/Electrical/RLSeriesFrequencySweep.mo:47:3-47:108:writable]
Error: Variable voltageSensor.y not found in scope RLSeriesFrequencySweep.
```
This is actually quite strange, unfortunately I can't see the converted library easily, so I don't know what's in the converted class. @perost, please check.

**Comment by casella** [comment]
Model [OpenHydraulics.Circuits.OpenCenter](https://libraries.openmodelica.org/branches/conversion/OpenHydraulics/files/OpenHydraulics_OpenHydraulics.Circuits.OpenCenter.err) fails because  of:
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries
/.openmodelica/libraries/OpenHydraulics 1.0.0-master/Components/Cylinders/DoubleActingCylinder.mo:83:3-86:65:writable] 
Error: Class ObsoleteModelica4.Mechanics.MultiBody.Types.Init not found in scope DoubleActingCylinder.
```
Maybe the ObsoleteModelica4 library is not correctly loaded for some reason?

**Comment by casella** [comment]
Most models in TAeZoSysPro fail because of
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries
/.openmodelica/libraries/TAeZoSysPro master/Media/Air/MoistAir.mo:30:3-30:32:writable] 
Notification: From here:
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries
/.openmodelica/libraries/TAeZoSysPro master/Media/Air/MoistAir.mo:31:3-31:27:writable]
Error: Qualified import name SI already exists in this scope.
```

**Comment by sjoelund** [comment]
> Maybe the ObsoleteModelica4 library is not correctly loaded for some reason?

That's quite likely. I didn't add it to the uses-annotation of converted libraries. I suppose that should always be done. Unless Per could somehow update the AST automatically when the conversion script runs? (Updating both the Modelica uses-annotation I am already updating in my script, and when another library is being added... I suppose use the package manager to set it to whatever version is compatible with the package we are converting... I could perhaps check how to query this if it helps)

**Comment by casella** [comment]
Last, but not least, the entire PowerSysPro library is broken because of
[this issue](https://libraries.openmodelica.org/branches/conversion/ThermoSysPro/files/ThermoSysPro_ThermoSysPro.Examples.Book.SimpleExamples.PressureLoss.TestBend.err):
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelicaLibraryTesting/converted-libraries
/.openmodelica/libraries/ThermoSysPro 3.2.0-master/Properties/WaterSteam/BaseIF97.mo:1503:7-1503:23:writable]
Error: Variable g.R not found in scope g5.
```
`R` is a constant, so maybe it's similar to the issue in AixLib

**Comment by casella** [comment]
> > Maybe the ObsoleteModelica4 library is not correctly loaded for some reason?
> 
> That's quite likely. I didn't add it to the uses-annotation of converted libraries. I suppose that should always be done.

Not really, only if there are actually some ObsoleteModelica4 models in the converted library. Otherwise we introduce a lot of totally bogus dependencies.

Not sure what is the proper way to handle this, I guess there should be a provision for this in the specification of the conversion script, i.e. if this clause is ever triggered, do add uses(XXX) to the converted package. What do you think?

In the meantime, I guess we should just put ObsoleteModelica4 in the ModelicaPath as a system library and have it loaded automatically.


> Unless Per could somehow update the AST automatically when the conversion script runs? (Updating both the Modelica uses-annotation I am already updating in my script, and when another library is being added... I suppose use the package manager to set it to whatever version is compatible with the package we are converting... I could perhaps check how to query this if it helps)

**Comment by sjoelund** [comment]
> Not really, only if there are actually some ObsoleteModelica4 models in the converted library, which is quite rare. Otherwise we introduce a lot of totally bogus dependencies.

Yes, but that's sort of fine for the testing...

> Not sure what is the proper way to handle this, I guess there should be a provision for this in the specification of the conversion script, i.e. if this clause is ever triggered, do add uses(XXX) to the converted package. What do you think?

The problem is what version to add... The conversion script doesn't have this information. I think it's somewhat obvious that adding the uses is a good thing to do.

One easy way of doing this is to add the version of the loaded ObsoleteModelica4 version and failing if it isn't loaded (forcing the user to choose a version). Another would be simply querying the package manager for ObsoleteModelica4 available versions `PackageManagement.versionsThatProvideTheWanted("ObsoleteModelica4", version="", printError=true)`. It's also possible to use `annotation(uses(ObsoleteModelica4))` - this will load the latest stable release, but is not standard Modelica...

It's a bit of an annoying thing that it isn't just ObsoleteModelica(version="4.0.0") since then it could actually change if something was forgotten during the creation of the conversion script. If only the script contained some rule such as:
```
convertUses(ObsoleteModelica4, "4.0.0");
```
Then we wouldn't need to load or know anything about ObsoleteModelica4.

**Comment by perost** [comment]
The PR is now improved such that it only loads things once (previously it didn't add loaded classes to the global cache and didn't add libraries loaded due to uses-annotation to the top scope). I also added a message so that it says e.g.:
```
Notification: Automatically loaded package ObsoleteModelica4 4.0.0 due to usage.
```
when loading a package during name lookup. If it fails to find a library with the given name it will just silently fail and print the usual lookup error messages.

I should probably add a test case too, but otherwise this seems to be pretty much complete now.

**Comment by perost** [comment]
I added a test case that just uses the MSL without loading it first. It'll probably break any time we change the default MSL version, but I guess that doesn't happen often enough that it's an issue.

**Comment by casella** [comment]
I had a quick look at the latest [conversion script report](https://libraries.openmodelica.org/branches/overview-special-jobs.html). The situation is now pretty good and it makes me confident we can release this feature in version 1.19.0

There are only a handful of remaining issues.

- Five models fail in Buildings_latest after conversion, and they are more or less the same in previous versions of the same library and in derived libraries such as BuildingsSystems, IBPSA, and BuildSysPro
- Two models fail in HanserModelica
- 15 models fail in HelmholtzMedia
- most models fail in TAeZoSysPro_testsuite

@perost would you mind to check those out and report?

Thanks!

**Comment by sjoelund** [comment]
ThermoSysPro also failed a lot

**Comment by perost** [comment]
Four of the five models in Buildings fail because the conversion script is missing the rule:
```Modelica
convertElement("Modelica.Media.Interfaces.PartialCondensingGases.gasConstant", "R", "R_s")
```
I will report it once I've gone through the other libraries to check if there are more missing rules. The last one, `Buildings.Media.Examples.SteamProperties`, fails because we fail to convert `g.R` to `g.R_s` for some reason (but at least the conversion script is correct for that case).

**Comment by perost** [comment]
For the other libraries:
* HanserModelica: Seems to be same issue as the one Buildings model.
* HelmholtzMedia: Fails because it uses `Modelica.Media.Examples.Tests.Components.PartialTestModel` for which there are no conversion rules (because it's an example model and not meant for other libraries to use). So that's a library issue.
* TAeZoSysPro_testsuite: `TAeZoSysPro.Media.Air` contains:
  ```
    import SI = Modelica.SIunits;
    import Modelica.SIunits;
  ```
  which after conversion becomes:
  ```
    import SI = Modelica.Units.SI;
    import Modelica.Units.SI;
  ```
  This causes the instantiation to fail because it doesn't allow the same name to be imported multiple times in a scope. I guess we could fix this by allowing it if it's the same name being imported, but it's not a conversion issue at least.
* ThermoSysPro: Same issue as in Buildings.

**Comment by sjoelund** [comment]
> I guess we could fix this by allowing it if it's the same name being imported, but it's not a conversion issue at least.

Or you could treat it as a conversion script issue and detect if you end up with duplicate imports. You could simplify imports like `X = A.B.C.X` = `A.B.C.X` and then filtering out duplicate imports.

**Comment by perost** [comment]
Closing since it seems to be working fine now.
