### ISSUE TITLE
Model with matrix equations produces wrong results with new frontend

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7824]
See e.g. `PowerSystems.Examples.AC3ph.Elementary.Line`. The model places a T-line between two voltage sources, initializes in steady state and then adapts the phase angle of `voltage1` during transient simulation.

![Screenshot from 2021-08-30 14-35-50](https://user-images.githubusercontent.com/4224368/131373648-17a77fee-b458-4934-b57c-1e40c7f94756.png)

The line model might be special by using matrix expressions for a compact formulation of the form:
```modelica
model Tline
  extends Partials.LineBase;
  parameter Integer ne = 3 "number of line elements";
  Voltage[3, ne] v(start = transpose(fill(v_start, ne)));
  Current[3, ne + 1] i(start = transpose(fill(i_start, ne + 1)));
initial equation
  der(v) = zeros(3, ne);
  der(i) = zeros(3, ne + 1);
equation
  i[:, 1] = term_p.i;
  i[:, ne + 1] = -term_n.i;
  diagonal({C,C,C0})*der(v) + omega*C*jj(v) + G*v =
    i[:,1:ne] - i[:,2:ne+1];
  diagonal({L,L,L0})*der(i) + omega*L*jj(i) + R*i =
    [[2*(term_p.v - v[:, 1])], v[:, 1:ne - 1] - v[:, 2:ne], [2*(v[:, ne] - term_n.v)]];
end Tline
```

### Expected Behavior
The simulation succeeds with the old frontend (`-d=-newInst` -- just a bit slow), see e.g. line voltages:

![Screenshot from 2021-08-30 18-45-06](https://user-images.githubusercontent.com/4224368/131374580-f9c7f06f-fa85-4019-bdde-49f908d3a58f.png)

### Steps to Reproduce
The new frontend enables a better job in translating the model to an explicit ODE. But the simulation produces wrong results:

![Screenshot from 2021-08-30 18-52-23](https://user-images.githubusercontent.com/4224368/131375586-6d459321-4902-4c71-9f27-f4d5b9f6dc30.png)

**Comment by rfranke** [comment]
There seems to be a problem with the generation of equation systems. Here are the results of steady state initialization, setting Stop Time to 0, with old frontend and new frontend, respectively!
<div>
<img height="500" src="https://user-images.githubusercontent.com/4224368/131448043-dab59ec7-de80-4464-beb3-0baf006f88b3.png">
<img height="500" src="https://user-images.githubusercontent.com/4224368/131449306-834f20d5-a80e-4aa1-807e-739e4d0da4f3.png">
</div>

**Comment by casella** [comment]
@kabdelhak, @AnHeuermann, @phannebohm, is it possible that there is some issue with the handling of the array, e.g. rows and columns are swapped or something?

**Comment by casella** [comment]
What is most striking to me is that, after stead-state initialization, you get der(i[1,1]) = 2.8e7. That's quite large for being zero :)

@rfranke I'm not familiar with the details of the library. Does this circuit induce some constraints among the three currents due to some delta or wye connection? In that case we may have a problem with Pantelides and/or with redundant consistent initial equations not being handled properly, and that could explain why we get one derivative which is so blatantly non-zero in a stead-state condition.

**Comment by rfranke** [comment]
There should be nothing special with this example, except the matrix equations. The example just places a line model as sketched above between two voltage sources.

First I thought it would be due to wrong matrix ordering in the Cpp runtime, similar to #7820. But then it should work with the C runtime. Maybe this issue is closer to #7818.

Btw. the output of omc's `instantiateModel` is identical for old and new frontend.

**Comment by perost** [comment]
Looking at how the backend handles the initial equations I spotted an odd thing the new frontend does. It flattens the function
```Modelica
redeclare function jj  "Vectorized version of j" 
  input Real[:, :] xx "array of voltage or current vectors";
  output Real[size(xx, 1), size(xx, 2)] yy "array of rotated vectors";
algorithm
  yy := cat(1, {-xx[2, :], xx[1, :]}, zeros(size(xx, 1) - 2, size(xx, 2)));
  annotation(Inline = true); 
end jj;
```
into
```Modelica
function Line_total.line.jj "Inline before index reduction"
  input Real[:, :] xx "array of voltage or current vectors";
  output Real[size(xx, 1), size(xx, 2)] yy "array of rotated vectors";
algorithm
  yy := cat(1, {xx[2,:], xx[1,:]}, fill(0.0, size(xx, 1) - 2, size(xx, 2)));
end Line_total.line.jj;
```
Notice that `-xx[2, :]` was turned into `xx[2, :]`. I can't imagine why that would happen, but I will do some debugging. The old frontend flattens it correctly, so that could account for the difference we're seeing.

**Comment by perost** [comment]
The issue I mentioned above has been fixed in #7863. The issue was that the NF tried to expand `xx[2, :]`, and when it failed it returned only the operand instead of the whole non-expanded expression.

I think the simulation results might be even worse with that fix though, but I guess you should check yourself and see how it looks.

**Comment by rfranke** [comment]
@perost: this appears to fix the transient simulation, e.g. when starting from given initial values. That's a first achievement for this issue!

The steady-state initialization still produces the same wrong results though.

**Comment by rfranke** [comment]
The more sophisticated `PowerSystems.Examples.AC3ph.Transmission.Tline` and `PowerSystems.Examples.AC3ph.Transmission.FaultTline` work now, including also steady-state initialization, even though they add breakers and a fault on top of the simpler `PowerSystems.Examples.AC3ph.Elementary.Line` that still fails with steady-state initialization!?

 ![Screenshot from 2021-09-04 07-50-17](https://user-images.githubusercontent.com/4224368/132084220-2576a584-6fee-4fd4-b267-231d870a41fa.png)
[(from link)](https://libraries.openmodelica.org/branches/history/master/2021-09-03%2012:09:04..2021-09-03%2022:56:45.html)

**Comment by casella** [comment]
Are the simulation results correct? @rfranke, maybe you could provide reference result files, so we can also perform the verification stage.

**Comment by perost** [comment]
With the OF it seems the tearing is discarded, with `-d=tearingdump` I get several messages saying:
```
Tearing set is discarded because it is not smaller than the original set. Use +forceTearing to prevent this.
```
This seems to lead to the backend creating some Jacobians and the simulation then spends a lot of time on initialization and solving non-linear systems, but it seems the simulation is correct.

With the NF the tearing is not discarded, but then for some reason the initialization is wrong. If I turn off tearing using `--tearingMethod=noTearing` when using the NF the initialization issues seems to disappear and I get the same results as with the OF, but the simulation only takes a small fraction of the time.

The cause of the issues seems to be the two `diagonal` equations, which the OF expands a bit more than the NF. If I use the `-d=nfExpandFuncArgs` flag I also get the correct results even with the default tearing, and the simulation is again even faster.

| Frontend  | Simulation Time | Correct?
| ------------- | ------------- | ------------- |
| OF  | ~8s  | yes |
| NF | ~2s  | no |
| NF (no tearing) | 0.150s  | yes |
| NF (expand args) | 0.035s  | yes |

Turning on function argument expansion by default is not really desirable though, so I would call that a workaround rather than a fix. But I'm out of my depth at this point, so one of our backend developers probably need to have a look at this and see what's going on.

**Comment by rfranke** [comment]
Thank you for the analysis. Then it appears to be an issue with bad tearing in the backend.

**Comment by casella** [comment]
I really find it quite odd that the application of tearing can increase the simulation time by one or two orders of magnitude. Why should that be the case? Is it because of some overhead caused by inefficient code generation?

**Comment by rfranke** [comment]
For some reason OpenModelica does not identify an explicit ODE with the old frontend. This makes the simulation comparably slow.
The simulation results look good with the new frontend and `--tearingMethod=omcTearing`.
The default `--tearingMethod=cellier` appears too aggressive for the initialization problem.

**Comment by casella** [comment]
> For some reason OpenModelica does not identify an explicit ODE with the old frontend. 

@rfranke, I'm not sure what do you mean by "explicit ODE". Could you elaborate a bit?

**Comment by rfranke** [comment]
I mean that the model can be translated to the form
```
  der(x) = f(x)
```
where `f(x)` contains no algebraic loops. This only works with the new frontend and the result is correct since #7863. Just the steady-state initialization does not work with `--tearingMethod=cellier`.

**Comment by casella** [comment]
OK. 

BTW, I understand that in case explicit ODEs are obtained (i.e. all regular equations are turned into assignments) what tearing algorithm is selected is irrelevant, right?

**Comment by kabdelhak** [comment]
> BTW, I understand that in case explicit ODEs are obtained (i.e. all regular equations are turned into assignments) what tearing algorithm is selected is irrelevant, right?

Although the simulation is an explicit ODE, the initialization might still contain algebraic loops, which is the case here. Those are torn in a bad way apparently.

**Comment by casella** [comment]
OK. I'm a bit confused though, a "too aggressive" tearing may end up with a singular problem, or with convergence failure. In this case, instead, we do get a solution, though it is not the expected one.

A priori, this can only be possible in one of two cases

1. There are multiple solutions of the problem, and the sover converges to the wrong one
2. There are bugs in the equation manipulation/code generation, so that the wrong problem is solved

Since the initialization is in steady-state, obviously a solution which has a non-zero derivative is not an acceptable solution; this rules out case 1. I guess then the conclusion is that wrong torn expressions or residuals are generated. 

What I mean is that a bad choice of tearing variables is not enough to explain the behaviour, because it would either cause solver failure or end up with 1., which is not the case. There really must be something wrong in the generated code.

**Comment by casella** [comment]
@rfranke, the original problem with the frontend was fixed in #7863, that will be available in 1.19.0. I am going to close this ticket, which is way too long, and reopen a new one that focuses on the remaining issue, which is related to tearing.
