### ISSUE TITLE
Incorrect handling of algorithms with arrays by the backend

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7832]
@kabdelhak, while investigating [#6199](https://trac.openmodelica.org/OpenModelica/ticket/6199) and [#6207](https://trac.openmodelica.org/OpenModelica/ticket/6207), I stumbled upon something weird related to how algorithm sections involving arrays are handled by the backend.

I could reproduce the issue (or a related one) with a much simpler model in the context of #7815. Consider this test package:
```
package TestAlgorithmArray
  
  model EquationBased
    parameter Integer N = 2;
    parameter Real C = 1;
    parameter Real G = 1;
    Real T[N](each start = 1, each fixed = true);
    Real Ta[N], Tb[N];
    Real Qa[N], Qb[N];
  equation
    Ta[1] = 0;
    Tb[N] = 0;
    Qa[1] = 2*N*G*(Ta[1] - T[1]);
    Qb[N] = 2*N*G*(Tb[N] - T[N]);
    for i in 1:N-1 loop
      Qb[i] = N*G*(T[i+1] - T[i]);
      Qa[i+1] = -Qb[i];
      Tb[i] = (T[i+1] + T[i])/2;
      Ta[i+1] = Tb[i];
    end for;
  equation
    for i in 1:N loop
      der(T[i]) = N/C*(Qa[i] + Qb[i]);
    end for;
  end EquationBased;
  model AlgorithmBased
    parameter Integer N = 2;
    parameter Real C = 1;
    parameter Real G = 1;
    Real T[N](each start = 1, each fixed = true);
    Real Ta[N], Tb[N];
    Real Qa[N], Qb[N];
  algorithm
    Ta[1] := 0;
    Tb[N] := 0;
    Qa[1] := 2*N*G*(Ta[1] - T[1]);
    Qb[N] := 2*N*G*(Tb[N] - T[N]);
    for i in 1:N-1 loop
      Qb[i] := N*G*(T[i+1] - T[i]);
      Qa[i+1] := -Qb[i];
      Tb[i] := (T[i+1] + T[i])/2;
      Ta[i+1] := Tb[i];
    end for;
  equation
    for i in 1:N loop
      der(T[i]) = N/C*(Qa[i] + Qb[i]);
    end for;
  end AlgorithmBased;
end TestAlgorithmArray;
```
The two models should obviously be equivalent; they also give the same result in Dymola. However, for some reason, when I try to compile the AlgorithmBased model in OMC, I get
```
[1] 16:39:40 Translation Error
Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information.

[2] 16:39:40 Translation Error
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!
```
I suspect that a large number of the issues that are still plaguing the Buildings library are related to this. Can you please check?

**Comment by kabdelhak** [comment]
On first glance i see a major error. The adjacency rows for the algorithm seem to be faulty. I made an even smaller example:
```
package arr_eq_test
model eq
  Real T[2];
equation
  T[1] = 1;
  for i in 1:1 loop
    T[i+1] = T[i]*cos(time);
  end for;
end eq;

model arr
  Real T[2];
algorithm
  T[1] := 1;
  for i in 1:1 loop
    T[i+1] := T[i]*cos(time);
  end for;
end arr;

end arr_eq_test;
```
The adjacency matrix entry for the algorithm block in `arr_eq_test.arr` only shows entries for `T[1]` and not `T[2]`, it seems like the iterator `i+1` is not parsed correctly. 

Seems like a crucial error and i don't know how that one slipped by for so long. I will see if i can fix it.

**Comment by casella** [comment]
> Seems like a crucial error and i don't know how that one slipped by for so long. I will see if i can fix it.

Good that we caught it, eventually, and good that you have hopefully fixed it already. Let's see what happens with the testsuites.

**Comment by kabdelhak** [comment]
There is only one model failing, but while analyzing it i just realized that there could be something way more basic wrong here.

We talked about arrays in algorithms once and as far as i remember we came to following conclusion: If one element of an array is assigned in an algorithm, the whole array is assumed to be. Is that correct or does this only hold for initialization @casella ?

If that is the case it would be way easier to resolve these issues.

**Comment by casella** [comment]
> There is only one model failing, but while analyzing it i just realized that there could be something way more basic wrong here.
> 
> We talked about arrays in algorithms once and as far as i remember we came to following conclusion: If one element of an array is assigned in an algorithm, the whole array is assumed to be. Is that correct or does this only hold for initialization @casella ?

It is correct. Modelica Specification [Section 11.1.2](https://specification.modelica.org/maint/3.5/statements-and-algorithm-sections.html#execution-of-an-algorithm-in-a-model):
>Whenever an algorithm section is invoked, all variables appearing on the left hand side of the assignment operator := are initialized
> - A continuous-time variable is initialized with its start value (i.e. the value of the start attribute).
> - A discrete-time variable v is initialized with pre(v).
> - If at least one element of an array appears on the left hand side of the assignment operator, then the complete array is initialized in this algorithm section.


This means that any given array must be completely handled in one algorithm section. You can't have two separate algorithm sections assigning values to different elements of an array. And if you only assign one (or a few) elements of the array explicitly, all the other ones are automatically assigned their start or pre() values.

I hope this help to make things simpler.

**Comment by kabdelhak** [comment]
> > * If at least one element of an array appears on the left hand side of the assignment operator, then the complete array is initialized in this algorithm section.

This only refers to initialization right? Or does this still hold for simulation?

**Comment by kabdelhak** [comment]
This particular problem is solved with #7853 but i will wait for the regression reports if it breaks anything.

Hopefully it also fixed something for the other issues.

**Comment by casella** [comment]
> This only refers to initialization right? Or does this still hold for simulation?

I understand this always applies. There is no mention in the specification of the initialization phase. BTW, the reason why the non-discrete variables are always initialized to their start attribute also during simulation is precisely to avoid introducing some kind of "memory" that would not be appropriate, as explained in the spec.

**Comment by casella** [comment]
It passed the compiler testuite. Let's see what happens to the [library testsuite](https://libraries.openmodelica.org/branches/history/master/).

**Comment by casella** [comment]
We did get some improvements in Buildings, see [report](https://libraries.openmodelica.org/branches/history/master/2021-09-03%2012:09:04..2021-09-03%2022:56:45.html), but not in the models reported in [#6199](https://trac.openmodelica.org/OpenModelica/ticket/6199) and [6207](https://trac.openmodelica.org/OpenModelica/ticket/6207), I guess you need to dig more.

There were also some regressions in the test report, I think it's some frontend stuff, but I'm not sure.

**Comment by casella** [comment]
See comment [here](https://github.com/OpenModelica/OpenModelica/pull/7853#issuecomment-912848421)

**Comment by casella** [comment]
@kabdelhak you can use this MWE as a reference:

```
model M
  Real x[2](start = {3, 4}), y, z;
algorithm
  x[2] := y + z;
  x[2] := 2*x[2];
equation
  z = 2;
  x[2] = 10;
end M;
```
According to the Modelica Specification [Section 11.1.2](https://specification.modelica.org/maint/3.5/statements-and-algorithm-sections.html#execution-of-an-algorithm-in-a-model), I understand this is how this means.

- the algorithm assigns 3 to x[1] because of the start value rule
- the algorithm assigns x[2] to y + z, and then reassign 2*x[2] to x[2]. This means that x[2] = 2*(y+z), but the compiler shouldn't try to find an equivalent declarative formulation of the algorithm, because in general this may not even be theoretically possible (because of Turing's undecidability), so this is only between you and me :)
- so, the algorithm section is equivalent to
```
equation
  x = f(y,z);
  function f
    input Real y; // RHS variable is a input
    input Real z; // RHS variable is an input
    output Real x[2]; // LHS variable is an ouput 
  algorithm
    // same algorithm as in the model + LHS initialization
    x := {2,3};
    x[2] := y + z;
    x[2] := 2*x[2];
  end f;
```
Now comes matching. We have these equations:
```
  1.  z = 2;
  2.  x[2] = 10;
  3.  x = f(y,z);
```
so obviously the first equation is matched with `z`, the second is matched with `x[2]`, and the third is matched with whatever's left, i.e., `x[1]` and `y`. Note that in general _algorithm sections are not matched with their LHS variables_, as this example makes very clear.

Next comes causalization
```
z := 2;
x[2] := 10;
// implicit equation: unknowns are x[1] and y
res = x - f(x,y);
```
The solution is:
```
x[1] = 3;
x[2] = 10;
y = 3;
z = 2;
```
Note that y is solved "backwards", compare to the execution flow of the algorithm. No big deal, in this case, since the algorithm is linear, one Newton iteration would do, otherwise you'd need to iterate until convergence. There's no need to solve it symbolically.

I checked with Dymola, that runs `M` smoothly and produced the expected results. OMC 1.18.0 gives
```
[1] 14:31:05 Translation Error
Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled
because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information.

[2] 14:31:05 Translation Error
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!
```
I'm not sure what happens with the latest nightly, you can check that.

**Comment by phannebohm** [comment]
What about the following model:
```modelica
model M
  Real x[2](start = {3, 4}), y, z;
algorithm
  x[2] := y;
  x[2] := z;
equation
  z = 2;
  x[2] = 10;
end M;
```
As I understand, `y` can take any value. Does that make the model singular? Do we need to detect that?

**Comment by kabdelhak** [comment]
The problem with the regressions was as follows. We have a tensor variable which gets assigned in a for loop, see small example:
```

**Comment by casella** [comment]
@kabdelhak, I'm not aware of the details of how code generation works when algorithms are involved. I suspect there may be something fishy, but you need to explain to me how it works. Maybe we can set up a short meeting for that?

**Comment by casella** [comment]
@phannebohm 

> What about the following model:
> 
> ```modelica
> model M
>   Real x[2](start = {3, 4}), y, z;
> algorithm
>   x[2] := y;
>   x[2] := 5*z;
> equation
>   z = 2;
>   x[2] = 10;
> end M;
> ```
> 
> As I understand, `y` can take any value.

That's correct.

> Does that make the model singular?

Definitely.

> Do we need to detect that?

I don't think so. According to my previous comment, this model will have to be solved numerically. A Jacobian will be computed, either numerically or symbolically by means of AD, and alas it will turn out to be singular at runtime. That's none of our business, if a modeller writes implicit algorithms in models and they turn out to be singular, that's his problem 😄 

In other words, in this simple case you can tell by inspection that there is a structural singularity. However, in general algorithms can be arbitrarily complex and have unpredictable behaviour if there are iterations and conditional branches, so there's no point trying to catch these singularities at compile time. You may be able to do that in some special cases, but it's not worth spending time on this, we have a lot of higher priority work to do. The structural analysis assumes that x = f(y,z), if then function f() actually turns out to be singular at runtime, too bad.

> EDIT: The second assignment is already redundant, so this is definitely singular, right?

I'm not really sure what you mean by "the second assignment is already redundant", but anyway the model is definitely singular. In fact, I tried it with Dymola and it simulated with `y = 0`, but IMHO this is questionable, one should at least get a warning that the model is not well posed.

**Comment by phannebohm** [comment]
> > Do we need to detect that?
> 
> I don't think so. According to my previous comment, this model will have to be solved numerically. A Jacobian will be computed, either numerically or symbolically by means of AD, and alas it will turn out to be singular at runtime. That's none of our business, if a modeller writes implicit algorithms in models and they turn out to be singular, that's his problem smile
> 
> In other words, in this simple case you can tell by inspection that there is a structural singularity. However, in general algorithms can be arbitrarily complex and have unpredictable behaviour if there are iterations and conditional branches, so there's no point trying to catch these singularities at compile time. You may be able to do that in some special cases, but it's not worth spending time on this, we have a lot of higher priority work to do. The structural analysis assumes that x = f(y,z), if then function f() actually turns out to be singular at runtime, too bad.

Good point!

> > EDIT: The second assignment is already redundant, so this is definitely singular, right?
> 
> I'm not really sure what you mean by "the second assignment is already redundant", but anyway the model is definitely singular. In fact, I tried it with Dymola and it simulated with `y = 0`, but IMHO this is questionable, one should at least get a warning that the model is not well posed.

Sorry I wasn't clear. I just mean the second assignment in the algorithm block  `x[2] := 5*z;` together with the equations
```modelica
equation
  z = 2;
  x[2] = 10;
```
If they are conflicting, this would be detected at runtime because the solver can't converge. But if the equations are in agreement, as they are in this example, any value of `y` is accepted without ever iterating, which I guess happens with Dymola.
Of course this should produce a singular Jacobian in the first place, as you pointed out, and that should lead to a warning or even an error, since wild values of `y` may otherwise be used elsewhere.

**Comment by kabdelhak** [comment]
Looks like i was able to fix the FFT regressions: [regression report](https://libraries.openmodelica.org/branches/history/master/2021-09-07%2012:07:54..2021-09-07%2022:55:21.html) Not quite sure if the speedups are also my merit. 

Maybe we should still have a meeting about some general stuff @casella @phannebohm (@AnHeuermann ?).
My points to discuss are:
  - What kind of singularities do we need to detect?
  - Invertability of Algorithms
  - Behavior while solving algorithms in an algebraic Loop
  - Can we treat constant accessed and assigned array variables as scalar variables (e.g. `a[2] := `)?
     -> I suppose the answer is no due to the specification so instead: how do we deal with those without changing code gen entirely

**Comment by casella** [comment]
> > I'm not really sure what you mean by "the second assignment is already redundant", but anyway the model is definitely singular.
> 
> Sorry I wasn't clear. I just mean the second assignment in the algorithm block `x[2] := 5*z;` together with the equations
> 
> ```modelica
> equation
>   z = 2;
>   x[2] = 10;
> ```

OK, now I get it, sorry. Singular square problems can have either infinitely many solutions (with `x[2] := 5*x`) or no solution at all (e.g. with `x[2] := 4*x`). 

As a modeller, I think singular models are not well posed, even more so if they have infinitely many solutions, so they should be reported as flawed and abort the simulation. Apparently DS has other opinions.

> If they are conflicting, this would be detected at runtime because the solver can't converge. But if the equations are in agreement, as they are in this example, any value of `y` is accepted without ever iterating, which I guess happens with Dymola.

Yes. I guess they are using some generalized solver using Moore-Penrose's pseudoinverse or something like that to get a solution in that case, and I guess it's the one with minimum norm (`y = 0`). While that is fine mathematically speaking, if the mathematical model describes something real, giving me only one solution when infinitely many are possible is highly questionable.

> Of course this should produce a singular Jacobian in the first place, as you pointed out, and that should lead to a warning or even an error, since wild values of `y` may otherwise be used elsewhere.

I agree.

**Comment by casella** [comment]
Some more thoughts about the case of when statements. Simple example case:
```
algorithm
  when v > 2 then
     x := y;
  end when;
  when v < 4 then
     x := -y;
  end when;
```
How do we turn this into an equation section? One option is to define a boolean variable (or array if there are multiple conditions) for each condition, bring them out in the equation section, and substitute them with if-statements in the algorithm, e.g.:
```
equation
  $cond1 = edge(v > 2); // Triggers event when v exceeds 2
  $cond2 = edge(v < 4); // Triggers an event when v goes below 4
  x = f_alg(y, pre(x));

function f_alg
  input Real y; // RHS variable in the algorithm
  input Real $pre_y; // pre() value of LHS variable
  output Real x; // LHS variable in the algorithm
algorithm
  x := $pre_x; // Initialization, v is a discrete variable because it is assigned in a when-section
  if edge($cond1) then
     x := y;
  end when;
  if edge($cond2) then
     x := -y;
  end when;
```

**Comment by casella** [comment]
Updated version of proposal to handle algorithm sections in the NF

- For each when-statement in an algorithm section, auxiliary boolean variable definitions (or arrays in case of multiple conditions) `Boolean | Boolean[:] $cond_n = edge(<condition_n>);` are added to the variable definitions section
- For each if-statement in an algorithm section, auxiliary boolean variable definitions `Boolean $cond_n = <condition_n>` are added to the variable definitions section
-  Each algorithm section is substituted by an equation section with one function call to compute all the LHS variables
- The function has all RHS variables, pre() values of LHS variables, and event-triggering conditions as inputs, all LHS variables (or arrays) as outputs, and the same algorithm as the algorithm section, except that
  - Statements are added at the beginning of the algorithm to initialize all LHS variables to their start attributes (if continuous) or to their pre()-value (if discrete)
  - each `when <condition_n> ` statement in the original algorithm section is replaced by `if $cond_n` in the function algorithm
  - each `if <condition_n>` statement in the original algorithm is replaced by `if $cond_n` in the function algorithm
- If it is (easily!) possible to determine that the initialization value of a certain variable will be always overwritten, the initialization statements may be omitted for optimization purposes.
```
Boolean | Boolean[:] $cond1 = edge(<condition of first when statement>);
Boolean | Boolean[:] $cond2 = edge(<condition of second when statement>);
...
Boolean $cond_k = <condition of first if statement>;
Boolean $cond_k+1 = <condition of second if statement>;
...
equation
  (v1, v2, ..., vn) = f_alg_n(w1, w2, ..., wn, pre(vd1), pre(vd2), ..., $cond1, $cond2, ...)

function f_alg_n // one for each algorithm section
  input <Type> w1 "First RHS variable or array";
  input <Type> w2 "Second RHS variable or array";
  ...
  input <Type> pre_vd1 "pre-value of first discrete LHS variable"; 
  input <Type> pre_vd2 "pre-value of second discrete LHS variable"; 
  ...
  input Boolean | Boolean[:] $cond1 "First even-triggering condition";
  input Boolean | Boolean[:] $cond2 "Second event-triggering condition";
  ...
  output <Type> v1 "First LHS variable or array";
  output <Type> v2 "Second LHS variable or array;"
   ...
algorithm
  // Initialization section
  v1c := v1c.start; // First LHS continuous variable
  v2c := v2c.start; // Second LHS continuous variable
  ...
  v1d = pre_v1d; // First LHS discrete variable
  v2d = pre_v2d; // Second LHS discrete variable
  ...
  // The original algoritm section gets copied here with the following replacements:
  //   when <condition_n>  =>  if $cond_n
  //   if <condition_n>  =>  if $cond_n
end f_alg_n;
```
I guess in case the original algorithm section contains variables with dot notation, e.g. a.b.c, the variable definitions in the function algorithm should be redefined as a_b_c or something like that.

**Comment by adrpo** [comment]
I guess you would also need to pass package constants as inputs.

**Comment by casella** [comment]
> I guess you would also need to pass package constants as inputs.

In fact, the function is defined locally in the model, so it "sees" the package constants exactly as the algorithm section does. The NF just needs to constant evaluate them before transforming the algorithm in a function.

> Also functions used in the algorithm section should be visible to the created function.

Ditto.

@adrpo, in fact I understand the main consequence of your remark is that we shouldn't perform this transformation as the last step of NF or first step of BE, i.e., after flattening, but that in fact we should be perform it _before flattening_, hence in the NF. In this way, lookup of package constants and functions and whatever else is needed in the algorithm will works by construction, since the function is defined within the model that contains the algorithm section, so whatever is visible from the model is also visible from within the function. Once that has been done, standard flattening applies.

@perost, what do you think?

**Comment by phannebohm** [comment]
> Some more thoughts about the case of when statements. Simple example case:
> 
> ```
> algorithm
>   when v > 2 then
>      x := y;
>   end when;
>   when v < 4 then
>      x := -y;
>   end when;
> ```
> 
> How do we turn this into an equation section? One option is to define a boolean variable (or array if there are multiple conditions) for each condition, bring them out in the equation section, and substitute them with if-statements in the algorithm, e.g.:
> 
> ```
> equation
>   $cond1 = edge(v > 2); // Triggers event when v exceeds 2
>   $cond2 = edge(v < 4); // Triggers an event when v goes below 4
>   x = f_alg(y, pre(x), $cond1, $cond2);
> 
> function f_alg
>   input Real y; // RHS variable in the algorithm
>   input Real $pre_y; // pre() value of LHS variable
>   input Boolean $cond1; // Triggering condition of first when-statement
>   input Boolean $cond2; // Triggering condition of second when-statement
>   output Real x; // LHS variable in the algorithm
> algorithm
>   x := $pre_x; // Initialization, v is a discrete variable because it is assigned in a when-section
>   if edge($cond1) then
> ```

Why the double edge, is that on purpose? The defining equation for `$cond1` already has that.

>   ```
>       x := y;
>     end when;
>     if edge($cond2) then
>        x := -y;
>     end when;
> ```
> 
> Similar handling applies for if-statements, of course

I like the approach. But one problem I see is if you have a when condition that depends on a LHS of the algorithm:
```modelica
algorithm
  x := 2*y;
  when x > 1 then
    z : = 1;
  end when;
```
In this case it could be difficult to extract the condition. We could substitute the LHS with its RHS and continue with your approach, but that could lead to extremely long expressions. And I'm not sure if that's always possible. The part before the when statement might contain other conditional behavior.

**Comment by kabdelhak** [comment]
We have a bunch of general problems when converting algorithms to functions ([Modelica Spec v3.6-dev 12.2 ](https://specification.modelica.org/master/functions.html)):
> A function cannot contain calls to the Modelica built-in operators der, initial, terminal, sample, pre, edge, change, reinit, delay, cardinality, inStream, actualStream, to the operators of the built-in package Connections, to the operators defined in chapter 16 and chapter 17, and is not allowed to contain when-statements.

I don't know if it is really beneficial to convert algorithms to functions because there are so many special cases to handle. On the new backend branch we added Input/Output lists to the algorithm record, maybe that suffices for efficient backend analysis.

**Comment by casella** [comment]
More specifically, I checked again the three test cases that are reported as exemplary of the 52 Buildings 7.0.1 models failing in the backend:
- [Buildings.Fluid.HeatExchangers.ActiveBeams.Examples.CoolingAndHeating](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Fluid.HeatExchangers.ActiveBeams.Examples.CoolingAndHeating.err), ticket [#6207](https://trac.openmodelica.org/OpenModelica/ticket/6207)
- [Buildings.Experimental.DistrictHeatingCooling.Validation.HeatingCoolingHotWaterSmall](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Experimental.DistrictHeatingCooling.Validation.HeatingCoolingHotWaterSmall.err), ticket [#6200](https://trac.openmodelica.org/OpenModelica/ticket/6200)
- [Buildings.Experimental.DistrictHeatingCooling.Plants.Validation.Plant_Carnot_T_ClosedLoop](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Experimental.DistrictHeatingCooling.Plants.Validation.Plant_Carnot_T_ClosedLoop.err), ticket [#6199](https://trac.openmodelica.org/OpenModelica/ticket/6199)

All three cases have structural issues related to either causalization or initialization. The flattened models reveals that in all three cases there are some initial algorithms, and also some algorithms in the regular section in the first case. I guess that is no coincidence 😄 

I'm not sure if the reason why they fail is the same as in the MWE of the previous comment, i.e. that you are forcing the matching to the LHS variables of algorithms section, and that does not allow to complete the causalization/index reduction step properly, or if there is any other reason for that. However, I think it's worth exploring a fix that would make the MWE work, and see if those issues get resolved.

Let's discuss this next Monday after the devmeeting.

**Comment by casella** [comment]
Further analysis of [#6207](https://trac.openmodelica.org/OpenModelica/ticket/6207) reveals that we have the following code:
```
algorithm
  beaCooHea.conHea.mod.temDif_mod.i := 1;
  for j in 1:2 loop
    if beaCooHea.conHea.mod.temDif_mod.u > beaCooHea.conHea.mod.temDif_mod.xd[j] then
      beaCooHea.conHea.mod.temDif_mod.i := j;
    end if;
  end for;
  beaCooHea.conHea.mod.temDif_mod.y := Buildings.Utilities.Math.Functions.cubicHermiteLinearExtrapolation(beaCooHea.conHea.mod.temDif_mod.u, beaCooHea.conHea.mod.temDif_mod.xd[beaCooHea.conHea.mod.temDif_mod.i], beaCooHea.conHea.mod.temDif_mod.xd[beaCooHea.conHea.mod.temDif_mod.i + 1], beaCooHea.conHea.mod.temDif_mod.yd[beaCooHea.conHea.mod.temDif_mod.i], beaCooHea.conHea.mod.temDif_mod.yd[beaCooHea.conHea.mod.temDif_mod.i + 1], beaCooHea.conHea.mod.temDif_mod.dMonotone[beaCooHea.conHea.mod.temDif_mod.i], beaCooHea.conHea.mod.temDif_mod.dMonotone[beaCooHea.conHea.mod.temDif_mod.i + 1]);
```
so the algorithm first computes and index and then uses it to access some data in order to compute some other output. You need to scalarize variable subscripts on the RHS

**Comment by casella** [comment]
The other two test cases only have initial algorithms, but they only contain asserts, so the root cause must be different.

**Comment by casella** [comment]
Further analysis of the other two cases reveals that in both ones it involves redundant initial equations on the air side of heat exchangers, which features volumes that are directly connected to the atmosphere (fixed pressure sinks). This is particularly clear in model HeatingCoolingHotWaterSmall, where if `-d=bltdump` is turned on, a singularity involving only two equations is spotted, where the two equations are `p = p_source` and `p = p_start`.

So, it seems that #6200 is correlated to #6199, but debugging is probably much easier in #6200.

It may be that the redundant initial equation is not handled because one of the two has a parameter that may be changed at runtime. We need to check what happens if we set `Evaluate = true` or if we put some modifiers with literals on that parameter, maybe that solves the problem, in which case we should make the algorithm less picky and declare that parameter as structural in this case.

**Comment by casella** [comment]
Plan: @kabdelhak tries to fix #6207, @casella tries to see if setting p_start to constant is enough for the redundant initial equation algorithm to work.

**Comment by mpradovelasco** [comment]
Hi, I have found a similar error in this code  in OM 1.26 dev (april 8, 2025):
````Modelica
    SI.MassFlowRate mfid[ChSt_N+1, chemicals];
    SI.MassFlowRate mfilin[size(E_ChSt_linear,1)];
    SI.MassFlowRate mfisat[size(E_ChSt_MM,1)];
    SI.MassFlowRate mfiWOd[chemicals](each start = 0); 
algorithm
    for i loop
      mfiWOd[ChSt_compounds[E_ChSt_linear[i]]] := mfilin[i];
    end for;
    for i loop
      mfiWOd[ChSt_compounds[E_ChSt_MM[i]]] := mfiWOd[ChSt_compounds[E_ChSt_MM[i]]] + mfisat[i];
    end for;
````
in which the associated model says "Internal error - IndexReduction.pantelidesIndexReduction failed!". 

This is solved including an explicit equation to make zero all the mfiWOd array components, at the beginning of algorithm, which should be unnecessary since the start is properly defined.
````Modelica
algorithm
    mfiWOd := fill(0,size(mfiWOd,1));
    for i loop
      mfiWOd[ChSt_compounds[E_ChSt_linear[i]]] := mfilin[i];
    end for;
    for i loop
      mfiWOd[ChSt_compounds[E_ChSt_MM[i]]] := mfiWOd[ChSt_compounds[E_ChSt_MM[i]]] + mfisat[i];
    end for;
````

Thanks!

**Comment by casella** [comment]
@kabdelhak there was a lot of discussion on this ticket 4 years ago, then we stopped it. I understand you're focused on the new backend now, but maybe we should get this issue through, since the NB is not going to replace the OB for yet some time.

**Comment by kabdelhak** [comment]
> Hi, I have found a similar error in this code in OM 1.26 dev (april 8, 2025):

Hello! Thank you for the contribution to the ticket. Can you provide an MWE? I cannot run your code sections, most of it is undefined.

**Comment by kabdelhak** [comment]
Thank you, i was able to reduce it further:
```
  model M2
    Real mfiWOd[2](each start = 0);
    Real a = 1;
  algorithm
    mfiWOd[2] := 1;
  end M2;
```
the very basic problem is that by accessing `mfiWOd[2]` it is by modelica syntax inferred that the whole array is set inside this algorithm, therefore it should count for partitioning. The variable `a=1` is necessary because otherwise partitioning is skipped (only one equation/algorithm -> trivial partition of everything).

I will try to fix it.

**Comment by kabdelhak** [comment]
As so often, i am the culprit myself. #7875 introduced an improvement by not removing constant index accesses to arrays because FFT models exploded in run time requirements. This leads to arrays not being considered in their entirety if not each element is accessed.

I have a rather complicated solution for this, i hope i get it done this week. Sadly it does not resolve the original issue of this ticket.

For the original issue i worked out a method to correctly solve implicit algorithms (at least symbolically, as previously said it might be numerically unstable for simulation). I probably will be able to implement it in the new backend in a weeks work. Backporting that idea to the old backend might take way longer, we will see.

**Comment by casella** [comment]
@kabdelhak still working on a full solution on the NB, if this works will attempt to back-port it to the OB.

**Comment by mpradovelasco** [comment]
### Additional failure caused by indexed array assignments

I have reproduced this issue in a non-trivial physiological Modelica library using:
```text
OpenModelica v1.28.0-dev-125-g80b997969f (64-bit) (july 15 2026)
```

The affected CybSim model had previously translated and simulated correctly with earlier OpenModelica versions. It contains two instances of the same metabolism component, one in the liver and one in the gut. The relevant code has the following structure:
```modelica
protected
  SI.MassFlowRate gprod[size(ChA_mS_products, 1)](
    each start = 0)
    "Net generation of products per reaction";

algorithm
  for i in 1:size(ChA_mS_linear, 1) loop
    gprod[ChA_mS_linear[i]] :=
      gprod[ChA_mS_linear[i]] + smooth(0, /* linear term */);
  end for;

  for i in 1:size(ChA_mS_MM, 1) loop
    gprod[ChA_mS_MM[i]] :=
      gprod[ChA_mS_MM[i]] + smooth(0, /* Michaelis-Menten term */);
  end for;
```

Translation failed during structural analysis:

```text
Model is structurally singular, error found sorting equations
...
Internal error Transformation Module PFPlusExt
index Reduction Method Pantelides failed!
```

The `-d=bltdump` output identified the two algorithm sections corresponding exactly to the liver and gut instances of this component.
The problem was resolved by adding one explicit whole-array assignment before the indexed assignments:
```modelica
algorithm
  gprod := fill(0.0, size(gprod, 1));

  for i in 1:size(ChA_mS_linear, 1) loop
    gprod[ChA_mS_linear[i]] :=
      gprod[ChA_mS_linear[i]] + smooth(0, /* linear term */);
  end for;

  for i in 1:size(ChA_mS_MM, 1) loop
    gprod[ChA_mS_MM[i]] :=
      gprod[ChA_mS_MM[i]] + smooth(0, /* Michaelis-Menten term */);
  end for;
```

No model topology, equation, parameter, or physical mechanism was otherwise changed. After adding this single assignment, the model translated and simulated successfully, with process exit code `0`.

This assignment should be semantically unnecessary, since the gprod array has `each start = 0` when declared. The resulting diagnostic is particularly problematic because it reports a structural singularity in otherwise valid, previously working models.

Thanks for your effort.

**Comment by casella** [comment]
@mpradovelasco is it really necessary to write an algorithm section for this model? If you can write it equivalently as an equation section, it is so much better in terms of structural analysis and symbolic handling.

**Comment by mpradovelasco** [comment]
@casella, the algorithm runs correctly when I add ´gprod := fill(0.0, size(gprod, 1))´. Therefore, it is not a blocking issue. The design is clearer when I split the entire metabolic behavior into algorithmic and equation sections, unless it is for myself. However, I suppose it's possible to design only with the equation section.

Thanks again

**Comment by mpradovelasco** [comment]
I found a closely related real-world case in CybSim, using also:
```text
OpenModelica v1.28.0-dev-169-g7b3b89d8b2 (64-bit)
```

The issue appears in two independent blocks in CybSim library. Both blocks contain the same pattern: only a mapped subset of an internal array is assigned explicitly in an `algorithm` section. For example, the relevant code is equivalent to:

```modelica
Real tint[nR, nC](each start = 0.0);

algorithm
  // tint := fill(0.0, size(tint, 1), size(tint, 2));
  for r in 1:nR loop
    for m in 1:nMapped loop
      tint[r, mapMapped[m]] := synthesis[r, m];
    end for;
  end for;
```
Before adding an explicit whole-array assignment, OpenModelica reports:
```text
Symbolic Error
An independent subset of the model has imbalanced number of equations (1808)
and variables (1802).
```
The diagnostic lists many variables outside the blocks, which seems consistent with propagation through the structural analysis of the complete model.

According to Modelica algorithm semantics, if at least one element of an array appears on the left-hand side of `:=`, the complete array is conceptually initialized in that algorithm section, **even if the for loop is empty** (I think). Therefore, the unassigned elements should receive their `start` values here.  Adding the explicit assignment
```modelica
tint := fill(0.0, size(tint, 1), size(tint, 2));
```
solves the problem, and model then translates and simulates correctly.

Here is a self-contained MWE with three equivalent variants: 
```modelica
within ;
package AlgorithmArraySubsetMWE
  partial model Base
    parameter Integer nR = 2;
    parameter Integer nC = 2;
    parameter Integer nMapped = 1;
    parameter Integer mapMapped[nMapped] = {2};
    parameter Real synthesis[nR, nMapped] = fill(1.0, nR, nMapped);

    Real x[nR, nC](each start = 0.0, each fixed = true);
    Real tint[nR, nC](each start = 0.0);
  equation
    for r in 1:nR loop
      for c in 1:nC loop
        der(x[r, c]) = tint[r, c] - x[r, c];
      end for;
    end for;
  end Base;

  model ImplicitWholeArrayInitialization
    extends Base;
  algorithm
    for r in 1:nR loop
      for m in 1:nMapped loop
        tint[r, mapMapped[m]] := synthesis[r, m];
      end for;
    end for;
  end ImplicitWholeArrayInitialization;

  model ExplicitWholeArrayInitialization
    extends Base;
  algorithm
    tint := fill(0.0, size(tint, 1), size(tint, 2));
    for r in 1:nR loop
      for m in 1:nMapped loop
        tint[r, mapMapped[m]] := synthesis[r, m];
      end for;
    end for;
  end ExplicitWholeArrayInitialization;

  model EquationReference
    extends Base;
  equation
    for r in 1:nR loop
      tint[r, 1] = 0.0;
      tint[r, 2] = synthesis[r, 1];
    end for;
  end EquationReference;
end AlgorithmArraySubsetMWE;
```

Suggested commands:

```modelica
loadFile("AlgorithmArraySubsetMWE.mo");

checkModel(
  AlgorithmArraySubsetMWE.ImplicitWholeArrayInitialization);
getErrorString();

checkModel(
  AlgorithmArraySubsetMWE.ExplicitWholeArrayInitialization);
getErrorString();

checkModel(
  AlgorithmArraySubsetMWE.EquationReference);
getErrorString();

simulate(
  AlgorithmArraySubsetMWE.ImplicitWholeArrayInitialization,
  stopTime = 1.0);
getErrorString();

simulate(
  AlgorithmArraySubsetMWE.ExplicitWholeArrayInitialization,
  stopTime = 1.0);
getErrorString();

simulate(
  AlgorithmArraySubsetMWE.EquationReference,
  stopTime = 1.0);
getErrorString();
```

The expected language semantics are that the implicit and explicit algorithm variants are equivalent, and both are equivalent to the equation-based reference. In the affected CybSim cases, however, the explicit whole-array assignment is required to avoid the structural imbalance.

This looks closely related to original #7832, but it adds the case where an indexed algorithm assignment covers only a mapped subset and the remaining elements must obtain their conceptual initialization values.
