### ISSUE TITLE
Array interpolation method does not work anymore

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7960]
### Description
In our BRSL library we use an own interpolation method for 3D array interpolation which does not work any more since OpenModelica version 1.19

### Steps to Reproduce

Load from BRLS v2.0 RC2  the package Rexroth_Generic_Test\package.mo
Open test model Rexroth_Generic_Test.SignalBlocks.Tables.Table3D.Table3D_TC4 and start  simulation

### Expected Behavior

For the correct simulation results please see the attached picture.  The wrong results are with OMEdit are also attached

### Version and OS

 - OpenModelica Version: 1.19
 - OS: Windows 10, 64 bit
 - BRSL v2.0 RC2

### Additional Context
I will provide you the BRSL libarary to reproduce the error

**Comment by casella** [comment]
@niklwors this is strange, since the external C code that I assume you developed is not affected by OMC. I could understand if it stopped to compiler or simulate because of some broken library dependencies or compiler settings, but how could work and yet give wrong results?

**Comment by niklwors** [comment]
@casella the interpolation code is not external C code, it's Modelica code

**Comment by casella** [comment]
Ah, ok.

@niklswors, I would suggest to prepare and attach a small test case with a 2x2x2 or 3x3x2 table, to keep the number of equations low, and check if the flattened code differs between 1.18.0 and 1.19.0. That would tell us if the problem is likely due to the frontend or backend. Can you do that?

**Comment by niklwors** [comment]
@casella yes no problem

**Comment by niklwors** [comment]
@casella I tested the test model Rexroth_Generic_Test.SignalBlocks.Tables.Table3D.Table3D_TC4 with version 1.17, 1.18 and 1.19 and the flat model does not differ and also the results are the same for all versions. Therefore, unfortunately we were wrong and the problem has always existed and not only since version 1.19.

**Comment by casella** [comment]
Ouch. It seems there is something wrong in the first part of the simulation. If you can privately send an MWE as specified above, we can give a look.

**Comment by niklwors** [comment]
@casella sorry, can you tell me what a MWE is? The test model I have already uploaded, @adrpo  knows.

**Comment by sjoelund** [comment]
> @casella sorry, can you tell me what a MWE is? The test model I have already uploaded, @adrpo knows.

Minimal Working Example (non-working in this case)

**Comment by beutlich** [comment]
MWE = [SSCCE](http://sscce.org/)

**Comment by casella** [comment]
@niklwors, could you provide a simple 2x2x2 or 3x3x2 test case for debuggin?

**Comment by niklwors** [comment]
> 
> 
> @niklwors, could you provide a simple 2x2x2 or 3x3x2 test case for debuggin?

The example Rexroth_Generic_Test.SignalBlocks.Tables.Table3D.Table3D_TC4 is a small example. It needs the library Rexroth_Generic  because the 3D interpolation is implemented in it. Is the example good for you?

**Comment by casella** [comment]
@adrpo, please send me a Save Total model with a encrypted zip, so I can have a look at it myself.

**Comment by adrpo** [comment]
See the messages in Teams.

**Comment by casella** [comment]
OK, here is the MWE:
```
model TestTable3D
  Integer lowerXrow(start = 0, fixed = true);
  parameter Integer iNX = 5;
  Real xIn = 0.2*time;
  Real rowX[5] = {0, 0.25, 0.5, 0.75, 1};
algorithm  
  lowerXrow := 0 "Reset index";
  for i in 1:iNX loop
    if i == iNX or xIn < rowX[i] and not i == 1 then
      lowerXrow := i - 1;
      break;
    end if;
  end for;
annotation(
    experiment(StartTime = 0, StopTime = 3, Tolerance = 1e-6, Interval = 0.006));
end TestTable3D;
```
Until `time = 1.25`, `xIn < rowX[2]`, hence the for loop breaks at `i = 2`, ad `lowerXrow` is set at 1. 

After `time = 1.25`, `xIn > rowX[2]`, while `xIn < rowX[3]`, so the loop should break at` i = 3` and `lowerXrow` set at 2. This is what Dymola does, correctly. For some reason, instead, OMC continues returning `lowerXrow = 1` until also `xIn > rowX[3]`, at which point it returns `lowerXrow = 2`, while it should be already `lowerXrow = 3`.

@mahge, @AnHeuermann, I'm not sure if the problem here is the event handling or just the way code is generated out of the algorithm section. Can you please give a look? This bug is part of the Bosch-Rexroth issues and should be fixed ASAP.

Thanks!

**Comment by casella** [comment]
![immagine](https://user-images.githubusercontent.com/4233148/149603495-97c75731-493b-4680-89b6-c1b6e43835a8.png)
Blue `lowerXrow` is Dymola's result, red `lowerXrow` is omc.

**Comment by AnHeuermann** [comment]
`xIn < rowX[i]` get's compiled into C code to
```C
      relationhysteresis(data,
                         &tmp1,
                         (data->localData[0]->realVars[5]/* xIn variable */),
                         (&data->localData[0]->realVars[0]/* rowX[1] variable */)[i - 1],
                         0 + (i - 1)/1,
                         Less,
                         LessZC);
```
and is stored in `tmp1`.
This generated part looks correct.

In the `relationhysteresis` function we are in continuous simulation mode and return the pre-value of the corresponding relation.

So we should have a relation for each `xIn < rowX[i]` and have events every time one of these relation changes.
I'll check them next.

**Comment by AnHeuermann** [comment]
We do find a state event at `time=1.24999999938` and update the relations:
```
relations[1] = xIn < rowX[2]
```
but `relation2` is still `true` at this time. The next time the relations are updated is at the next event location (again found a tiny bit to early).

I tried to change the bisection method to always return a solution greater then the root, but this didn't solve the problem.

**Comment by AnHeuermann** [comment]
I found the problem 🎉 
Our generated code isn't correct:

```C
  tmp1 = LessZC((data->localData[0]->realVars[5]/* xIn variable */) , (data->localData[0]->realVars[0]/* rowX[1] variable */) , data->simulationInfo->storedRelations[0]);
  gout[0] = (((((modelica_integer) 1) == ((modelica_integer) 5)) || (tmp1 && (!(((modelica_integer) 1) == ((modelica_integer) 1)))))) ? 1 : -1;
  tmp4 = LessZC((data->localData[0]->realVars[5]/* xIn variable */) , (data->localData[0]->realVars[1]/* rowX[2] variable */) , data->simulationInfo->storedRelations[0]);
  gout[1] = (((((modelica_integer) 2) == ((modelica_integer) 5)) || (tmp4 && (!(((modelica_integer) 2) == ((modelica_integer) 1)))))) ? 1 : -1;
  tmp7 = LessZC((data->localData[0]->realVars[5]/* xIn variable */) , (data->localData[0]->realVars[2]/* rowX[3] variable */) , data->simulationInfo->storedRelations[0]);
  gout[2] = (((((modelica_integer) 3) == ((modelica_integer) 5)) || (tmp7 && (!(((modelica_integer) 3) == ((modelica_integer) 1)))))) ? 1 : -1;
  tmp10 = LessZC((data->localData[0]->realVars[5]/* xIn variable */) , (data->localData[0]->realVars[3]/* rowX[4] variable */) , data->simulationInfo->storedRelations[0]);
  gout[3] = (((((modelica_integer) 4) == ((modelica_integer) 5)) || (tmp10 && (!(((modelica_integer) 4) == ((modelica_integer) 1)))))) ? 1 : -1;
  tmp13 = LessZC((data->localData[0]->realVars[5]/* xIn variable */) , (data->localData[0]->realVars[4]/* rowX[5] variable */) , data->simulationInfo->storedRelations[0]);
  gout[4] = (((((modelica_integer) 5) == ((modelica_integer) 5)) || (tmp13 && (!(((modelica_integer) 5) == ((modelica_integer) 1)))))) ? 1 : -1;
```

We should have a `storedRelations` for each relation.
When fixing the indices of `data->simulationInfo->storedRelations[]` to be `0, 1, 2, 3, 4` the simulation is working.

![image](https://user-images.githubusercontent.com/38031952/160813798-e005d1ce-2893-418c-bda7-88d7db8fea16.png)

**Comment by AnHeuermann** [comment]
After a long debug session with @kabdelhak we came to the conclusion that the error is somewhere deep in the backend.
Fixing it is by no means trivial and the best approach would to re-write the zero-crossing generation. And because the new backend is making progress it would be better to include the changes there.

But there is a workaround available.
When replacing the relation from the if condition and replacing it with a Boolean variable the results are looking correct.

So instead of 
```modelica
  for i in 1:iNX loop
    if i == iNX or xIn < rowX[i] and not i == 1 then
      lowerXrow := i - 1;
      break;
    end if;
  end for;
```

writing

```modelica
Boolean b;
[...]
  for i in 1:iNX loop
    b := xIn < rowX[i];
    if i == iNX or b and not i == 1 then
      lowerXrow := i - 1;
      break;
    end if;
  end for;
```

should work.

@niklwors Is is feasible to change your for loops in the BRSL library?

**Comment by AnHeuermann** [comment]
We should keep the ticket open. The underlying problem in the backend is not fixed.
Maybe @kabdelhak can include it in the new backend.
