### ISSUE TITLE
The Linux package of OMSimulator seems to be missing OMSimulatorServer.py

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8163]
@dietmarw reports [here](https://github.com/OpenModelica/OpenModelica/issues/8160#issuecomment-971825804) that OMSimulatorServer.py is probably missing in the Linux installation, because he gets
```
/usr/bin/../bin/OMSimulatorPython3 /usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py --model=/tmp/OpenModelica_dietmarw/OMEdit//Test.ssp --endpoint-pub=tcp://127.0.0.1:41821 --logLevel=0 --option "--suppressPath=true"
python3: can't open file '/usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py': [Errno 2] No such file or directory
Simulation process failed. Exited with code 2.   
```

@dietmarw, could you please specify how do you reproduce this error exactly? Thanks!

**Comment by sjoelund** [comment]
Should be resolved by https://github.com/OpenModelica/OpenModelicaBuildScripts/commit/511848fd651f0b39d878a935fa7c13e18cd0ed2a

**Comment by casella** [comment]
Good! @dietmarw please confirm that you can now run what you wanted to.

**Comment by dietmarw** [comment]
Not quite yet, lets see if #8173 fixes it.

**Comment by dietmarw** [comment]
@sjoelund  `OMSimulatorServer.py` is present now but its dependencies are missing:

```
/usr/bin/../bin/OMSimulatorPython3 /usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py --model=/tmp/OpenModelica_dietmarw/OMEdit//test.ssp --endpoint-pub=tcp://127.0.0.1:39007 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "/usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py", line 12, in <module>
    import OMSimulator as oms
  File "/usr/lib/OMSimulator/__init__.py", line 17, in <module>
    Scope._init()
  File "/usr/lib/OMSimulator/Scope.py", line 5, in _init
    _capi = capi()
  File "/usr/lib/OMSimulator/capi.py", line 11, in __init__
    self.obj=ctypes.CDLL(omslib)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/OMSimulator/x86_64-linux-gnu/omc/libOMSimulator.so: cannot open shared object file: No such file or directory
Simulation process failed. Exited with code 1.
```

**Comment by dietmarw** [comment]
BTW, would  it not be good to reopen this ticket? Unfortunately I can't.

**Comment by sjoelund** [comment]
Do you have package `libomsimulator` installed?

**Comment by dietmarw** [comment]
Yes.

**Comment by dietmarw** [comment]
```
$ locate libOMSimulator
/usr/lib/x86_64-linux-gnu/omc/libOMSimulator.a
/usr/lib/x86_64-linux-gnu/omc/libOMSimulator.so
/usr/lib/x86_64-linux-gnu/omc/libOMSimulatorLua.a
```

**Comment by sjoelund** [comment]
@lochel do you know why libOMSimulator.so is installed into 2 different places in `OpenModelica/build`? We only install one of them in the Debian/Ubuntu packages

**Comment by lochel** [comment]
No, I don't know. Might be related to the windows installer?

**Comment by sjoelund** [comment]
Which one should it be? `build/lib/OMSimulator/x86_64-linux-gnu` or `build/lib/x86_64-linux-gnu`?

**Comment by lochel** [comment]
I really don't know

**Comment by sjoelund** [comment]
I suppose we could create a symbolic link on Linux so they both exist

**Comment by dietmarw** [comment]
Any updates on this?

**Comment by casella** [comment]
I added this to the 1.19.0 release plan so we don't forget about it. @lochel @sjoelund I'm not sure who's ultimately responsible for this kind of things, I'm adding @adrpo to the loop, please make sure this is resolved.

Thanks!

**Comment by casella** [comment]
Adding @adeas31 to the loop, since the problem seems to be originated from OMEdit

**Comment by sjoelund** [comment]
From the dev meeting. Fix this in 2 places:
* Make sure the build/ directory only has libOMSimulator.so installed into `1` directory
* As a work-around until this is found, make the Python-script look in both locations before failing

**Comment by sjoelund** [comment]
See also https://github.com/OpenModelica/OMSimulator/issues/947

**Comment by dietmarw** [comment]
Any update on this, OMSimulator still fails with the latest nightly: OpenModelica 1.19.0~dev-564-g9489298

**Comment by casella** [comment]
> From the dev meeting. Fix this in 2 places:
> 
>     * Make sure the build/ directory only has libOMSimulator.so installed into `1` directory
> 
>     * As a work-around until this is found, make the Python-script look in both locations before failing

@arun3688, @lochel, any chance of fixing this by the end of this week in time for 1.19.0-beta.1?

Thanks!

**Comment by lochel** [comment]
I don't know how we build the Linux packages. @sjoelund can you help out?

**Comment by casella** [comment]
@adrpo can you also give a look?

**Comment by adrpo** [comment]
Tested this on my WSL by modifying the installed /usr/lib/OMSimulator/capi.py with the modifications from: https://github.com/OpenModelica/OMSimulator/pull/1156/commits/c2b5c446ef8f4510f12f197d2ea7c553c6e14338.
We will close this when we update the OMSimulator submodule in the OpenModelica project.
