### ISSUE TITLE
FMU export options "none", "dynamic", "static" are broken. 

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#8168]
In "Tools -> Options -> FMI" one can choose the type of "none", "dynamic", "static". The problem is they all do the same, generate a ''static" FMU no matter what. 
So either the options should be taken away or they should be fixed. 

The documentation also mentions "with [dynamically|statically] linked runtime for current platform." But what does this mean when one has chosen several target platforms. Will the win64 target include a link to some OMC win library even if compiled on a linux machine? This should be clarified. 

### Version
OpenModelica 1.19.0~dev-388-gb35aa9c on Ubuntu Linux 20.04

**Comment by casella** [comment]
This should also be fixed for the 1.19.0 release, it's not good to have options that don't work.

@dietmarw are you working on Linux or Windows? This is not clear from your report.

**Comment by dietmarw** [comment]
I've updated the ticket though it is not really of relevance since this should work on windows and linux ;-)

**Comment by adeas31** [comment]
Perhaps @AnHeuermann can help with this.

**Comment by casella** [comment]
Or @lochel

**Comment by AnHeuermann** [comment]
Some years ago I worked on that a tiny bit, but eventually I gave up.
It was not clear to me what should be the difference between static/dynamic or some OS-tripple.
And getting FMUs to compile on system `A` to work on system `B`, where `A` and `B` could be any combination from `{Windows, Any Linux, OSX} x {x32, x64}` is a nightmare. 

Since we abounded OSX it got a bit easier. But now we want to support CVODE (SUNDIALS) in FMUs as well, so it's more complicated again.

Let's start with an example. I don't know what OMEdit will make of it, so I'm using the scripting API.
Let's use Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum for now, all generated from an Ubuntu 20.04.

## Static platform

```modelica
loadModel(Modelica, {"4.0.0"}); getErrorString();
buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum, version="2.0", fmuType="me_cs", platforms= {"static"}); getErrorString();
```
We get
```bash
$ ls static_FMU/binaries/linux64/
Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so
Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum_FMU.libs
```

Here we have a static lib and a dynamic lib. The later on needs
```bash
$ readelf -d static_FMU/binaries/linux64/Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 ```
 
The omc C runtime is somewhere in the static library.
If you want to transfer this FMU to a system without the shared libs above it won't work.

## Dynamic platform

```modelica
loadModel(Modelica, {"4.0.0"}); getErrorString();
buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum, version="2.0", fmuType="me_cs", platforms= {"dynamic"}); getErrorString();
```

Again we get
```bash
$ ls dynamic_FMU/binaries/linux64/
Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so  Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum_FMU.libs
```

and using the elf reader
```bash
$ readelf -d dynamic_FMU/binaries/linux64/Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libSimulationRuntimeC.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libomcgc.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

So the omc C runtime is dynamically linked. Same for lapack and blas and the omc garbage collector.


## Dynamically and static platform

I have no clue what I would expect for this case.

```bash
$ ls static_dynamic_FMU/binaries/linux64/
Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so  Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum_FMU.libs
```

```bash
$ readelf -d static_dynamic_FMU/binaries/linux64/Modelica_Mechanics_MultiBody_Examples_Elementary_Pendulum.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libSimulationRuntimeC.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libomcgc.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

Looks like this is basically the dynamic platform. Doesn't make much sense to use dynamic and static at the same time.

----------------

## Conclusion

Dynamic and static seems to work. But we always need some static and dynamic libs, it is only different where the omc runtime libs are actually compiled to.

`platforms={"dynamic", "static"}` doesn't make sense. We should issue a warning.

And now we could do the same on Windows. And I bet it will be somewhat different. But not today any more.

**Comment by dietmarw** [comment]
OK doing the same test when using the OMEdit interface I get: 
```
$ readelf -d  static_FMU/binaries/linux64/TestFMU.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
$ readelf -d  dynamic_FMU/binaries/linux64/TestFMU.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

So looks like the "dynamic" setting simply does not work in OMEdit (as reported in this ticket ;-) )

As for cross-compilation, when on linux there is no need to use docker as long as one has the mingw packages installed.

**Comment by adrpo** [comment]
AFAIK, in Windows we always compile the FMUs static no matter what you choose in OMEdit.

**Comment by dietmarw** [comment]
So just to recap. 
 | option | current action |  proposed fix |
| --- | --- | --- | 
| none | creates static FMU | remove? |
| dynamic | creates static FMU | fix to dynamic |
| static | creates static FMU | working as it should |

So the dynamic option makes **only** sense for Linux targets and then the question is is there any practical value in having dynamic Linux FMU available. If not, then the whole drop-down list of option could be removed and FMUs would be generated **always** as static, independent of the target OS.

**Comment by adrpo** [comment]
I think the only one we should get rid of is "none", I don't know why we have that. Maybe @sjoelund remembers.

**Comment by sjoelund** [comment]
Pure source-code FMUs

**Comment by dietmarw** [comment]
So maybe rename "none" to "source-code only" and at the same time deactivate the platform checkboxes if that option is chosen?
If you keep dynamic then you also need to add some logic/info that it does not effect the windows targets. 
Possibly change it to:

| option | current action |  proposed fix |
| --- | --- | --- | 
| none | creates static FMU | new name: "source-code only", deactivate platform selection  |
| dynamic | creates static FMU | fix the dynamic generation for Linux and Windows or only Linux and change option name to "dynamic (Linux only)" and deactivate possible windows targets |
| static | creates static FMU | working as it should |

**Comment by sjoelund** [comment]
> So the dynamic option makes only sense for Linux targets and then the question is is there any practical value in having dynamic Linux FMU available

I think that the original idea was to have the different solvers available for the dynamic version (if you link everything to the OM environment, you have access to them). If we do include sundials sources/etc and create a nice statically linked package for more solvers, there's no point in having it except it linked slightly faster.

**Comment by AnHeuermann** [comment]
> As for cross-compilation, when on linux there is no need to use docker as long as one has the mingw packages installed.

I wouldn't agree. It is easy to use a docker container with some very old compilers to cross-compile for some older Linux OS, but nearly impossible to install them in your OS because they are no longer compatible.

**Comment by dietmarw** [comment]
Right, I was only thinking of the Windows targets.

**Comment by adeas31** [comment]
So if I take forward @dietmarw proposal we can have for Windows,

| option | current action |  proposed fix |
| --- | --- | --- | 
| none | creates static FMU | new name: "source-code only", deactivate platform selection, make it to export source-code only  |
| static | creates static FMU | working as it should |

And for Linux the same 2 options as listed above and,

| option | current action |  proposed fix |
| --- | --- | --- | 
| dynamic | creates dynamic FMU | working as it should on Linux |

@dietmarw you wrote "fix the dynamic generation for Linux" but what I understood from @AnHeuermann comment that it is working fine on Linux. Or did I miss something?

**Comment by dietmarw** [comment]
>  @dietmarw you wrote "fix the dynamic generation for Linux" but what I understood from @AnHeuermann comment that it is working fine on Linux. Or did I miss something?

It works if you trigger it from the command line but this ticket is about OMEdit and there the options don't work.

**Comment by AnHeuermann** [comment]
> So looks like the "dynamic" setting simply does not work in OMEdit (as reported in this ticket ;-) )

I can't reproduce the problem in OMEdit. Maybe because I'm using my self build OMEdit or have some other FMI settings in OMEdit or have other stuff installed in my Ubuntu.

![image](https://user-images.githubusercontent.com/38031952/143222006-f417f715-4624-42f0-b16c-7b3164ef9fcf.png)

```bash
/tmp/OpenModelica_andreas/OMEdit/Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum/Pendulum_FMU/binaries/linux64$ readelf -d Modelica_Mecha
nics_MultiBody_Examples_Elementary_Pendulum.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libSimulationRuntimeC.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libomcgc.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```


@dietmarw If I understand https://github.com/OpenModelica/OpenModelica/issues/8168#issuecomment-977745251 correctly this should give you the "correct" linking?
```
loadModel(Modelica, {"4.0.0"}); getErrorString();

setCommandLineOptions("--fmiFlags=s:cvode"); getErrorString();
setCommandLineOptions("--fmiFilter=internal"); getErrorString();
setCommandLineOptions("--fmiSources=true"); getErrorString();

buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum, version="2.0", fmuType="me_cs", platforms= {"dynamic"}); getErrorString();
```

**Comment by dietmarw** [comment]
So I just did double checked. Dynamic only works when running the commands in OMShell. Not when triggered from inside OMEdit.

**Comment by adeas31** [comment]
That is weird. What commands you run in OMShell? Please also attach your `omeditcommunication.log`?

**Comment by dietmarw** [comment]
I run the exact same commands that @AnHeuermann  listed. I could not find any `omeditcommunication.log` file to be created but I can attach the FMU file which contains plenty of other logs that might help (renamed to .zip so it can be uploaded here):
[Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.zip](https://github.com/OpenModelica/OpenModelica/files/7596440/Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum.zip)

**Comment by adeas31** [comment]
`omeditcommunication.log` is in %TEMP%/OpenModelica/OMEdit

**Comment by dietmarw** [comment]
Needed to restart OMEdit for it to get created. So here it is:
[omeditcommunication.log.zip](https://github.com/OpenModelica/OpenModelica/files/7596490/omeditcommunication.log.zip)

**Comment by adeas31** [comment]
OMEdit is calling,

```
setCommandLineOptions("--fmiFlags=s:cvode")
setCommandLineOptions("--fmiFilter=internal")
setCommandLineOptions("--fmiSources=true")
buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum,"2.0","me_cs","<default>",{"dynamic","x86_64-linux-gnu"},false)
```

That is same what you are calling from OMShell except that it has `x86_64-linux-gnu` in the platforms. So I am not sure what is the real problem.

**Comment by dietmarw** [comment]
Well maybe exactly that, I.e., calling with several platforms overrides the "dynamic" argument. This brings me back to what the meaning of a dynamic FMU is when several targets are chosen (also including cross platform targets).

**Comment by dietmarw** [comment]
Yes that's it! So if you choose "dynamic" in the settings then you can NOT chose any target platform. That basically overrides the "dynamic" and makes the FMU static for the chosen platform. I could now create a dynamic FMU by simply not selecting ANY platform. 

Possible solution for "dynamic":
If "dynamic" is chosen then the platform choices should get disabled. Also add documentation that dynamic compilation is (at least on linux) only possible for the platform OMEdit is running on.

**Comment by dietmarw** [comment]
### Summary/recap again:
| option | current action |  proposed fix |
| --- | --- | --- | 
| none | creates static FMU | new name: "source-code only", deactivate platform selection, make it to export source-code only  |
| dynamic | creates static FMU (if also a platform is selected) | fix the dynamic generation for Linux and Windows or only Linux and change option name to "dynamic (Linux only)" or "dynamic (current native platform only)" and deactivate platform selection |
| static | creates static FMU | working as it should |

### Still open question: 
- What happens when no platform is selected? Currently it then uses the current native platform. If that is the desired outcome it should be documented.

**Comment by adeas31** [comment]
@dietmarw I had a discussion with @AnHeuermann and @sjoelund today and we came up with this,

![image](https://user-images.githubusercontent.com/4007231/144249800-78710a51-7f3f-426f-9bbc-73c940d7d651.png)

So you don't see any dropdown list now just the flat list of platforms. The `native` is always `static`. Also added list of docker targets. Some platforms will be picked up from the PATH and you see `(auto-detected)` in their name. Then there is a text box where one can add additional platforms as a comma separated list.

**Comment by dietmarw** [comment]
Some comments/questions: 
 1. It would be good to specify/document a bit more detailed what is meant by "native".
 2. Is dynamic now completely off the table?
 3. The docker images seem to be out of date, so where I could previously compile locally with my installed nightly build, with docker I'm restricted to some old released versions?
 4. Same about the cross-compile options. As of now I can compile them independent on the docker image. This option would not be available any more.

Now, there might be some drawbacks using the local version vs using docker generated versions. If yes, what are those and if not, why restrict the generation on docker.

**Comment by adeas31** [comment]
Docker is just another option. You can still compile independent of docker.

**Comment by adeas31** [comment]
> It would be good to specify/document a bit more detailed what is meant by "native".

Sure. Any suggestion what would be better description for it from a user point of view? I am thinking to write in the user's guide `By default a native FMU statically linked with the runtime for the current user platform is generated.`

> Is dynamic now completely off the table?

No. But is more confusing so we decided to keep it hidden for advanced users. You can write `dynamic` in the textbox for additional platforms. However, the dynamic option has issues when combined with other platforms and that is probably a bug we should address in some other ticket.

**Comment by dietmarw** [comment]
Just tested it. Would be nice to have the native documentation appear in a tool tip on the native option in addition to the documentation.

Also something is still bothering me. Choosing `native` **and** `x86_64` on my Ubuntu 20.04 64bit machine will actually create a different FMU to when just choose `native` only. But it should be the same or am I missing something?

Here the two variants: 
[FMUtests.SinSource_native_x86_64.fmu.zip](https://github.com/OpenModelica/OpenModelica/files/7647604/FMUtests.SinSource_native_x86_64.fmu.zip)
[FMUtests.SinSource_native.fmu.zip](https://github.com/OpenModelica/OpenModelica/files/7647605/FMUtests.SinSource_native.fmu.zip)

Just choosing `x86_64` creates the same as `native` **and** `x86_64`.

**Comment by dietmarw** [comment]
OK ´native` is still creating a dynamic FMU:
```
/tmp/a$ readelf -d both/FMUtests_SinSource.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
/tmp/a$ readelf -d native/FMUtests_SinSource.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsundials_cvode.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libsundials_nvecserial.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

**Comment by sjoelund** [comment]
Choosing `x86_64` is different from the static target. Static will link an already compiled version of the runtime whereas `x86_64` will take (possibly a subset of the source files) and compile them for the given architecture. Selecting both should result in a late error since both try to write to the same target, but I guess that's not been coded into OpenModelica.

**Comment by dietmarw** [comment]
But there is no "static" target option. As far as I understood, all target listed should be static. Hence choosing `native` should be identical to `x86_64` in my machine. Otherwise what else is the meaning of `native` if not that?

I did find even more issues when trying to replicate #8233. Choosing `x86_64` only as target the FMU has theses dependencies: 

```
$ readelf -d SpeedProfile.so | grep 'NEEDED'
 0x0000000000000001 (NEEDED)             Shared library: [libModelicaStandardTables.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libModelicaIO.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

**Comment by casella** [comment]
One problem could be that CVODE can be used inside an FMU, but then CVODE is dynamically linked, which conflicts with static linking.

Adding @AnHeuermann to the loop.

**Comment by casella** [comment]
@dietmarw this ticket is now slightly oversized, it's hard to figure out what was fixed and what still isn't.

Would you mind opening a new one focusing on what still doesn't work for you so we can close this one and restart on a clean basis?

Thanks!

**Comment by dietmarw** [comment]
I rather continue here where all information is still available in one place. Open issues are still:
 1. `Native`  should be identical to choosing the current platform (`x86_64` in my case) and if this is not the case it should be documented what `native` then means.
 2. The FMUs are still created dynamically and not statically which will course issues when exchanged (which is the whole point purpose of FMUs)
 3. If CVODE option causes the dynamic link problem then this should be documented in the dialogue. Also clarifying if the FMU then will "only" depend on CVODE libs present or which other libs need to be present in order to run that FMU.

**Comment by casella** [comment]
@dietmarw, I think some of these last three issues may have been solved in the meantime. Would you mind to check? Thanks!

**Comment by dietmarw** [comment]
I did some more tests with the latest `OpenModelica 1.19.0~dev-778-g9596bfc`

 1. `Native` vs selecting the platform that my machine is running on `(x86_64-linux-gnu (autodetected)`: 
    - Here it is still not clear an neither documented what native vs platform means. The generated FMUs differ in:
        -  size
        - GLIBC dependencies
     - ''Verdict:** I consider this still as  **not fixed**.
  2. Dynamic vs Static:
     - indpendent on `native` or "platform" the FMUs still depend on:
        -  Shared library: [libm.so.6]
        -  Shared library: [libpthread.so.0]
        - Shared library: [libc.so.6]
      - **Verdict**: I'm not sure if this can be considered as static with those dependencies still present
 3. see 2.

**Comment by casella** [comment]
@mahge, @AnHeuermann any ideas on how to accomplish this?

**Comment by AnHeuermann** [comment]
I'm not sure what the problem is we want to solve in this ticket.

> I rather continue here where all information is still available in one place. Open issues are still:
> 
> 1. `Native`  should be identical to choosing the current platform (`x86_64` in my case) and if this is not the case it should be documented what `native` then means.
> 2. The FMUs are still created dynamically and not statically which will course issues when exchanged (which is the whole point purpose of FMUs)
> 3. If CVODE option causes the dynamic link problem then this should be documented in the dialogue. Also clarifying if the FMU then will "only" depend on CVODE libs present or which other libs need to be present in order to run that FMU.

I guess we should open issues for each of these points and discuss them separately and close this issue. This issue did go a bit haywire.

Our compile process of FMUs is not very straight forward and therefore it is hard to figure out what we are actually doing. Maybe @mahge and myself could spend some time to improve CMake FMUs to address these issues and get clear source-code FMUs that are only static or dynamic linked.

We should use https://github.com/OpenModelica/OpenModelica/projects/6 to prioritize the issues.
But currently I have to focus on other tasks, so I don't think we can do this for the 1.19 release.

**Comment by casella** [comment]
I agree it's too late to get this into 1.19.0, since we'll branch off tomorrow. 1.20.0 is more like it.

@AnHeuermann would you mind opening the three separate tickets and mention them here? Thanks!

**Comment by AnHeuermann** [comment]
>2. Dynamic vs Static:
> - indpendent on native or "platform" the FMUs still depend on:
> Shared library: [libm.so.6]
>  Shared library: [libpthread.so.0]
>  Shared library: [libc.so.6]

@dietmarw Did you encounter a compatibility problem with this dynamic linked system libraries?

Until there is an issue I wouldn't change the way we link these libraries.

**Comment by dietmarw** [comment]
@AnHeuermann  No not an issue as such just a question as to what OM regards as static since clearly there is still some dependency which might be important to know, i.e., should be documented.

**Comment by casella** [comment]
I agree, if there are some shared libraries that are expected to be found on _every_ system, there's no point in statically linking them; I also agree this should be properly documented.

And, I hate dll hell :)

**Comment by dietmarw** [comment]
Revisiting this ticket, the main issues seem to be fixed:
 1. "native" now produces the same binary as the platform ("x86_64-linux-gnu" in my case.
 2. The dynamic/static part has been removed from the settings page so it no longer confuses here. #8842 will hopefully take care of the details connected to what dynamic or static actually means.
 3. Since there is no longer a dynamic/static box to tick, the  CVODE option no longer conflicts with such a setting (but still has other issues).

So closing this here for 1.21.
