### ISSUE TITLE
Constant values not shown when time is negative

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8799]
### Description
I thought I had posted this yesterday, but I cannot find it anymore

Constant-valued plots are not shown by OMEdit when time is negative
### Steps to Reproduce
Run this piece of code:
`model TestBug5
  parameter Real p=1;
  Real t=time;
equation
  annotation(experiment(StartTime = -1, StopTime = 0));
end TestBug5;`

variable t is plotted correctly, p is not.

### Expected Behavior
Plots should be shown also when time is negative

### Screenshots
![image](https://user-images.githubusercontent.com/37046832/161385075-f362f73b-4971-4ed1-b786-3b7c359a2be6.png)

### Version and OS
OM 1.18.0 64 bit, win11

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by perost** [comment]
You did report it yesterday, see #8796, but that issue was closed since it seems the issue is already fixed in newer versions of OM. Please continue the discussion in that ticket instead if you find that the issue is not in fact already fixed.

**Comment by perost** [comment]
Sorry, it seems I mistook your reports since they're rather similar, but this one seems to be different to #8796.

**Comment by casella** [comment]
@max-privato, @adeas31 made lots of improvements to plotting in 1.19.0, please always check the nightly build for all such issues.

Thanks!

**Comment by max-privato** [comment]
Just checked.
The issue is still there with today's nightly.

My fault was that yesterday, while progressively simplifying the test case I had, to create a MWE, I simpliifed it too much :-)

**Comment by casella** [comment]
Confirmed. @adeas31 can you please have a look?
