### ISSUE TITLE
PDEModelica1 Example not working

### ISSUE THREAD

**Issue by 12Tall** [OpenModelica/OpenModelica#9388]
### Description
When I am trying to run the following example mode on <https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/pdemodelica.html>, the OMEditor shows an error `Modified element domain not found in class Real.`  

```modelica 
model Advection "advection equation"
  parameter Real pi = Modelica.Constants.pi;
  parameter DomainLineSegment1D omega(L = 1, N = 100)  "domain";
  field Real u(domain = omega)                         "field";  //  `Modified element domain not found in class Real.` 
initial equation
  u = sin(2*pi*omega.x)                                "IC";
equation
  der(u) + pder(u,x) = 0   indomain omega              "PDE";
  u = 0                    indomain omega.left         "BC";
  u = extrapolateField(u)  indomain omega.right        "extrapolation";
end Advection;
```
### Version and OS

 - OpenModelica Version: 1.19.2 (64-bit)
 - OS: Windows 11, 64 bit

EDIT: After I updated Openmodelica to `OpenModelica v1.20.0-dev-281-gcc5bdc84ed (64-bit)`, the error is chaged to `Modified element unit not found in class Integer.`

Is there any further configuration I should do? 
Thanks :)

**Comment by 12Tall** [comment]
Seems it was caused by the new frontend code generator, after I enabled the old option. the code can be compiled and executed well  
![image](https://user-images.githubusercontent.com/29416757/190919142-419669d3-b37d-4bb9-ae1f-9428ac9bfe2f.png)

**Comment by casella** [comment]
@12Tall thanks for the report!

@perost would you mind fixing the NF so that we still support this PDEModelica example?

**Comment by casella** [comment]
OK, then, given the experimental status of PDEModelica, I guess using the old frontend is fine for the time being. I don't think one would use any sophisticated model that really needs the NF to work in that context.

I had a quick look to the user's guide: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/pdemodelica.html and I see that in order to use PDEModelica one needs to set `--grammar=PDEModelica`. @perost, could you just fix it, so that it automatically enables the OF as well?

**Comment by perost** [comment]
> I had a quick look to the user's guide: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/pdemodelica.html and I see that in order to use PDEModelica one needs to set `--grammar=PDEModelica`. @perost, could you just fix it, so that it automatically enables the OF as well?

Done in #9396.

**Comment by casella** [comment]
Thanks @perost!

@12Tall, @perost's fix should is already available in the latest nightly build. Please check that you can run your experiments without explicitly activating the new backend. If something still doesn't work, please reported here.

**Comment by 12Tall** [comment]
Hello @casella , @perost ,  
Thanks a lot for your great work. I'll check and let you know if it works well. 👍

**Comment by 12Tall** [comment]
Hello @casella , 
I tested the latest nightly build, it works great. Thank you :)
