### ISSUE TITLE
OMEdit crashes upon opening parameter window of a Buildings model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9461]
@mwetter reports:

> Bug Description :
> Connected to OpenModelica 1.20.0~dev-319-gbd71b95 built for Ubuntu 20.04.5 LTS.
> The running OS is Ubuntu 20.04.5 LTS on x86_64.
> 
> Opened Buildings Library (commit e1aa85392941766c68b3651c5e38913008235182)
> Opened model Plants.Cooling.Examples.ElectricChillerParallel
> Checked model.
> Opened instance "pla".
> Double-clicked on instance "perCWPum".
> OMEdit crashed.

@adeas31 could you please check? Maybe this will be fixed with #8425 anyway, but it would be good to avoid OMEdit 1.20.0 to crash anyway.

Thanks!

**Comment by adeas31** [comment]
It works fine for me.

- Cloned https://github.com/lbl-srg/modelica-buildings/tree/master
- Checked out branch `issue2668_fanEfficiencyEuler`. That's where the commit `e1aa85392941766c68b3651c5e38913008235182` is done.
- Opened model `Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel`
- Checked model. It fails with error,
```
[1] 12:21:06 Translation Error
[Buildings.Fluid.Movers.BaseClasses.Characteristics.efficiencyParameters_yMot: 5:3-6:45]: [Could not evaluate structural parameter (or constant): perCHWPum which gives dimensions of array: y. Array dimensions must be known at compile time.](omeditmessagesbrowser:///Buildings.Fluid.Movers.BaseClasses.Characteristics.efficiencyParameters_yMot?lineNumber=5)

[2] 12:21:06 Translation Error
[C:/OpenModelica/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1678:9-1679:95]: Internal error NFCeval.evalRelationGreater failed to evaluate ‘perCHWPum.power.P[1] > 1e-15‘
```

- Opened instance `pla`
- Double-clicked on instance `perCWPum` opens Parameters Window

![image](https://user-images.githubusercontent.com/4007231/193795375-5f903223-1592-4cc3-a777-8d5bbd0d6704.png)

**Comment by perost** [comment]
Considering that we get crash reports where OMEdit seems to just crash randomly when clicking something it might be that there's some memory issue somewhere. We should probably run this through valgrind and see if it picks something up. I can do that later if no one else does it, my valgrind is a bit broken right now it seems.

**Comment by adeas31** [comment]
Some of the issues depends on which operations are performed so they are very difficult to reproduce.

Anyways, this seems related to https://github.com/OpenModelica/OpenModelica/issues/9449 which was fixed in https://github.com/OpenModelica/OpenModelica/commit/9cbaf6232eb3a275f112a1cabbf8af6ea0e7de69.

**Comment by casella** [comment]
> Anyways, this seems related to #9449 which was fixed in [9cbaf62](https://github.com/OpenModelica/OpenModelica/commit/9cbaf6232eb3a275f112a1cabbf8af6ea0e7de69).

@mwetter, you may try with the latest nightly build if you still get the same crash.

**Comment by perost** [comment]
I ran valgrind again without the error limit, but it still didn't show anything fishy going on. So most likely this was just the issue that @adeas31 pointed out that's already been fixed.

**Comment by mwetter** [comment]
I reinstalled the nightly build of OpenModelica, which is still at OpenModelica 1.20.0~dev-319-gbd71b95 built for Ubuntu 20.04.5 LTS.
OMEdit still crashes for the reported sequence of steps and Buildings, commit e1aa85392941766c68b3651c5e38913008235182

**Comment by mwetter** [comment]
> @mwetter this should now be fixed. Nightly builds are available again. Please reopen if there is still any remaining issue.

@casella : I don't think nightly builds are available again. The file 
https://build.openmodelica.org/apt/dists/focal/nightly/binary-amd64/Packages
still points to 1.20.0~dev-336-g8a791ee which I think is at least a week or two old.

**Comment by casella** [comment]
Windows nightly are fine. Unfortunately the Linux build pipeline is stuck, but our expert @sjoelund is currently 100% busy on other stuff, we'll try to get it unstuck ASAP.
