### ISSUE TITLE
Issue with var[end] indexing in Buildings model

### ISSUE THREAD

**Issue by hcasperfu** [OpenModelica/OpenModelica#9465]
### Description
This is related to #9461.
The model `Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel` fails to translate with openmodelica.

### Steps to reproduce
Because the model in question is very complex, I have created a small model as a minimal working example of this problem.
- Check out Buildings library at commit https://github.com/lbl-srg/modelica-buildings/commit/5ed56f3c4c8615fb9da577c4bce32d60b335ed4d (on a debug branch)
- Open `Buildings.Experimental.DHC.Plants.Cooling.Test` in OMEdit
- Click "Check Model"
- It fails with the following error messages:
```
[1] 14:28:19 Translation Error
[Buildings.Fluid.Movers.BaseClasses.Characteristics.efficiencyParameters_yMot: 5:3-6:45]: Could not evaluate structural parameter (or constant): perCWPum which gives dimensions of array: y. Array dimensions must be known at compile time.

[2] 14:28:19 Translation Error
[/var/lib/jenkins1/ws/LINUX_BUILDS/tmp.build/openmodelica-1.19.3/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1670:9-1671:95]: Internal error NFCeval.evalRelationGreater failed to evaluate ‘perCWPum.power.P[1] > 1e-15‘
```
The original model in question should produce the same error messages upon model check.

### Expected behavior
The model should be able to pass translation. It can simulate successfully with both Dymola and optimica.
Please note that we are already excluding this model from simulation in our CI tests because of a division-by-zero error at time 0. So in this issue we only want to have it pass translation, even though it will probably still fail simulation, but that's another problem.

### Version and OS
 - OpenModelica Version 1.19.3
 - OS: Ubuntu 64-bit 20.04.3
 - Modelica Standard Library 4.0.0
 - Modelica Buildings Library
   - The minimal test model was created on a debug branch at https://github.com/lbl-srg/modelica-buildings/commit/5ed56f3c4c8615fb9da577c4bce32d60b335ed4d
   - The model in question is on a development branch at https://github.com/lbl-srg/modelica-buildings/pull/2693/commits/e1aa85392941766c68b3651c5e38913008235182 (This is where the debug branch was branched off of.)

### Additional information
In the minimal test model, if the record `perCWPum` is left unmodified (i.e. removing the `pressure` modification), the test model can translate and simulate in OMEdit with no problem.

**Comment by perost** [comment]
The issue is because the compiler tries to evaluate the `Buildings.Fluid.Movers.BaseClasses.Euler.getPeak` function but fails. There seems to be something going wrong when replacing component references in the function with the actual arguments.

The issue is specifically that `end` in `pressure.dp[end]` isn't replaced correctly like it should, so in case you want to test simulation of the model you can work around the issue by changing:
```Modelica
  parameter Modelica.Units.SI.VolumeFlowRate V_flow_hal = if max(pressure.V_flow) < 1E-6 then 0 else (pressure.V_flow[end] - (pressure.V_flow[end] - pressure.V_flow[end - 1]) / (pressure.dp[end] - pressure.dp[end - 1]) * pressure.dp[end]) / 2 "Half of max flow, max flow is where dp=0";
```
to:
```Modelica
  parameter Integer dp_end = size(pressure.dp, 1);
  parameter Modelica.Units.SI.VolumeFlowRate V_flow_hal = if max(pressure.V_flow) < 1E-6 then 0 else (pressure.V_flow[end] - (pressure.V_flow[end] - pressure.V_flow[end - 1]) / (pressure.dp[dp_end] - pressure.dp[dp_end - 1]) * pressure.dp[dp_end]) / 2 "Half of max flow, max flow is where dp=0";
```
But just to clarify there's nothing wrong with the function as it is, this is a compiler bug that we should to fix.

**Comment by casella** [comment]
@hcasperfu the `Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel` translates without errors with [v. 1.20.0](https://libraries.openmodelica.org/branches/v1.20/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel.err). It is currently broken on [master](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel.err) because of #10029, but that is another story.

It seems that the problem has been solved in the meantime. If not, please reopen this ticket.

**Comment by hcasperfu** [comment]
@casella  Greetings!
Thanks for working on this! But unfortunately I still get the same error with the nightly build (1.21.0~dev-185-g9d983b8).
```
[1] 10:18:29 Translation Error
[Buildings.Fluid.Movers.BaseClasses.Characteristics.efficiencyParameters_yMot: 5:3-6:45]: Could not evaluate structural parameter (or constant): perCHWPum which gives dimensions of array: y. Array dimensions must be known at compile time.

[2] 10:18:29 Translation Error
[/var/lib/jenkins2/ws/LINUX_BUILDS/tmp.build/openmodelica-1.21.0~dev-185-g9d983b8/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1679:9-1680:95]: Internal error NFCeval.evalRelationGreater failed to evaluate ‘perCHWPum.power.P[1] > 1e-15‘
```

It appears I cannot reopen this ticket on github.

**Comment by casella** [comment]
@hcasperfu with the latest version of Buildings on master we don't get that error, we get [this one](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel.err). When and whence did you branch off your debug branch?

**Comment by hcasperfu** [comment]
The code causing trouble has not been merged into master yet. (See the original post "Versions and OS".)
> - The minimal test model was created on a debug branch at https://github.com/lbl-srg/modelica-buildings/commit/5ed56f3c4c8615fb9da577c4bce32d60b335ed4d
> - The model in question is on a development branch at https://github.com/lbl-srg/modelica-buildings/commit/e1aa85392941766c68b3651c5e38913008235182 (This is where the debug branch was branched off of.)

**Comment by casella** [comment]
OK, @perost will have a look ASAP, thanks for reporting.

**Comment by casella** [comment]
@hcasperfu, I just checked [Buildings.DHC.Plants.Cooling.Examples.ElectricChillerParallel](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.DHC.Plants.Cooling.Examples.ElectricChillerParallel.sim) on the Buildings master branch and it's working fine now. I guess the problem has been resolved in the meantime.

If you still see issues with this ticket, please drop a comment and I'll reopen it.
