### ISSUE TITLE
OMEdit crashes when enumeration types are accessed.

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9489]
### Description

When opening the parameter dialogue of a model that contains a enumeration type parameter OMEdit simply crashes

### Steps to Reproduce

1. Open the `Run` model in the attached minimal example package
[EnumTest.mo.zip](https://github.com/OpenModelica/OpenModelica/files/9732727/EnumTest.mo.zip)
2. Double click on the `test` component
3. OMEdit opens the Report Issue dialogue, which will hang for some time if you try to submit a report and then OMEdit crashes or you click cancel and OMEdit crashes immediately. 

### Version and OS

 - OpenModelica Version: OpenModelica 1.20.0~dev-319-gbd71b95
 - OS: Linux

**Comment by adeas31** [comment]
Is already fixed 9cbaf6232eb3a275f112a1cabbf8af6ea0e7de69.

**Comment by dietmarw** [comment]
So when will that fix be available in the nighty for testing?

**Comment by adeas31** [comment]
@sjoelund @perost @adrpo can someone please fix Linux builds.
#9461 is also the same problem.

**Comment by casella** [comment]
@dietmarw, you can check the status of Linux nightlies here: https://test.openmodelica.org/jenkins/job/LINUX_BUILDS/

I checked the Blue Ocean view of the last run: [#1836](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/LINUX_BUILDS/detail/LINUX_BUILDS/1894/pipeline), the only build that is broken is el8, which is a RedHat/CentOS build. Ubuntu builds seem to be fine, and I understand they are published anyway.

@dietmarw can you please run `apt update` and `apt upgrade`, and report the output of `omc --version`? Then, you can compare it with the [commits on master](https://github.com/OpenModelica/OpenModelica/commits/master) to see if you are up or downstream the fix.

**Comment by dietmarw** [comment]
Just done it again  on Ubuntu 22.04.1 and I still get only OpenModelica 1.20.0~dev-319-gbd71b95 from more than a week ago.

**Comment by casella** [comment]
Ah no, wait a minute, build-dep is run, but build isn't. I'll check with @sjoelund

**Comment by dietmarw** [comment]
I can confirm that this works with OpenModelica 1.20.0~dev-336-g8a791ee
