### ISSUE TITLE
Icons are not drawn with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9552]
### Description
For components from our BRSL library icons are not drawn. 

### Steps to Reproduce

Load the BRSL package: ```Rexroth_Generic/package.mo```
Drag the component ```Rexroth_Generic.SignalBlocks.Interfaces.RealInput``` to a new sheet
Actually the icon should look like in picture 1.
Drag the compnent ```exroth_Generic.SignalBlocks.Interfaces.SISO```
For the port symbols, boxes are drawn instead of triangles. See Figures 2 and 3.

### Screenshots
**Picuter 1**
<img width="410" alt="Icons-1" src="https://user-images.githubusercontent.com/12269776/196734310-da40c2a5-bc75-4db8-96fb-93bb32f9dd98.png">
**Picture 2**
<img width="951" alt="Icons-3" src="https://user-images.githubusercontent.com/12269776/196734486-a0c61d0c-2d4e-45d5-a66d-43e22c500354.png">
**Picture 3**
<img width="1073" alt="Icons-2" src="https://user-images.githubusercontent.com/12269776/196734585-a4126253-811f-44d6-a6d2-7b160281a9b5.png">

### Version and OS

 - OpenModelica Version:  v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.2 dev
### Additional Context

@sbaetzing @abuntrock

**Comment by adeas31** [comment]
Duplicate of #9533

**Comment by niklwors** [comment]
I have tested it and in the diagram view it is fixed but the icon in the library browser is still wrong so i reopen the ticket,.

**Comment by adeas31** [comment]
@perost #9586 solved the issue of display of ports in the component. But the instance api fails when called on the ports directly.

```
loadFile("Rexroth_Generic/package.mo");
getErrorString();
getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.RealInput);
getErrorString();
```

```
true
"Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation from Rexroth_Generic.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation from Modelica.
"

"[C:/OpenModelica/OMCompiler/Compiler/NFFrontEnd/NFTyping.mo:193:9-193:116:writable] Error: Internal error NFTyping.typeComponents got uninstantiated class RealInput
"

```

**Comment by adeas31** [comment]
@perost this one is still valid. And is more annoying now since the `getModelInstanceIcon(Rexroth_Generic.SignalBlocks.Interfaces.RealInput)`  works but `getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.RealInput)` doesn not.

**Comment by perost** [comment]
> @perost this one is still valid. And is more annoying now since the `getModelInstanceIcon(Rexroth_Generic.SignalBlocks.Interfaces.RealInput)` works but `getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.RealInput)` doesn not.

I thought I had fixed that, but it seems it was something else related to that I fixed and calling `getModelInstance` on any short class definition seems to fail. I opened an issue for it: #9701.

**Comment by adeas31** [comment]
@perost this is not fixed with #9702

**Comment by perost** [comment]
> 

That's just the usual warnings about a missing inner declaration though, they shouldn't affect the actual functionality. Is there still some issue with the icons though?

**Comment by adeas31** [comment]
Yes, `getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.RealInput)` still doesn't return anything.

**Comment by adeas31** [comment]
Strange. It works from the command line but not from OMEdit.

**Comment by adeas31** [comment]
Here is the script where it doesn't work,

```
loadFile("Rexroth_Generic/package.mo");
getErrorString();
getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.MISO, true);
getErrorString();
getModelInstance(Rexroth_Generic.SignalBlocks.Interfaces.RealInput, true);
getErrorString();
```

**Comment by niklwors** [comment]
I tested this ticket and with the current version in  the diagram view there is only a box drawn and not the correct icon

**Comment by mahge** [comment]
@niklwors If you are on Windows and using the nightly builds, check your `omc` version and make sure you are not using one that does not include the fix. The nightly builds were broken. They will hopefully be fixed and ready for tomorrow.

**Comment by niklwors** [comment]
I already check the included commits and the fix should be included

**Comment by adeas31** [comment]
Hmmmm, that is weird. It works fine for me.

**Comment by niklwors** [comment]
I'll test it again with today's version and let you know then if it works.

**Comment by niklwors** [comment]
<img width="848" alt="ticket" src="https://user-images.githubusercontent.com/12269776/203010111-4e58521f-df5a-4c0e-8d7a-f6f38bdf0c5c.png">
Unfortunately, it still does not work for me.

**Comment by adeas31** [comment]
This is the expected behavior. Since the `RealInput` doesn't have any `Diagram` annotation.

Diagram View

![image](https://user-images.githubusercontent.com/4007231/203048473-8d1a297b-b872-4e5c-bd72-414b7d6282a7.png)

Icon View

![image](https://user-images.githubusercontent.com/4007231/203048678-49e690b9-96b5-4369-9169-bc8c8dc5cf8f.png)

This is due to the latest changes that are done to conform to the Modelica specification,

`For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model.`

**Comment by niklwors** [comment]
Ok, thank you then we will need to  extend our model. I closed the ticked then.
